import snapshot from './conservation-snapshot.json';
import {latest,formatMetric,isStale,type ConservationData} from '../lib/conservation-types';
const profiles = [
{id:'SP-001',name:'Blue crab',latin:'Callinectes sapidus',type:'Species',area:'Tangier Sound',tag:'Estuary',lon:-76.05,lat:38.02,primary:'females',links:['HB-001','AS-002'],desc:'Chesapeake Bay species assessed using the Bay-wide Winter Dredge Survey. Adult females, juveniles, males and total abundance describe the entire Bay, not a population at the Tangier Sound exploration marker.',note:'Adult females indicate spawning potential; juvenile abundance indicates recruitment. These estimates do not assign a global conservation category. Consult the current assessment for management reference points.',source:'https://dnr.maryland.gov/fisheries/pages/blue-crab/dredge.aspx'},
{id:'SP-002',name:'Eastern oyster',latin:'Crassostrea virginica',type:'Species',area:'Harris Creek',tag:'Oyster reef',lon:-76.29,lat:38.76,primary:'spat',links:['HB-002','AS-001'],desc:'Reef-forming Chesapeake Bay species. Recruitment and observed mortality come from Maryland Fall Oyster Survey monitoring bars. These statewide indices are not measurements of the Harris Creek restoration project. Its marker is an exploration anchor only.',note:'Recruitment and mortality measure different aspects of population health. Higher spat counts alone do not establish that disease, habitat or adult abundance has improved. Preliminary results remain labelled.',source:'https://dnr.maryland.gov/fisheries/pages/shellfish-monitoring/reports.aspx'},
{id:'HB-001',name:'Tangier Sound grass habitat',latin:'Submerged aquatic vegetation · TANMH1',type:'Habitat',area:'Tangier Sound',tag:'Estuary',lon:-76.035,lat:38.07,primary:'sav',links:['SP-001','AS-002'],desc:'Underwater grass habitat represented by VIMS segment TANMH1. Annual mapped hectares cover the whole survey segment, beyond this Maryland exploration marker; they are not a local plot or a Maryland-only subtotal.',note:'Underwater grasses provide nursery habitat. Survey coverage, water clarity and preliminary revisions affect year-to-year comparisons. Missing and partially surveyed areas are identified.',source:'https://www.vims.edu/research/units/programs/sav/access/tables/segment_area/'},
{id:'HB-002',name:'Choptank mouth grass habitat',latin:'Submerged aquatic vegetation · CHOMH1',type:'Habitat',area:'Harris Creek',tag:'Estuary',lon:-76.30,lat:38.745,primary:'sav',links:['SP-002','AS-001'],desc:'Regional habitat in VIMS segment CHOMH1, the mouth of the Choptank River. Underwater grass area provides context for the Harris Creek exploration area; it is not oyster reef cover. The marker does not delimit the survey segment.',note:'Whole-segment hectares replace the invented reef-coverage percentage. Compare only equivalent survey coverage and inspect partial-survey flags.',source:'https://www.vims.edu/research/units/programs/sav/access/tables/segment_area/'},
{id:'AS-001',name:'Cambridge monitoring station',latin:'NOAA CO-OPS · station 8571892',type:'Asset',area:'Choptank River',tag:'Equipment',lon:-76.0617,lat:38.5725,station:'8571892',primary:'water_temperature',links:['SP-002','HB-002'],desc:'A real NOAA CO-OPS station at Cambridge. It provides water temperature, water level and verified monthly mean sea level. Position comes from NOAA metadata. Habitat links provide regional context, not co-located measurements.',note:'Operator: NOAA CO-OPS. Battery, calibration and maintenance health are not published in this feed. Recent readings indicate recency, not that every sensor is healthy. Marketplace listings are unrelated demonstrations.',source:'https://tidesandcurrents.noaa.gov/stationhome.html?id=8571892'},
{id:'AS-002',name:'Solomons Island monitoring station',latin:'NOAA CO-OPS · station 8577330',type:'Asset',area:'Patuxent River',tag:'Equipment',lon:-76.4517,lat:38.3172,station:'8577330',primary:'water_temperature',links:['SP-001','HB-001'],desc:'A real NOAA CO-OPS station near the Patuxent River mouth. Readings provide regional Bay context, not conditions measured in Tangier Sound. Current water levels and monthly history are separate from the fixed terrain model.',note:'Operator: NOAA CO-OPS. Battery, servicing and calibration health are unavailable. The thematic Tangier Sound link does not imply co-location or common management.',source:'https://tidesandcurrents.noaa.gov/stationhome.html?id=8577330'}
];
export function buildRecords(data:ConservationData){
 return profiles.map(p=>{
  const metrics=[...(data.metrics[p.id]||[])].sort((a,b)=>Number(b.id===p.primary)-Number(a.id===p.primary));
  const observation=latest(metrics[0]),stationMetadata=p.station?data.stations[p.station]:undefined;
  const status=p.type==='Asset'? !observation||observation.value==null?'No reading':observation.quality==='Flagged by NOAA'?'Flagged reading':isStale(observation)?'Older reading':'Recent reading':observation?.quality==='Preliminary'?'Preliminary':p.type==='Species'?'Annual assessment':'Published survey';
  return {...p,...(stationMetadata?{lon:stationMetadata.lon,lat:stationMetadata.lat}:{}),metrics,observation,stationMetadata,status,metric:formatMetric(observation?.value,metrics[0]?.precision),unit:metrics[0]?.unit||'No imported measurement',trend:metrics[0]?.series.filter(o=>o.value!=null).slice(-5).map(o=>o.value as number)||[]};
 });
}
export const records=buildRecords(snapshot as ConservationData);
export type BayRecord=ReturnType<typeof buildRecords>[number];
