export const topics=['Landscape','Seasonal life','Pressures','Evidence'] as const;
export type Landmark={id:string;region:number;name:string;lon:number;lat:number;kind:'Estuary'|'Study area'|'Coastal connection';note:string};
export type RegionalDetail={subtitle:string;views:readonly [string,string,string,string];sources:{title:string;url:string}[]};
export const regionalDetails:RegionalDetail[]=[
 {subtitle:'Nursery shallows • tidal rivers • Atlantic gateway',views:[
 'Underwater grass beds and marsh edges offer feeding grounds and cover for young blue crabs. A crab can move between shallow refuge, open bottom and deeper water as its size and molt stage change. Tangier Sound provides geographic context for this profile; the lower Bay connects the estuary to Atlantic spawning and larval habitat.',
 'Warm-season activity includes feeding, growth and reproduction. Egg-bearing females move toward the saltier Bay mouth. During winter, adults commonly shelter in deeper sediment, while young crabs may remain in shallow nursery habitat. Wind and tidal transport help determine whether larvae return successfully to the estuary.',
 'Grass loss reduces shelter, particularly for small and soft-shelled crabs. Poor water quality, predation, harvest and winter mortality act together rather than as independent switches. Protecting nursery habitat and water quality supports survival beyond what a catch restriction alone can achieve.',
 'The Chesapeake Bay Program supplies habitat and life-cycle context. Its monitoring and management publications describe different geographic and temporal scales; a regional marker is not a survey station or a local abundance estimate. Open the sources to examine the underlying scope.'
 ],sources:[{title:'Bay habitat and threats',url:'https://www.chesapeakebay.net/discover/faq/category/blue-crabs'},{title:'Migration and environmental variability',url:'https://www.chesapeakebay.net/files/documents/iv.b_blue_crab_abundance_management_strategy.pdf'},{title:'Underwater grass habitat',url:'https://www.chesapeakebay.net/issues/whats-at-risk/underwater-grasses'}]},
 {subtitle:'Barrier-island sounds • river nurseries • ocean inlets',views:[
 'The Albemarle–Pamlico system joins river-dominated waters to coastal sounds behind the Outer Banks. Early juveniles use submerged vegetation near inlets and also oyster habitat. As they develop, some disperse into shallower, lower-salinity parts of the estuary. The map separates the two sounds as orientation landmarks, not sampling stations.',
 'Recruitment and secondary movement redistribute juveniles within the estuary. Studies describe late-summer and early-autumn recruitment and show that storms can alter dispersal into low-salinity habitat. This is a regional pattern, not a fixed annual timetable for every creek.',
 'Nursery habitat condition and fishing pressure both matter. North Carolina’s management page reports declining stock trends and an assessment review process. A fishery-wide assessment should not be read as the population status of an individual sound or inlet.',
 'The state stock assessment describes habitat use and recruitment. The current management page provides assessment updates. Keep biological research, stock estimates and current fishing rules separate: this atlas is not a regulations guide.'
 ],sources:[{title:'NC habitat and recruitment assessment',url:'https://www.deq.nc.gov/marine-fisheries/fisheries-management/blue-crab/2018-blue-crab-stock-assessment/open'},{title:'NC management information',url:'https://www.deq.nc.gov/about/divisions/marine-fisheries/managing-fisheries/fishery-management-plans/blue-crab-management-information'},{title:'Juvenile dispersal study',url:'https://www.sciencedirect.com/science/article/pii/S0022098104005775'}]},
 {subtitle:'Louisiana estuaries • nearshore spawning • larval exchange',views:[
 'Northern Gulf blue crabs occupy connected estuarine and coastal waters. Louisiana’s Barataria and Terrebonne basins are geographic reference points within this wider setting. Adults may remain within an estuary, while female spawning movements and offshore larvae connect estuarine life to nearshore waters.',
 'Females move toward higher-salinity coastal water to spawn. Tides and wind-driven circulation influence larval dispersal and the return of megalopae to estuaries. Recruitment can therefore link neighboring estuaries even when adult movements are more local.',
 'Fishing mortality must be considered alongside growth, recruitment and natural mortality. Larval exchange complicates the idea that every estuary contains a fully isolated stock. A statewide assessment is a management unit, not proof that crab movements stop at a state boundary.',
 'Louisiana’s 2025 assessment defines the assessed stock and describes the life-history assumptions used in its models. It notes likely mixing between estuaries. These basin markers identify the landscape; they are not current catch-density measurements.'
 ],sources:[{title:'Louisiana blue-crab assessment, 2025',url:'https://www.wlf.louisiana.gov/assets/Resources/Publications/Stock_Assesments/Blue_Crab/LABC_Assessment_2025.pdf'}]},
 {subtitle:'Southern Brazil • lagoon nurseries • coastal reproduction',views:[
 'The broad South American record includes a closer look at the Patos Lagoon estuary in southern Brazil. Research distinguishes shallow estuarine habitat used by juveniles and molting crabs from adjacent marine reproductive areas. A single broad-range marker cannot represent that life-stage separation.',
 'A Patos Lagoon study recorded egg-bearing females from November 2008 through May 2009 and again in October 2009, with spawning concentrated around late spring and summer. These are Southern Hemisphere seasons. They should not be replaced with a Chesapeake calendar.',
 'Protection of reproductive females and recognition of juvenile habitat are relevant to recruitment. Studies of larval distribution show why the estuary–coast connection matters. The available studies do not establish present-day abundance throughout Brazil.',
 'The selected sources are regional field studies, not a continental census. One examines reproductive females; another investigates habitat use by life and molt stage. Their sampling periods and locations define how far their findings can be generalized.'
 ],sources:[{title:'Patos reproductive study',url:'https://periodicos.furg.br/atlantica/article/view/2695'},{title:'Life-stage and molt habitat study',url:'https://www.cambridge.org/core/journals/journal-of-the-marine-biological-association-of-the-united-kingdom/article/abs/habitat-use-in-different-life-and-moulting-stages-of-callinectes-sapidus-decapoda-portunidae-in-south-brazilian-estuarine-and-marine-environments/BD9FD504E33C230C3686C42C5D6EA157'},{title:'Estuarine and coastal larvae',url:'https://www.scielo.br/scielo.php?pid=S0104-64972015000200132&script=sci_arttext&tlng=en'}]},
 {subtitle:'Uruguayan coast • lagoon–ocean exchange • southern range',views:[
 'This broad regional record is paired with Rocha Lagoon on Uruguay’s Atlantic coast, east of the Río de la Plata. The two are not the same water body. Rocha provides a documented local research setting within the southern native range and its coastal lagoon fisheries.',
 'Research in Rocha Lagoon examines reproductive strategy through sampled animals rather than assuming that every season resembles conditions farther north. Lagoon exchange with the sea changes environmental conditions; a dated local study is more informative than a universal monthly activity calendar.',
 'Blue crabs support artisanal catches in coastal lagoon systems from Uruguay to Brazil. Understanding reproduction is important when interpreting those catches. The atlas does not infer stock depletion, current harvest limits or present abundance from the existence of a fishery.',
 'The Rocha reproductive study examined 422 individuals and identifies its study coordinates. The regional estuary marker supplies orientation only. Lagoon hydrodynamic research gives environmental context, not a blue-crab population estimate.'
 ],sources:[{title:'Rocha Lagoon reproductive strategy',url:'https://journal.szu.org.uy/index.php/Bol_SZU/en/article/view/334'},{title:'Lagoon environmental study',url:'https://www.int-res.com/articles/meps/207/m207p019.pdf'}]},
 {subtitle:'Ebro Delta • coastal bays • introduced food-web interactions',views:[
 'The Ebro Delta provides a western Mediterranean example of an introduced blue-crab population. Research in its open waters examines trophic relationships as well as abundance. The delta and adjacent coastal bays form a more useful landscape context than treating the whole Mediterranean as one habitat.',
 'Open coastal water is relevant to egg-bearing females. Conditions and sampling methods influence what researchers observe, so a seasonal catch pattern cannot automatically be read as a complete population count. The linked study is the starting point for local interpretation.',
 'Blue crabs interact with native prey and predators and have become a fishery resource in this area. Ecological impact and commercial value can coexist. A harvest opportunity is not evidence that introduction has been harmless or that its impacts have been resolved.',
 'The Ebro study investigates trophic role and predatory interactions in open waters. Its authors explicitly identify remaining gaps in the factors controlling abundance. This atlas therefore does not assign a numeric invasion severity or forecast to these landmarks.'
 ],sources:[{title:'Ebro Delta trophic interactions, 2024',url:'https://riunet.upv.es/entities/publication/40c42b3c-3cbf-4d0b-9516-52c61f62eb0f'}]},
 {subtitle:'Italian lagoons • shellfish production • seasonal field studies',views:[
 'Adriatic coastal lagoons provide contrasting settings for blue-crab research. The Po Delta is associated with shellfish-production impacts, while Lesina Lagoon offers a documented southern Adriatic study of abundance, growth and size structure. Neither site represents every Adriatic shore.',
 'In a 2021–2022 Lesina study, catches rose toward summer and were absent in December and January under that sampling design. Catch rate correlated with temperature. This is evidence of a local seasonal pattern—not proof of winter absence throughout the Adriatic.',
 'A Po Delta field-data study examines ecological and economic damage to clam production. This introduced predator can create a conservation conflict: supporting its population is not the same objective as protecting native shellfish communities.',
 'Lesina results come from a field investigation with specified dates and gear. The linked Po Delta analysis is provided as a research preprint and should be read with that publication status in mind. Neither source is a live monitoring feed.'
 ],sources:[{title:'Lesina abundance and growth study',url:'https://www.mdpi.com/2079-7737/13/12/1051'},{title:'Po Delta impacts — research preprint',url:'https://arxiv.org/abs/2502.07095'}]},
 {subtitle:'Northern Aegean • river-mouth habitat • regional fisheries',views:[
 'The Evros estuary and Thermaikos Gulf give geographic anchors for the northern Aegean. Research from the Evros examines the species’ complex life cycle in an introduced estuarine population. These are local examples within a much larger eastern Mediterranean region.',
 'The Evros study describes a life-cycle pattern broadly consistent with the species’ estuarine–coastal life history. Its local observations are preferable to importing exact spawning dates from the Atlantic. Seasonal conditions and sampling location affect which life stages are encountered.',
 'Introduced populations interact with local fisheries and ecosystems. Abundance can change markedly, and the history of a fishery does not establish a permanent level of stock productivity. Assessments should distinguish local observations from assumptions about the entire eastern basin.',
 'The regional fisheries-biology paper provides the principal evidence here. It also discusses the Thermaikos fishery as regional context. Landmark coordinates are approximate orientation points, not the precise positions of biological samples.'
 ],sources:[{title:'Evros fisheries biology and life cycle',url:'https://utopia.duth.gr/~amogias/Papers/C23.pdf'}]},
 {subtitle:'Bulgarian records • reproductive evidence • uncertain coverage',views:[
 'Published Bulgarian records provide a more specific starting point than a marker in the center of the Black Sea. Varna Bay and Cape Shabla are documented localities. Records along one coast must not be expanded into a claim of continuous occupation around the entire sea.',
 'An egg-bearing female was reported from Varna Bay in 2005. A later paper reports a male captured near Cape Shabla in April 2024. These observations concern different places and dates; they do not establish a complete regional reproductive calendar.',
 'Expansion of an introduced predator warrants monitoring, but occurrence reports alone cannot quantify ecological damage or population size. Reproductive observations add important evidence without resolving all questions about establishment and recruitment.',
 'A 2021 paper compiles thirteen Bulgarian records since 2006 and discusses evidence of expansion. The Cape Shabla paper adds a later occurrence. Both are useful records with limited spatial coverage, not a standardized basin-wide abundance survey.'
 ],sources:[{title:'Bulgarian expansion records, 2021',url:'https://zenodo.org/records/4719855'},{title:'Cape Shabla occurrence',url:'https://doi.uni-plovdiv.bg/items/3b9a2afc-2172-4fbb-bc3c-8a3dab8b783b'}]}
];
export const landmarks:Landmark[]=[
 {id:'tangier',region:0,name:'Tangier Sound',lon:-76.05,lat:38.02,kind:'Estuary',note:'Archive setting in the Chesapeake system; a geographic reference, not a survey station.'},
 {id:'bay-mouth',region:0,name:'Lower Chesapeake Bay',lon:-76.1,lat:37.05,kind:'Coastal connection',note:'Orientation point for the estuary’s connection with Atlantic waters.'},
 {id:'pamlico',region:1,name:'Pamlico Sound',lon:-75.9,lat:35.35,kind:'Estuary',note:'Sound within the Albemarle–Pamlico nursery and dispersal setting.'},
 {id:'albemarle',region:1,name:'Albemarle Sound',lon:-76.15,lat:36.03,kind:'Estuary',note:'Northern sound in the connected North Carolina estuarine system.'},
 {id:'barataria',region:2,name:'Barataria Bay',lon:-89.95,lat:29.4,kind:'Estuary',note:'Louisiana basin orientation point; no local abundance is implied.'},
 {id:'terrebonne',region:2,name:'Terrebonne Bay',lon:-90.6,lat:29.2,kind:'Estuary',note:'Coastal basin associated with Louisiana blue-crab life-history research.'},
 {id:'patos',region:3,name:'Patos Lagoon estuary',lon:-52.1,lat:-32.05,kind:'Study area',note:'Regional research setting for reproduction, juvenile habitat and molting.'},
 {id:'patos-coast',region:3,name:'Patos coastal outlet',lon:-52.08,lat:-32.2,kind:'Coastal connection',note:'Approximate lagoon–ocean gateway, relevant to the estuary/coast life-cycle distinction.'},
 {id:'rocha',region:4,name:'Rocha Lagoon',lon:-54.367,lat:-34.55,kind:'Study area',note:'Uruguayan reproductive-study locality; east of the Río de la Plata.'},
 {id:'plata',region:4,name:'Río de la Plata mouth',lon:-55.5,lat:-35.2,kind:'Coastal connection',note:'Broad geographic landmark at the estuary–Atlantic transition, not a sample record.'},
 {id:'ebro',region:5,name:'Ebro Delta',lon:.85,lat:40.72,kind:'Study area',note:'Western Mediterranean setting for blue-crab food-web research.'},
 {id:'alfacs',region:5,name:'Alfacs Bay',lon:.65,lat:40.6,kind:'Estuary',note:'Coastal-bay landmark on the southern side of the Ebro Delta; geographic context.'},
 {id:'po',region:6,name:'Po Delta',lon:12.3,lat:44.95,kind:'Study area',note:'Research context for blue-crab impacts on shellfish production.'},
 {id:'lesina',region:6,name:'Lesina Lagoon',lon:15.45,lat:41.88,kind:'Study area',note:'Southern Adriatic abundance, size and growth investigation.'},
 {id:'evros',region:7,name:'Evros estuary',lon:26.03,lat:40.83,kind:'Study area',note:'Fisheries-biology and life-cycle research setting in the northeast Aegean.'},
 {id:'thermaikos',region:7,name:'Thermaikos Gulf',lon:22.8,lat:40.3,kind:'Coastal connection',note:'Northwest Aegean fishery setting discussed in regional research.'},
 {id:'varna',region:8,name:'Varna Bay',lon:27.96,lat:43.18,kind:'Study area',note:'Published locality of a 2005 egg-bearing female; not a current sighting.'},
 {id:'shabla',region:8,name:'Cape Shabla',lon:28.61,lat:43.54,kind:'Study area',note:'Approximate locality of a published April 2024 occurrence.'}
];
