import {useState} from 'react';
import {CrabBodyInspector} from './crab-body-inspector';
import './crab-biology-lab.css';
type Response={name:string;signal:string;response:string;body:string;source:string};
const signals=[
 {name:'Chemical cues',sensor:'Antennules & leg receptors',integration:'Combine odor with flow',action:'Orient the search',steps:['Chemical receptors sample dissolved substances at different points around the body. Antennules and legs contribute information during odor tracking.','Experiments link the timing of odor filaments and the crab’s preceding movement to subsequent upstream motion. Signals from different appendages interact.','The animal adjusts its movement while searching. This is documented sensory-guided behavior, not a claim that every odor produces a fixed response.'],source:'https://pubmed.ncbi.nlm.nih.gov/21490258/'},
 {name:'Visual cues',sensor:'Stalked compound eyes',integration:'Coordinate sensory input',action:'Respond to the encounter',steps:['Compound eyes on movable stalks gather visual information. Their placement allows the crab to inspect its surroundings without relying on smell alone.','The brain and connected nerve centers coordinate sensory input with appendage movement. Vision is one contributor within that network.','An approaching animal may prompt defense or escape. The situation, available shelter and condition of the crab affect what happens next.'],source:'https://lanwebs.lander.edu/faculty/rsfox/invertebrates/callinectes.html'},
 {name:'Contact & movement',sensor:'Sensory appendages',integration:'Coordinate body and limbs',action:'Handle food or reposition',steps:['Sensory information is gathered through appendages as the crab encounters its surroundings. Chemical sensing also occurs on limbs, not only at the front of the head.','A brain linked to a thoracic nerve center supports coordinated movement. Feeding rhythms also involve specialized stomatogastric circuits.','Jointed limbs can walk, manipulate food, defend or swim. These functions share the body’s nervous and muscular systems rather than acting as independent tools.'],source:'https://lanwebs.lander.edu/faculty/rsfox/invertebrates/callinectes.html'}
];
const systems=[
 {name:'Nervous coordination',label:'SIGNALS',color:'#c9b3ef',body:'The brain connects around the esophagus to a thoracic nerve center. Sensory input and limb movement are coordinated across this network. Specialized circuits also organize rhythmic activity involved in feeding and digestion.',connection:'Links sensory receptors with coordinated action.'},
 {name:'Gills & salt balance',label:'EXCHANGE',color:'#a1ddeb',body:'Gills occupy chambers beneath the carapace. They exchange respiratory gases and participate in regulating salts as the crab moves through estuarine conditions.',connection:'Connects the internal environment to surrounding water.'},
 {name:'Heart & circulation',label:'TRANSPORT',color:'#efb2a7',body:'The heart circulates hemolymph through the body. In the blue crab, a cardiac ganglion participates in driving heart activity; circulation connects tissues with respiratory exchange.',connection:'Moves materials between organs and tissues.'},
 {name:'Digestion & growth',label:'RESOURCES',color:'#e9ce91',body:'The stomach and digestive glands process food. Muscles act against the exoskeleton, while molting allows an increase in body size. The new covering is initially soft before it hardens.',connection:'Feeding supplies resources; molting makes physical growth possible.'}
];
const tabs=['Mind & senses','Body & functions','Disposition & responses'];
export function CrabBiologyLab({responses}:{responses:Response[]}){
 const [tab,setTab]=useState(0),[signal,setSignal]=useState(0),[stage,setStage]=useState(0),[system,setSystem]=useState(0),[context,setContext]=useState(0),[compare,setCompare]=useState<number|null>(null);
 const [bodyFocus,setBodyFocus]=useState<{index:number;token:number}>();
 const cue=signals[signal],organ=systems[system],response=responses[context];
 const changeTab=(i:number)=>setTab(i);
 return <div className="bio-lab"><header className="bio-header"><span className="poc-eyebrow">LIVING SYSTEMS / BLUE CRAB</span><h4>One organism. Connected systems.</h4><p>Follow a signal, inspect a structure, or explore how context changes behavior.</p></header>
 <div className="bio-tabs" role="tablist" aria-label="Biology explorer">{tabs.map((name,i)=><button key={name} role="tab" id={'bio-tab-'+i} aria-controls="bio-panel" aria-selected={tab===i} tabIndex={tab===i?0:-1} onClick={()=>changeTab(i)} onKeyDown={e=>{const next=e.key==='ArrowRight'?(i+1)%3:e.key==='ArrowLeft'?(i+2)%3:e.key==='Home'?0:e.key==='End'?2:null;if(next!==null){e.preventDefault();changeTab(next);document.getElementById('bio-tab-'+next)?.focus()}}}><span>0{i+1}</span>{name}</button>)}</div>
 <div id="bio-panel" role="tabpanel" aria-labelledby={'bio-tab-'+tab}>
 <section className="bio-mind" hidden={tab!==0}><div className="bio-section-title"><span>SENSORY PATHWAYS</span><h5>From information to action</h5><p>Select a cue, then trace its three explanatory stages.</p></div><div className="bio-choice-row" role="group" aria-label="Sensory cue">{signals.map((s,i)=><button key={s.name} aria-pressed={signal===i} onClick={()=>{setSignal(i);setStage(0)}}>{s.name}</button>)}</div>
 <div className="bio-signal-diagram"><svg viewBox="0 0 900 150" aria-hidden="true"><defs><linearGradient id="bio-path"><stop stopColor="#a5dcd5"/><stop offset=".5" stopColor="#c9b3ef"/><stop offset="1" stopColor="#e9ce91"/></linearGradient></defs><path d="M150 75H750" fill="none" stroke="url(#bio-path)" strokeWidth="2"/>{[150,450,750].map((x,i)=><g key={x}><circle cx={x} cy="75" r={stage===i?47:34} fill={stage===i?'#30554b':'#122b2e'} stroke={['#a5dcd5','#c9b3ef','#e9ce91'][i]} strokeWidth="2"/><circle cx={x} cy="75" r="8" fill={['#a5dcd5','#c9b3ef','#e9ce91'][i]}/>{stage===i&&<circle className="bio-pulse" cx={x} cy="75" r="56" fill="none" stroke="#b7ebd544"/>}</g>)}</svg><div className="bio-stage-buttons" role="group" aria-label="Signal pathway stage">{[cue.sensor,cue.integration,cue.action].map((label,i)=><button key={label} aria-pressed={stage===i} onClick={()=>setStage(i)}><small>{['01 · DETECT','02 · INTEGRATE','03 · RESPOND'][i]}</small><strong>{label}</strong></button>)}</div></div>
 <div className="bio-reading" aria-live="polite"><span className="poc-eyebrow">{['Detection','Integration','Response'][stage]}</span><p>{cue.steps[stage]}</p><div className="bio-reading-actions"><button disabled={stage===0} onClick={()=>setStage(stage-1)}>← Previous</button><button disabled={stage===2} onClick={()=>setStage(stage+1)}>Next stage →</button><a href={cue.source} target="_blank" rel="noreferrer">Supporting research ↗</a></div></div>
 <div className="bio-consciousness"><div><span className="poc-eyebrow">MIND / CONSCIOUS EXPERIENCE</span><h5>What can the evidence tell us?</h5><p>Blue-crab experiments demonstrate sensory integration during navigation. Processing a signal, however, does not by itself reveal what the animal experiences.</p></div><details><summary>Sentience and the open questions</summary><p>A review of more than 300 studies evaluates sentience in decapods and cephalopods. It considers converging evidence, rather than treating a single reflex as decisive. The broader decapod evidence and the specific question of a blue crab’s subjective experience are different levels of inquiry.</p><a href="https://www.lse.ac.uk/business/consulting/reports/review-of-the-evidence-of-sentiences-in-cephalopod-molluscs-and-decapod-crustaceans" target="_blank" rel="noreferrer">Read the evidence review ↗</a></details></div></section>
 <section hidden={tab!==1}><CrabBodyInspector focusRequest={bodyFocus}/><div className="bio-internal"><div className="bio-section-title"><span>INTERNAL FUNCTIONS</span><h5>Inside the protective shell</h5><p>A functional diagram—not an anatomical section or measured organ placement.</p></div><div className="bio-internal-grid"><div><svg viewBox="0 0 500 380" role="group" aria-label="Internal functional systems"><path d="M75 170Q110 55 250 65Q390 55 425 170L455 195L413 204Q370 310 250 320Q130 310 87 204L45 195Z" fill="#173731" stroke="#759b8744" strokeWidth="2"/>{systems.map((s,i)=>{const x=[170,330,170,330][i],y=[140,140,250,250][i];return <g key={s.name} role="button" tabIndex={0} aria-label={'Inspect '+s.name} aria-pressed={system===i} onClick={()=>setSystem(i)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setSystem(i)}}}><path d={`M250 195L${x} ${y}`} stroke={s.color} opacity=".4"/><circle cx={x} cy={y} r="44" fill={system===i?'#36524a':'#11292c'} stroke={s.color} strokeWidth={system===i?3:1}/><text x={x} y={y+4} textAnchor="middle" fill={s.color} fontSize="11">{s.label}</text></g>})}<circle cx="250" cy="195" r="18" fill="#c1e8cf"/><text x="250" y="350" textAnchor="middle" fill="#8aaa9c" fontSize="10">FUNCTIONAL CONNECTIONS · SCHEMATIC</text></svg><div className="bio-choice-row" aria-label="Internal system list">{systems.map((s,i)=><button key={s.name} aria-pressed={system===i} onClick={()=>setSystem(i)}>{s.name}</button>)}</div></div><div className="bio-reading" aria-live="polite"><span className="poc-eyebrow">{organ.label}</span><h5>{organ.name}</h5><p>{organ.body}</p><blockquote>{organ.connection}</blockquote><a href={system===2?'https://link.springer.com/article/10.1186/1471-2202-10-S1-P295':'https://lanwebs.lander.edu/faculty/rsfox/invertebrates/callinectes.html'} target="_blank" rel="noreferrer">Anatomy & evidence ↗</a></div></div></div></section>
 <section className="bio-disposition" hidden={tab!==2}><div className="bio-section-title"><span>BEHAVIOR OBSERVATORY</span><h5>Different conditions. Different responses.</h5><p>Explore observed contexts—not a prediction of an individual crab’s mood.</p></div><div className="bio-context-grid">{responses.map((r,i)=><button key={r.name} aria-pressed={context===i} onClick={()=>{setContext(i);if(compare===i)setCompare(null)}}><span>0{i+1}</span><strong>{r.name}</strong><small>{r.signal}</small></button>)}</div><div className="bio-response-flow"><div><small>CONTEXT</small><strong>{response.signal}</strong></div><span aria-hidden="true">→</span><div><small>OBSERVED RESPONSE</small><strong>{response.response}</strong></div></div><div className="bio-reading" aria-live="polite"><p>{response.body}</p><a href={response.source} target="_blank" rel="noreferrer">Supporting source ↗</a></div><div className="bio-crosslinks">{context===0?<button onClick={()=>{setTab(0);setSignal(0);setStage(0)}}>Trace the food-cue pathway →</button>:context===1||context===2?<button onClick={()=>{setTab(1);setBodyFocus({index:context===1?3:0,token:Date.now()})}}>Inspect {context===1?'the claws':'the protective shell'} →</button>:<a href="#crab-world-map">Explore seasonal habitat context →</a>}</div><div className="bio-compare"><label>Compare with another context <select aria-label="Compare behavioral contexts" value={compare??''} onChange={e=>setCompare(e.target.value===''?null:Number(e.target.value))}><option value="">Choose a context…</option>{responses.map((r,i)=><option key={r.name} value={i} disabled={i===context}>{r.name}</option>)}</select></label>{compare!==null&&compare!==context&&<div className="bio-comparison">{[response,responses[compare]].map(r=><article key={r.name}><span className="poc-eyebrow">{r.name}</span><h5>{r.response}</h5><p>{r.body}</p><a href={r.source} target="_blank" rel="noreferrer">Evidence ↗</a></article>)}</div>}</div></section>
 </div><footer className="bio-lab-note">Explanatory pathways and observed contexts. Detailed descriptions and original references continue below.</footer></div>
}
