import {useEffect,useRef,useState} from 'react';
import {Search,Type,Link,Check,X} from 'lucide-react';
import categories from './crab-categories.json';
import merged from './crab-merged.json';
type Section={id:string;title:string;paragraphs:{text:string}[];children:Section[]};
const flatten=(ss:Section[]):Section[]=>ss.flatMap(s=>[s,...flatten(s.children)]);
const sources=new Map(flatten(merged.sections).map(s=>[s.id,s]));
const entries=categories[0].sections.map(s=>{const item=s as {source:string;id?:string;cluster?:string;subsection?:string;paragraphs?:number[]};const section=sources.get(item.source)!;return {id:item.id||item.source,title:[item.cluster,item.subsection].filter(Boolean).join(' / '),body:(item.paragraphs?item.paragraphs.map(i=>section.paragraphs[i]):section.paragraphs).map(p=>p.text).join(' ')}});
export function CrabReaderWorkspace(){const [query,setQuery]=useState(''),[size,setSize]=useState('Standard'),[copy,setCopy]=useState(''),[open,setOpen]=useState(false);const dialog=useRef<HTMLDialogElement>(null),trigger=useRef<HTMLButtonElement>(null);useEffect(()=>{const root=document.getElementById('crab-category-overview');if(root)root.dataset.readingSize=size;return()=>{if(root)delete root.dataset.readingSize}},[size]);useEffect(()=>{if(open)dialog.current?.showModal()},[open]);const words=query.toLowerCase().trim().split(/\s+/).filter(Boolean);const results=entries.filter(e=>words.every(w=>(e.title+' '+e.body).toLowerCase().includes(w)));async function copyLink(){try{await navigator.clipboard.writeText(location.href);setCopy('Link copied')}catch{setCopy('Copy unavailable—use the address bar')}}return <div className="reader-workspace"><button ref={trigger} onClick={()=>setOpen(true)}><Search size={16}/><span>Find in Overview</span></button><div role="group" aria-label="Article text size"><Type size={15}/>{['Standard','Large'].map(s=><button key={s} onClick={()=>setSize(s)} aria-pressed={size===s}>{s}</button>)}</div><button onClick={copyLink}>{copy==='Link copied'?<Check size={15}/>:<Link size={15}/>} Copy page link</button>{copy&&<span className="reader-copy-status" role="status">{copy}</span>}{open&&<dialog ref={dialog} className="reader-dialog" onKeyDown={e=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();dialog.current?.close()}}} aria-labelledby="reader-search-title" onCancel={()=>{setOpen(false);trigger.current?.focus()}} onClose={()=>{setOpen(false);trigger.current?.focus()}}><header><div><span className="poc-eyebrow">OVERVIEW / CONTENT SEARCH</span><h3 id="reader-search-title">Find an idea, not just a heading.</h3></div><button aria-label="Close Overview search" onClick={()=>dialog.current?.close()}><X size={20}/></button></header><label><span>Search article text and topics</span><input autoFocus type="search" placeholder="Try sensory, mythology, evolution…" value={query} onChange={e=>setQuery(e.target.value)}/></label><p role="status">{results.length} matching passages · original article text</p><div className="reader-search-results">{results.map((r,i)=><a key={r.id+i} href={'#'+r.id} onClick={()=>{dialog.current?.close()}}><strong>{r.title}</strong><span>{r.body.slice(0,220)}{r.body.length>220?'…':''}</span><small>Go to passage →</small></a>)}{!results.length&&<div className="reader-no-results"><p>No passage matches every search word.</p><button onClick={()=>setQuery('')}>Clear search</button></div>}</div><p className="poc-disclaimer">Search covers Overview’s source article passages. The belief directory and questions have their own specialized searches.</p></dialog>}</div>}
