import {useState} from 'react';

const images={
 animation:[
  {title:'Bronze crab',url:'https://images.metmuseum.org/CRDImages/gr/original/DP20970.jpg',credit:'The Metropolitan Museum of Art · 1992.11.69 · public domain',caption:'Greek, Hellenistic, third–first century BCE. Comparative crab art; species unspecified.',source:'https://www.metmuseum.org/art/collection/search/256125'},
  {title:'Crab from Cleopatra’s Needle',url:'https://images.metmuseum.org/CRDImages/eg/original/81.2.2_EGDP014597.jpg',credit:'The Metropolitan Museum of Art · 81.2.2 · public domain',caption:'Roman, 13 BCE. A bronze architectural support, not a blue-crab specimen.',source:'https://www.metmuseum.org/art/collection/search/551894'}
 ],
 graphics:[
  {title:'Blue crab illustration',url:import.meta.env.BASE_URL+'blue-crab-hero.png',credit:'Existing Labyrinth archive illustration',caption:'Illustrative anatomy, not a specimen photograph or calibrated measurement.',source:'https://lanwebs.lander.edu/faculty/rsfox/invertebrates/callinectes.html'},
  {title:'Field researcher with blue crab',url:'https://ecosystemsontheedge.org/wp-content/uploads/2013/05/tuck_crabs300x351.jpg',credit:'Smithsonian · Ecosystems on the Edge · source-hosted photograph',caption:'Marine biologist Tuck Hines. Research context from the historical documentary collection.',source:'https://ecosystemsontheedge.org/top-predator/'}
 ]
};
export function CrabObjectGallery({section}:{section:'animation'|'graphics'}){const [selected,setSelected]=useState(0),[zoom,setZoom]=useState(false),[failed,setFailed]=useState(false);const list=images[section],item=list[selected];return <section className="crab-object-gallery"><h4>{section==='animation'?'Museum object gallery':'Visual reference gallery'}</h4><div role="group" aria-label="Choose an image">{list.map((im,i)=><button key={im.title} aria-pressed={selected===i} onClick={()=>{setSelected(i);setZoom(false);setFailed(false)}}>{im.title}</button>)}</div><figure><div className={'crab-gallery-frame'+(zoom?' is-magnified':'')} tabIndex={0} aria-label="Image viewport; scroll to inspect a magnified image">{!failed?<img key={item.url} src={item.url} alt={item.title+'. '+item.caption} loading="lazy" onError={()=>setFailed(true)}/>:<p>The image host could not be reached. <a href={item.source} target="_blank" rel="noreferrer">Inspect the original museum or research record ↗</a></p>}</div><figcaption><strong>{item.title}</strong><p>{item.caption}</p><small>{item.credit}</small></figcaption></figure><button onClick={()=>setZoom(!zoom)} disabled={failed}>{zoom?'Fit image':'Magnify image'}</button> <a href={item.source} target="_blank" rel="noreferrer">Original object &amp; provenance ↗</a></section>}

const habitats=[
 {label:'Upper estuary',x:105,y:108,body:'Compare the archive’s accounts of juvenile habitat, feeding and adult distribution. “Upper” describes position, not a fixed salinity value.'},
 {label:'Vegetated shallows',x:250,y:190,body:'Inspect the relationship between structural cover, smaller crabs and predator exposure. This patch is illustrative, not a mapped seagrass survey.'},
 {label:'Bottom sediment',x:390,y:240,body:'Connect concealment and seasonal refuge with the sediment record in Infrastructure. The drawing does not imply every bottom type is suitable.'},
 {label:'Bay mouth / coast',x:510,y:130,body:'Follow the reproductive-migration and larval-life records. A generalized habitat sequence is not a prediction of an individual crab’s route.'}
];
export function CrabHabitatDiagram(){const [active,setActive]=useState(0);return <section className="crab-habitat-diagram"><h4>Inspect the estuary</h4><p>Conceptual habitat cross-section. Select a location; this is not a geographic map or measured environmental model.</p><svg viewBox="0 0 620 300" role="img" aria-label="Illustrative estuary from upper waters to coast"><path d="M0 65Q140 40 270 70T620 55V300H0Z" fill="#153e54"/><path d="M0 140Q100 180 240 225T620 270V300H0Z" fill="#77694c"/><path d="M0 65Q140 40 270 70T620 55" fill="none" stroke="#9bd1dc" strokeWidth="3"/>{[205,225,245,265,285].map(x=><path key={x} d={`M${x} 233q-14 -40 -5 -65m5 65q20 -32 12 -52`} stroke="#82ad77" strokeWidth="4" fill="none"/>)}{habitats.map((h,i)=><g key={h.label}><circle cx={h.x} cy={h.y} r={active===i?20:15} fill={active===i?'#f0cc87':'#def1ee'}/><text x={h.x} y={h.y+5} textAnchor="middle" fill="#102b32" fontSize="15">{i+1}</text></g>)}</svg><div className="crab-pathway-steps">{habitats.map((h,i)=><button key={h.label} aria-pressed={active===i} onClick={()=>setActive(i)}>{i+1}. {h.label}</button>)}</div><p aria-live="polite">{habitats[active].body}</p><a href="https://www.chesapeakebay.net/discover/field-guide/entry/blue-crab" target="_blank" rel="noreferrer">Habitat reference · Chesapeake Bay Program ↗</a></section>}

export function CrabSurveyDiagram(){const [distance,setDistance]=useState(100),[width,setWidth]=useState(2);return <section className="crab-survey-diagram"><h4>Inspect a survey footprint</h4><p>Illustrative geometry of a dredge tow—not an actual tow, survey result or official gear specification. Change the dimensions to see why sampling area matters.</p><svg viewBox="0 0 600 170" role="img" aria-label={`Illustrative rectangular tow footprint, ${distance} by ${width} metres`}><rect x="60" y="35" width={distance*2} height={width*20} fill="#153e54" stroke="#83c1d1" strokeWidth="2"/><path d={`M60 20H${60+distance*2}`} stroke="currentColor"/><text x="60" y="155" fill="currentColor">Tow footprint = distance × gear width</text></svg><label>Tow distance (illustrative): {distance} m<input aria-label="Illustrative tow distance" type="range" min="20" max="240" step="10" value={distance} onChange={e=>setDistance(Number(e.target.value))}/></label><label>Gear width (illustrative): {width.toFixed(1)} m<input aria-label="Illustrative gear width" type="range" min=".5" max="5" step=".5" value={width} onChange={e=>setWidth(Number(e.target.value))}/></label><output>Sampled rectangle: {(distance*width).toLocaleString()} m²</output><p>Real abundance estimation also needs catch observations, sampling design and efficiency corrections. This calculation supplies none of those.</p><a href="https://dnr.maryland.gov/fisheries/pages/blue-crab/dredge.aspx" target="_blank" rel="noreferrer">Published survey method ↗</a></section>}
