import {useState} from 'react';
const features=[
 {name:'Carapace',x:50,y:32,system:'Protection & support',description:'The broad dorsal covering protects the fused head and thorax. The exoskeleton combines chitin and proteins with mineral reinforcement; it must be shed for the crab to grow.',source:'https://journals.biologists.com/jeb/article/210/24/4272/17258/Mechanical-properties-of-the-rigid-and-hydrostatic'},
 {name:'Compound eyes',x:41,y:44,system:'Visual sensing',description:'Eyes on movable stalks gather visual information from the surroundings. Vision works alongside chemical and contact sensing; it is not the crab’s only way of locating food or responding to danger.',source:'https://lanwebs.lander.edu/faculty/rsfox/invertebrates/callinectes.html'},
 {name:'Swimming paddles',x:25,y:15,system:'Movement through water',description:'The flattened final pair of legs acts as paddles, distinguishing swimming crabs from forms that rely primarily on walking. They complement movement along the bottom.',source:'https://www.dnr.sc.gov/marine/pub/seascience/bluecrab.html'},
 {name:'Claws',x:27,y:64,system:'Feeding & defense',description:'The first pair of legs bears the claws. They grasp and handle food and can be used in defense. These jointed appendages combine a rigid exterior with muscles that act across the joints.',source:'https://lanwebs.lander.edu/faculty/rsfox/invertebrates/callinectes.html'},
 {name:'Walking legs',x:12,y:48,system:'Bottom locomotion',description:'Three pairs of walking legs support movement across the bottom. Together with the claw-bearing pair and rear paddle pair, they make the five pairs of legs characteristic of decapods.',source:'https://www.dnr.sc.gov/marine/pub/seascience/bluecrab.html'}
];
export function CrabBodyInspector(){const [active,setActive]=useState(0),[zoom,setZoom]=useState(1);const feature=features[active];return <div className="body-inspector"><header><div><span className="poc-eyebrow">FORM / FUNCTION EXPLORER</span><h4>Inspect the organism</h4></div><button onClick={()=>setZoom(zoom===1?2:1)}>{zoom===1?'Magnify selected feature':'Show whole organism'}</button></header><div className="body-inspector-grid"><div><div className="body-portrait-window"><div className="body-portrait-transform" style={{transform:`scale(${zoom})`,transformOrigin:`${feature.x}% ${feature.y}%`}}><img src={`${import.meta.env.BASE_URL}blue-crab-hero.png`} alt="Blue-crab illustration with selectable external structures" width="1672" height="941" loading="lazy"/>{features.map((f,i)=><button key={f.name} className="body-hotspot" style={{left:f.x+'%',top:f.y+'%',transform:`translate(-50%,-50%) scale(${1/zoom})`}} aria-label={'Inspect '+f.name} aria-pressed={active===i} onClick={()=>setActive(i)}>{i+1}</button>)}</div></div><div className="body-feature-list" role="group" aria-label="Anatomical structures">{features.map((f,i)=><button key={f.name} onClick={()=>setActive(i)} aria-pressed={active===i}><span>0{i+1}</span>{f.name}</button>)}</div></div><div className="body-feature-detail" aria-live="polite"><span className="poc-eyebrow">{feature.system}</span><h5>{feature.name}</h5><p>{feature.description}</p><a href={feature.source} target="_blank" rel="noreferrer">Anatomy &amp; evidence ↗</a><p className="poc-disclaimer">Annotated illustration, not a diagnostic or anatomically measured specimen. Internal systems are described in the sourced text below.</p></div></div></div>}
