import {useEffect,useRef,useState} from 'react';
import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';

const parts=[
 {id:'all',name:'Whole crab',text:'Compare the broad shell, five appendage pairs and ventral abdomen. This locally generated educational model is schematic—not a specimen scan or a metrically validated sculpt.'},
 {id:'shell',name:'Carapace',text:'The dorsal covering spans the cephalothorax. Lateral points distinguish the broad silhouette. Surface ornament here is illustrative, not specimen-derived.'},
 {id:'claws',name:'Claw-bearing pair',text:'The first appendage pair carries the chelae. Compare the articulated arm, palm and opposing fingers; the grip control is an illustrative hinge.'},
 {id:'legs',name:'Walking legs',text:'Three pairs of jointed walking legs lie between the claw-bearing pair and the rear swimming pair. Segments are simplified for inspection.'},
 {id:'paddles',name:'Swimming pair',text:'The final pair ends in flattened swimming paddles. Compare the paddle surface with a narrow walking-leg tip.'},
 {id:'eyes',name:'Stalked eyes',text:'The paired eyes project from the front of the body. The model shows their placement, not microscopic compound-eye structure.'},
 {id:'abdomen',name:'Ventral abdomen',text:'A folded abdominal apron is represented on the underside. Its simplified broad form illustrates the female configuration; sex identification requires the actual specimen reference.'},
 {id:'gills',name:'Gill chambers',text:'Paired schematic gill arrays sit beneath the carapace. Their arrangement is illustrative and is not reconstructed from internal scanning.'},
 {id:'mouth',name:'Mouthparts',text:'Layered appendages around the mouth are represented as simplified plates. Consult the dissection reference for their individual identities.'},
 {id:'antennae',name:'Antennae & antennules',text:'Paired anterior sensory appendages are shown separately from the eyes. Fine sensory hairs are a schematic surface detail, not microscopic evidence.'},
 {id:'sternum',name:'Ventral sternum',text:'The ventral surface connects appendage bases and supports the folded abdomen. Segment boundaries are simplified.'}
];
export function CrabComponentModel(){const mount=useRef<HTMLDivElement>(null);const api=useRef<{select:(id:string)=>void;explode:(value:boolean)=>void;grip:(value:number)=>void;zoom:(factor:number)=>void;reset:()=>void}|null>(null);const [part,setPart]=useState('all'),[exploded,setExploded]=useState(false),[grip,setGrip]=useState(25),[failure,setFailure]=useState('');
 useEffect(()=>{const el=mount.current;if(!el)return;let renderer:THREE.WebGLRenderer;try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:true})}catch{setFailure('This browser cannot create the 3D view. The anatomy illustration and source sculpt remain available below.');return}renderer.setPixelRatio(Math.min(devicePixelRatio,2));el.appendChild(renderer.domElement);renderer.domElement.setAttribute('aria-label','Interactive schematic blue crab; drag to orbit, scroll to zoom');renderer.domElement.tabIndex=0;const scene=new THREE.Scene();scene.background=new THREE.Color('#11272e');const camera=new THREE.PerspectiveCamera(40,1,.1,100);camera.up.set(0,0,1);camera.position.set(0,-10,10);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=1.5;controls.maxDistance=22;scene.add(new THREE.HemisphereLight(0xd5f6fa,0x314940,2.5));const light=new THREE.DirectionalLight(0xffffff,3);light.position.set(-4,-4,8);scene.add(light);const root=new THREE.Group();scene.add(root);const groups:Record<string,THREE.Group>={};for(const p of parts.slice(1)){groups[p.id]=new THREE.Group();root.add(groups[p.id])}const blue=new THREE.MeshStandardMaterial({color:0x36869a,roughness:.5}),shellMaterial=new THREE.MeshStandardMaterial({color:0x54796a,roughness:.8}),joint=new THREE.MeshStandardMaterial({color:0x9dc3bf,roughness:.65}),tip=new THREE.MeshStandardMaterial({color:0xb36b45,roughness:.65}),black=new THREE.MeshStandardMaterial({color:0x111e21,roughness:.3});
 function ellipsoid(group:THREE.Group,x:number,y:number,z:number,sx:number,sy:number,sz:number,material:THREE.Material){const mesh=new THREE.Mesh(new THREE.SphereGeometry(1,32,20),material);mesh.position.set(x,y,z);mesh.scale.set(sx,sy,sz);group.add(mesh);return mesh}
 function segment(group:THREE.Group,a:number[],b:number[],radius:number,material:THREE.Material){const start=new THREE.Vector3(...a),end=new THREE.Vector3(...b),delta=end.clone().sub(start);const mesh=new THREE.Mesh(new THREE.CylinderGeometry(radius*.65,radius,delta.length(),12),material);mesh.position.copy(start.clone().add(end).multiplyScalar(.5));mesh.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),delta.normalize());group.add(mesh);ellipsoid(group,...b as [number,number,number],radius,radius,radius,joint)}
 ellipsoid(groups.shell,0,0,.15,1.65,1.05,.42,shellMaterial);
 for(const side of [-1,1]){for(let i=0;i<7;i++){const y=-.65+i*.2,x=side*(1.3+.18*Math.sin(i/6*Math.PI));segment(groups.shell,[x,y,.15],[x+side*(i===3?.7:.17),y-.08,.13],i===3?.14:.07,shellMaterial)}for(let i=0;i<3;i++){const y=-.25+i*.45;segment(groups.legs,[side*1.25,y,0],[side*2.05,y+.1,-.1],.12,blue);segment(groups.legs,[side*2.05,y+.1,-.1],[side*2.8,y-.45+i*.27,-.3],.09,blue);segment(groups.legs,[side*2.8,y-.45+i*.27,-.3],[side*3.2,y-.85+i*.4,-.45],.055,tip)}segment(groups.paddles,[side*1.1,.7,0],[side*1.95,1.35,-.1],.14,blue);segment(groups.paddles,[side*1.95,1.35,-.1],[side*2.45,1.55,-.1],.1,blue);const paddle=ellipsoid(groups.paddles,side*2.65,1.55,-.1,.45,.25,.055,blue);paddle.rotation.z=side*.35;segment(groups.eyes,[side*.48,-.78,.22],[side*.65,-1.13,.38],.065,joint);ellipsoid(groups.eyes,side*.65,-1.13,.38,.13,.1,.11,black);segment(groups.claws,[side*.9,-.6,0],[side*1.8,-1.35,-.08],.2,blue);segment(groups.claws,[side*1.8,-1.35,-.08],[side*1.5,-2.05,-.05],.17,blue);ellipsoid(groups.claws,side*1.42,-2.35,-.05,.29,.43,.2,blue);segment(groups.claws,[side*1.6,-2.5,-.05],[side*1.5,-3.12,-.05],.1,tip);const finger=new THREE.Group();finger.name='finger'+side;finger.position.set(side*1.22,-2.55,-.05);groups.claws.add(finger);segment(finger,[0,0,0],[side*.18,-.57,0],.095,tip)}
 ellipsoid(groups.abdomen,0,.08,-.26,.7,.78,.065,joint);for(let i=0;i<5;i++){const line=new THREE.Mesh(new THREE.TorusGeometry(.15+i*.08,.012,6,32,Math.PI),shellMaterial);line.rotation.z=Math.PI;line.position.set(0,.45-i*.18,-.33);groups.abdomen.add(line)}for(let i=0;i<20;i++){const angle=i*.9,r=.3+(i%4)*.23;ellipsoid(groups.shell,Math.cos(angle)*r*1.3,Math.sin(angle)*r*.7,.49,.03,.025,.015,joint)}
 const texels=new Uint8Array(128*128*4);let seed=1974;for(let i=0;i<128*128;i++){seed=(seed*1664525+1013904223)>>>0;const tone=110+(seed%100);texels[i*4]=tone;texels[i*4+1]=tone;texels[i*4+2]=tone;texels[i*4+3]=255}const grain=new THREE.DataTexture(texels,128,128);grain.wrapS=grain.wrapT=THREE.RepeatWrapping;grain.repeat.set(5,5);grain.needsUpdate=true;shellMaterial.bumpMap=grain;shellMaterial.bumpScale=.035;blue.bumpMap=grain;blue.bumpScale=.018;
 for(const side of [-1,1]){for(let g=0;g<7;g++){const blade=ellipsoid(groups.gills,side*(.58+g*.085),-.5+g*.18,.12,.16,.37,.07,joint);blade.rotation.z=side*.55}for(let n=0;n<2;n++){const sx=side*(.15+n*.12);segment(groups.antennae,[sx,-.9,.14],[sx*1.4,-1.3-n*.12,.2],.035,joint);segment(groups.antennae,[sx*1.4,-1.3-n*.12,.2],[sx*2,-1.65-n*.2,.24],.018,blue)}for(let j=0;j<3;j++){const plate=ellipsoid(groups.mouth,side*(.1+j*.09),-.9-j*.12,-.18,.12,.19,.04,joint);plate.rotation.z=side*.3}}
 for(let s=0;s<5;s++)ellipsoid(groups.sternum,0,.65-s*.27,-.17,.82-s*.025,.17,.065,joint);
 api.current={select(id){for(const [key,g]of Object.entries(groups))g.visible=id==='all'||key===id},explode(value){groups.shell.position.z=value?1.4:0;groups.abdomen.position.z=value?-.8:0;groups.eyes.position.y=value?-.5:0;groups.gills.position.z=value?.65:0;groups.mouth.position.y=value?-.7:0;groups.sternum.position.z=value?-.4:0;groups.antennae.position.y=value?-.6:0;groups.claws.position.y=value?-.6:0;groups.legs.scale.x=value?1.18:1;groups.paddles.scale.x=value?1.2:1},grip(value){for(const side of [-1,1]){const finger=groups.claws.getObjectByName('finger'+side);if(finger)finger.rotation.z=side*value*Math.PI/180}},zoom(factor){const offset=camera.position.clone().sub(controls.target).multiplyScalar(factor).clampLength(1.5,22);camera.position.copy(controls.target).add(offset);controls.update()},reset(){camera.position.set(0,-10,10);controls.target.set(0,0,0);controls.update()}};api.current.grip(25);const resize=new ResizeObserver(()=>{const w=el.clientWidth,h=el.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix()});resize.observe(el);let frame=0;const draw=()=>{controls.update();renderer.render(scene,camera);frame=requestAnimationFrame(draw)};draw();return()=>{cancelAnimationFrame(frame);resize.disconnect();controls.dispose();scene.traverse(o=>{if(o instanceof THREE.Mesh)o.geometry.dispose()});for(const m of [blue,shellMaterial,joint,tip,black])m.dispose();grain.dispose();renderer.dispose();renderer.domElement.remove();api.current=null}},[]);
 return <section className="crab-component-model"><h4>Interactive component model</h4><p>Locally rendered anatomical schematic. Inspect ten component groups and separate the body layers. Surface grain and internal structures are illustrative; the separate Smithsonian viewer below is intended for the scanned exterior when its source is available.</p><div className="crab-model-canvas" ref={mount}/>{failure&&<p role="status">{failure}</p>}<div className="crab-pathway-steps" role="group" aria-label="Isolate crab component">{parts.map(p=><button key={p.id} aria-pressed={part===p.id} onClick={()=>{setPart(p.id);api.current?.select(p.id)}}>{p.name}</button>)}</div><p aria-live="polite">{parts.find(p=>p.id===part)?.text}</p><div className="crab-model-controls"><label><input type="checkbox" checked={exploded} onChange={e=>{setExploded(e.target.checked);api.current?.explode(e.target.checked)}}/> Separate shell and abdomen</label><label>Claw opening <input type="range" min="0" max="55" value={grip} onChange={e=>{setGrip(Number(e.target.value));api.current?.grip(Number(e.target.value))}}/></label><button aria-label="Zoom into component model" onClick={()=>api.current?.zoom(.75)}>＋ Zoom</button><button aria-label="Zoom out of component model" onClick={()=>api.current?.zoom(1.33)}>− Zoom</button><button onClick={()=>api.current?.reset()}>Reset view</button></div><p><small>Drag to orbit; scroll or pinch to zoom. Simplified geometry, not manufacturing CAD. <a href="https://lanwebs.lander.edu/faculty/rsfox/invertebrates/callinectes.html" target="_blank" rel="noreferrer">Anatomical reference ↗</a></small></p></section>
}
