import {useState} from 'react';
import {CrabQuestionSubmission} from './crab-future-panels';
const common=[
 {q:'Are soft-shell crabs a different species?',a:'No. A soft-shell blue crab has recently molted. Its new covering is still flexible and hardens afterward; molting lets the crab grow.',href:'https://www.chesapeakebay.net/news/blog/clues-of-a-growing-blue-crab',source:'Chesapeake Bay Program'},
 {q:'Can blue crabs swim, or only walk sideways?',a:'They do both. Three pairs of walking legs move them along the bottom, while the flattened rear legs paddle through the water.',href:'https://www.dnr.sc.gov/marine/pub/seascience/bluecrab.html',source:'South Carolina DNR'},
 {q:'What do blue crabs eat?',a:'They hunt and scavenge, eating foods such as clams, oysters, worms, fish and other crabs. Their diet changes with what is available.',href:'https://www.dnr.sc.gov/marine/pub/seascience/bluecrab.html',source:'South Carolina DNR'},
 {q:'Where do they go in winter?',a:'Cold water reduces their activity. In the Chesapeake Bay, blue crabs shelter in bottom sediment until warmer conditions return.',href:'https://www.chesapeakebay.net/discover/faq/category/blue-crabs',source:'Chesapeake Bay Program'}
];
const unresolved=[
 {q:'What determines how many young crabs survive each year?',a:'Currents, nursery habitat, predators and environmental conditions all matter. Their relative contributions vary, making recruitment—the arrival of young crabs into the population—difficult to predict precisely.',href:'https://www.fisheries.noaa.gov/species/blue-crab',source:'NOAA Fisheries · population research'},
 {q:'What does a blue crab consciously experience?',a:'Research supports sentience in true crabs, but the character of a blue crab’s subjective experience remains unresolved. Species-specific studies are needed to separate sensory responses, learning and felt experience.',href:'https://www.lse.ac.uk/news/latest-news-from-lse/k-november-21/octopuses-crabs-and-lobsters-welfare-protection',source:'LSE · evidence review'},
 {q:'Which extinct species were its direct ancestors?',a:'Early fossils document crab evolution, but they do not provide a complete species-by-species ancestry for the blue crab. Fossil placement and gaps in the record leave parts of that lineage uncertain.',href:'https://palaeo-electronica.org/content/2021/3427-new-bajocian-crab-from-france',source:'Palaeontologia Electronica · fossil evidence'}
];
export function CrabQuestions(){const [query,setQuery]=useState('');const matches=(item:{q:string;a:string})=>(item.q+' '+item.a).toLowerCase().includes(query.toLowerCase());return <section id="crab-questions" className="crab-section crab-level-1 crab-questions"><h3>Common &amp; Unresolved Questions</h3><label className="question-search"><span>SEARCH THE QUESTIONS</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Try molting, swimming, consciousness…" type="search"/></label><p className="question-count" role="status">{[...common,...unresolved].filter(matches).length} matching questions</p>{![...common,...unresolved].some(matches)&&<div className="question-empty"><p>No questions match “{query}”. Try a broader term or return to all seven questions.</p><button onClick={()=>setQuery('')}>Clear search</button></div>}{[{id:'common',title:'Common questions',label:'Quick answers',items:common},{id:'unresolved',title:'Unresolved questions',label:'Open research',items:unresolved}].map(group=><section id={'crab-questions-'+group.id} key={group.id} className={'crab-question-category '+group.id}><header><span>{group.label}</span><h4>{group.title}</h4></header><div className="crab-question-grid">{group.items.filter(matches).map((item,i)=><article className="crab-question-card" key={item.q}><span className="crab-question-number">{String(i+1).padStart(2,'0')}</span><h5>{item.q}</h5><p>{item.a}</p><a href={item.href} target="_blank" rel="noreferrer">{item.source} ↗</a></article>)}</div></section>)}<CrabQuestionSubmission/></section>}
