import {lazy,Suspense,useRef,useState} from 'react';
import {crabCollections} from './crab-collections';
import {CrabBodyInspector} from './crab-body-inspector';
import {CrabHabitatDiagram,CrabSurveyDiagram} from './crab-collection-visuals';
import './crab-collection-view.css';
import {CrabRecordMedia,CrabMediaThumbnail} from './crab-record-media';
const CrabSpecimenViewer=lazy(()=>import('./crab-specimen-viewer').then(m=>({default:m.CrabSpecimenViewer})));
const CrabComponentModel=lazy(()=>import('./crab-component-model').then(m=>({default:m.CrabComponentModel})));

type Point={label:string;detail:string};
const pathways:Record<string,{title:string;note:string;points:Point[]}>= {
 overview:{title:'Read the crab at three scales',note:'An archive navigation diagram, not a taxonomic or evolutionary tree.',points:[{label:'Organism',detail:'Inspect the body, growth and senses in Health and Models.'},{label:'Relationships',detail:'Compare animal behavior in Society with predators and prey in Environment.'},{label:'Human context',detail:'Connect fishing traditions, research instruments, images and cultural objects.'}]},
 infrastructure:{title:'From physical sample to population evidence',note:'Conceptual reconstruction of the published winter-survey method; no fabricated survey measurements.',points:[{label:'Dredge + tow',detail:'A lined dredge samples the bottom along a recorded tow. Gear and tow conditions affect what is caught.'},{label:'Position + area',detail:'Start/end positions establish tow distance. Distance multiplied by gear width gives the area sampled.'},{label:'Crab observations',detail:'Count and measure captured crabs; retain sex, size and environmental observations alongside the catch.'},{label:'Survey estimate',detail:'Scaling and corrections are required before catches support an abundance estimate. Read the published method for uncertainty.'}]},
 transport:{title:'Follow life-stage movement',note:'Generalized life-history sequence. Timing and routes vary; this is not a tracked individual.',points:[{label:'Egg-bearing female',detail:'Compare the adult migration account with the estuary’s salinity gradient.'},{label:'Larvae',detail:'Water movement matters at this scale. Do not interpret larval transport as adult-style swimming.'},{label:'Settling juvenile',detail:'Inspect the transition toward bottom habitat and the nursery environment.'},{label:'Adult',detail:'Compare walking, swimming and reproductive movement using the sources below.'}]},
 business:{title:'Compare evidence about interaction',note:'Study-design guide for the primary behavioral papers in this collection.',points:[{label:'Signal',detail:'What was observed or manipulated: chemical information, visual appearance or water movement?'},{label:'Context',detail:'Was a partner accessible? Was the behavior pair formation, pair maintenance or display?'},{label:'Response',detail:'Separate the observed action from an interpretation of motivation.'},{label:'Limit',detail:'An experimental result does not establish a universal sequence or a human-like social intention.'}]},
 fitness:{title:'Inspect the molt cycle',note:'Qualitative sequence, not a timer or a diagnostic tool.',points:[{label:'Pre-molt',detail:'Preparation precedes shedding. Compare the regional field account with experimental definitions of molt stage.'},{label:'Shedding',detail:'The animal leaves the old exoskeleton. This is growth through replacement, not stretching rigid armor.'},{label:'Soft stage',detail:'Mechanical support differs from the hardened state. Compare the skeleton study with refuge behavior.'},{label:'Hardening',detail:'The new exterior develops rigidity; measurements depend on stage and method.'}]},
 agriculture:{title:'Compare defense mechanisms',note:'Functional comparison, not a live-animal experiment or a combat simulator.',points:[{label:'Claws',detail:'Inspect articulated grasping structures and their physical contact surfaces.'},{label:'Armor',detail:'Compare the carapace with the appendage joints and the changing skeleton across molt stages.'},{label:'Escape',detail:'Use Movement to compare the limbs available for walking and swimming.'},{label:'Refuge',detail:'Read Infrastructure and Survival for protection supplied by the surrounding habitat.'}]},
 nature:{title:'Connect habitat observations',note:'Qualitative relationship map. No thresholds, causal coefficients or forecast values are invented.',points:[{label:'Place',detail:'Keep region, depth and habitat type attached to an observation.'},{label:'Water',detail:'Temperature and salinity measurements describe sampling conditions, not automatically the animal’s tolerance limits.'},{label:'Life stage',detail:'Compare juveniles and adults before pooling habitat observations.'},{label:'Food web',detail:'Predator, prey and refuge relationships connect the animal to the wider estuary.'}]},
 survival:{title:'Read conservation evidence',note:'A source-reading sequence, not a current management recommendation.',points:[{label:'Pressure',detail:'Identify the specific pressure: habitat change, predation, seasonal conditions or harvest.'},{label:'Observation',detail:'Find the survey, field observation or experiment used to investigate it.'},{label:'Uncertainty',detail:'Check date, sampling method and whether an estimate includes uncertainty.'},{label:'Response',detail:'Distinguish conservation interpretation from current law; consult the responsible agency for current rules.'}]},
 film:{title:'Documentary viewing guide',note:'Discussion themes, not fabricated timestamps or a transcript.',points:[{label:'Animal',detail:'Watch how the crab’s life history frames the research questions.'},{label:'Fieldwork',detail:'Identify sampling and tracking equipment; connect them with Infrastructure.'},{label:'People',detail:'Compare the perspectives of researchers and fishing communities.'},{label:'Evidence',detail:'Keep the documentary’s historical population narrative separate from the latest survey results.'}]},
 animation:{title:'Compare crab imagery',note:'Visual-analysis prompts; historical species identifications remain unspecified.',points:[{label:'Silhouette',detail:'Compare carapace width, limb arrangement and the overall shape selected by the artist.'},{label:'Material',detail:'Compare a digital painted mesh with cast bronze and the archive illustration.'},{label:'Function',detail:'Distinguish an anatomical image, an expressive sculpture and an architectural support.'},{label:'Provenance',detail:'Read date, creator, collection and species attribution before drawing biological conclusions.'}]}
};

function Pathway({section}:{section:string}){const [step,setStep]=useState(0);const path=pathways[section];if(!path)return null;return <section className="crab-pathway"><h4>{path.title}</h4><div className="crab-pathway-steps" role="group" aria-label={path.title}>{path.points.map((p,i)=><button key={p.label} aria-pressed={step===i} onClick={()=>setStep(i)}><span>{String(i+1).padStart(2,'0')}</span>{p.label}</button>)}</div><div className="crab-pathway-detail" aria-live="polite"><strong>{path.points[step].label}</strong><p>{path.points[step].detail}</p></div><small>{path.note}</small></section>}



export function CrabCollectionView({section}:{section:string}){
 const [specimenOpen,setSpecimenOpen]=useState(false);const collection=crabCollections[section];const detail=useRef<HTMLElement>(null);const [selected,setSelected]=useState(section==='animation'?1:0),[query,setQuery]=useState(''),[kind,setKind]=useState('All'),[comparison,setComparison]=useState<number|null>(null);
 if(!collection)return null;
 const current=collection.records[selected],types=['All',...new Set(collection.records.map(r=>r.media?.type||'Research'))];
 const visible=collection.records.map((r,i)=>({r,i})).filter(({r})=>(kind==='All'||(r.media?.type||'Research')===kind)&&[r.title,r.kind,r.focus,r.description].join(' ').toLowerCase().includes(query.toLowerCase()));
 function choose(index:number){setSelected(index);setComparison(null);requestAnimationFrame(()=>detail.current?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'}))}
 function download(){const blob=new Blob([JSON.stringify({subject:'Callinectes sapidus',section,records:collection.records},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='blue-crab-'+section+'-catalog.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 return <section className="crab-subject-collection" id={'crab-collection-'+section} aria-label={section+' crab collection'}>
 <header className="crab-collection-heading"><div><span className="crab-collection-eyebrow">BLUE CRAB ARCHIVE · {collection.records.length} ENTRIES</span><h3>{section==='graphics'?'Photos, illustrations & slides':section==='film'?'Watch the collection':section==='sounds'?'Listen & investigate':section==='modeling'?'Specimens & components':section==='animation'?'Crab art & visual history':'The collection'}</h3></div><button className="crab-catalog-export" onClick={download}>Export source catalog</button></header>
 <p className="crab-collection-intro">{collection.intro}</p>
 {section==='modeling'&&<Suspense fallback={<p>Loading component model…</p>}><CrabComponentModel/></Suspense>}
 <div className="crab-collection-toolbar"><label>Find a record <input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search names, topics or materials"/></label><span>{visible.length} of {collection.records.length}</span></div>
 <div className="crab-format-filters" role="group" aria-label="Filter collection format">{types.map(type=><button key={type} aria-pressed={kind===type} onClick={()=>setKind(type)}>{type==='youtube'||type==='vimeo'?'Video · '+type:type==='pdf'?'Documents':type==='image'?'Images':type==='audio'?'Recordings':type==='model'?'3D':type}</button>)}</div>
 <div className="crab-record-list crab-gallery-grid" role="group" aria-label="Collection records">{visible.map(({r,i})=><button key={r.title} aria-pressed={selected===i} onClick={()=>choose(i)}><CrabMediaThumbnail record={r}/><span className="crab-card-body"><small>{r.kind} · {r.focus}</small><strong>{r.title}</strong><span>{r.media?'View here':'Read note'}</span></span></button>)}{!visible.length&&<p>No matching records. <button onClick={()=>{setQuery('');setKind('All')}}>Clear search</button></p>}</div>
 <article ref={detail} className="crab-record-detail crab-selected-object" aria-live="polite"><div className="crab-selected-heading"><div><span className="crab-collection-eyebrow">{current.kind} · {current.focus}</span><h4>{current.title}</h4></div><div className="crab-object-paging"><button aria-label="Previous collection object" onClick={()=>choose((selected+collection.records.length-1)%collection.records.length)}>←</button><span>{selected+1} / {collection.records.length}</span><button aria-label="Next collection object" onClick={()=>choose((selected+1)%collection.records.length)}>→</button></div></div>
 <CrabRecordMedia key={current.title} record={current}/>{current.media&&<p>{current.description}</p>}
 <details className="crab-record-context"><summary>Object details, evidence & attribution</summary><h5>What to inspect</h5><ul>{current.inspect.map(text=><li key={text}>{text}</li>)}</ul><dl><dt>Subject</dt><dd>{current.scope}</dd><dt>Provenance</dt><dd>{current.credit}</dd></dl><a href={current.source} target="_blank" rel="noreferrer">Source citation ↗</a>{current.media?.licenseUrl&&<> · <a href={current.media.licenseUrl} target="_blank" rel="noreferrer">License ↗</a></>}</details>
 <label className="crab-record-compare">Compare with <select value={comparison??''} onChange={e=>setComparison(e.target.value===''?null:Number(e.target.value))}><option value="">Choose another record</option>{collection.records.map((r,i)=><option key={r.title} value={i} disabled={selected===i}>{r.title}</option>)}</select></label>
 {comparison!==null&&comparison!==selected&&<div className="crab-record-comparison"><h5>{collection.records[comparison].title}</h5><CrabRecordMedia key={collection.records[comparison].title} record={collection.records[comparison]}/><p>{collection.records[comparison].description}</p><small>{collection.records[comparison].credit}</small></div>}</article>
 <details className="crab-collection-explore"><summary>Explore relationships & study tools</summary><Pathway section={section}/>{section==='infrastructure'&&<CrabSurveyDiagram/>}{section==='nature'&&<CrabHabitatDiagram/>}{section==='graphics'&&<CrabBodyInspector/>}</details>
 {section==='modeling'&&<details className="crab-collection-explore" onToggle={e=>setSpecimenOpen(e.currentTarget.open)}><summary>Smithsonian scanned specimen · external source currently unavailable</summary><p>The source’s certificate failed validation during testing. The local component model and anatomical image collection remain usable.</p>{specimenOpen&&<Suspense fallback={<p>Loading specimen viewer…</p>}><CrabSpecimenViewer/></Suspense>}</details>}
 </section>
}
