import {useState} from 'react';
import {Users,Building2,BookOpen,ScanLine,Shapes,ExternalLink,MessageCircle} from 'lucide-react';
export function CrabNetworkPreview(){
 const [filter,setFilter]=useState('All');
 const rows=[{type:'Person',alignment:'Aligned',Icon:Users},{type:'Organization',alignment:'Aligned',Icon:Building2},{type:'Person',alignment:'Misaligned',Icon:Users},{type:'Organization',alignment:'Misaligned',Icon:Building2}];
 return <section id="crab-profiles" className="crab-section crab-level-1 future-module"><div className="poc-module-heading"><span>FROM NETWORKS / PREVIEW</span><h3>Network Connections</h3><p>Entities whose documented activities align—or conflict—with blue-crab conservation interests. Full profiles will live in Networks.</p></div><div className="poc-segmented" role="group" aria-label="Conservation alignment filter">{['All','Aligned','Misaligned'].map(f=><button key={f} aria-pressed={filter===f} onClick={()=>setFilter(f)}>{f}</button>)}</div><div className="network-mock-grid">{rows.filter(r=>filter==='All'||r.alignment===filter).map((r,i)=><article key={r.type+r.alignment} className={'network-mock-card '+(r.alignment==='Misaligned'?'conflict':'')}><span className="network-placeholder"><r.Icon size={28}/></span><span className="poc-eyebrow">{r.alignment} · example slot</span><strong>{r.type} profile</strong><span className="skeleton-line"/><span className="skeleton-line short"/><p className="connection-summary">Conservation relationship and supporting evidence will appear here.</p><button disabled className="future-destination"><ExternalLink size={14}/> View in Networks</button><small>No profile linked yet</small></article>)}</div><p className="poc-disclaimer">Blank design placeholders, not assessments of real entities. Alignment concerns documented conservation activities—not an entity’s overall character. Profiles and evidence will be maintained in Networks.</p></section>
}
const workTypes=[{type:'Learning',Icon:BookOpen,title:'Learning project'},{type:'Gathering',Icon:ScanLine,title:'Fieldwork & observations'},{type:'Creating',Icon:Shapes,title:'Creative & technical work'}];
export function CrabTestingPreview(){
 const [filter,setFilter]=useState('All work');
 return <section id="crab-testing" className="crab-section crab-level-1 future-module"><div className="poc-module-heading"><span>FROM WORKSHOPS / PREVIEW</span><h3>Workshop Showcase</h3><p>User-created work related to the blue crab: learning projects, gathered evidence, models and strategy investigations. Creation, training and testing will take place in Workshops.</p></div><div className="poc-segmented" role="group" aria-label="Workshop work filter">{['All work','Learning','Gathering','Creating'].map(f=><button key={f} aria-pressed={filter===f} onClick={()=>setFilter(f)}>{f}</button>)}</div><div className="work-showcase-grid">{workTypes.filter(w=>filter==='All work'||w.type===filter).map(w=><article key={w.type} className="work-showcase-card"><div className="work-preview-art"><w.Icon size={38}/><span>Project preview</span></div><div className="work-showcase-body"><span className="poc-eyebrow">{w.type} / PLACEHOLDER</span><h4>{w.title}</h4><p>A project’s creator, summary, outputs and evidence will appear here once linked from Workshops.</p><dl><dt>Creator</dt><dd>Not linked</dd><dt>Project status</dt><dd>—</dd></dl><button disabled className="future-destination"><ExternalLink size={14}/> View in Workshops</button></div></article>)}</div><p className="poc-disclaimer">Showcase mockup only. No real projects or results have been submitted. This area will display linked work, not run simulations or training.</p></section>
}
export function CrabQuestionSubmission(){
 function saveDraft(){const url=URL.createObjectURL(new Blob(['Blue crab question draft\\nCategory: '+category+'\\n\\n'+question.trim()+'\\n\\nLocal draft — not submitted or published.'],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='blue-crab-question-draft.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 const [question,setQuestion]=useState(''),[category,setCategory]=useState('General question'),[preview,setPreview]=useState(false);
 return <section className="question-submission" aria-labelledby="ask-crab-title"><header><MessageCircle size={24}/><div><span className="poc-eyebrow">COMMUNITY QUESTIONS / PREVIEW</span><h4 id="ask-crab-title">Ask your own question</h4><p>What would you like to know about crabs or blue crabs?</p></div></header><form onSubmit={e=>{e.preventDefault();if(question.trim().length>=10)setPreview(true)}}><label>Question category<select value={category} onChange={e=>{setCategory(e.target.value);setPreview(false)}}><option>General question</option><option>Research & unresolved questions</option></select></label><label>Your question<textarea required minLength={10} maxLength={1000} value={question} onChange={e=>{setQuestion(e.target.value);setPreview(false)}} placeholder="For example: How do blue crabs find their way back to suitable nursery habitat?" aria-describedby="question-preview-note"/></label><div className="question-submit-footer"><span>{question.length} / 1000 characters</span><button type="submit" disabled={question.trim().length<10}>Preview question</button></div><p id="question-preview-note" className="poc-disclaimer">Submission service is not connected. Your question is not sent or stored by the site; reloading clears this form. After previewing, you can download a draft to keep.</p></form>{preview&&<div className="question-submission-preview" role="status"><span className="poc-eyebrow">{category}</span><h5>Your question preview</h5><p>{question.trim()}</p><button type="button" className="question-download" onClick={saveDraft}>Download question draft</button><strong>Not submitted</strong><p>Public submissions will become available when the community question service is developed.</p></div>}</section>
}
