import {useState} from 'react';
import entries from './crab-belief-index.json';
export {CrabCultureSelections} from './crab-culture-explorer';
const types=Array.from(new Set(entries.map(e=>e.type)));
const connections:Record<string,{text:string;url:string}>={
 'Greek':{text:'Karkinos connects the crab with Hera and the constellation Cancer.',url:'https://www.theoi.com/Ther/Karkinos.html'},
 'Roman':{text:'The Karkinos/Cancer tradition is transmitted in Roman mythography as well as Greek sources.',url:'https://www.theoi.com/Ther/Karkinos.html'},
 'Christian mythology':{text:'Devotional crab-and-cross imagery recalls the Francis Xavier miracle story; it does not establish crab worship.',url:'https://www.jesuittampa.org/spiritual-life/the-chapel-of-the-holy-cross/full-story-chapel-of-the-holy-cross'},
 'Buddhism':{text:'The crab is a discerning character in a Jātaka teaching story about deceit.',url:'https://www.buddhanet.net/e-learning/buddhism/tale008/'},
 'Buddhist mythology':{text:'The Crane and the Crab supplies a documented animal teaching narrative.',url:'https://www.buddhanet.net/e-learning/buddhism/tale008/'},
 'Moche':{text:'Supernatural crab figures occur in Moche religious imagery and material culture.',url:'https://www.metmuseum.org/art/collection/search/313419'},
 'Japanese mythology':{text:'The Monkey and the Crab is a documented folktale. Its presence alone does not establish a Shinto ritual.',url:'https://www.gutenberg.org/cache/epub/25021/pg25021-images.html'},
 'Malay':{text:'A giant crab at Pusat Tasek appears in the supplied Malay tidal tradition; the full account is retained in Further Reading.',url:'#crab-in-culture'}
};
export function CrabBeliefIndex(){const [query,setQuery]=useState(''),[type,setType]=useState('All'),[documented,setDocumented]=useState(false),[sort,setSort]=useState('Supplied order');const filtered=entries.filter(e=>(type==='All'||e.type===type)&&(!documented||connections[e.label])&&`${e.label} ${e.sourceGroup}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='A–Z'?a.label.localeCompare(b.label):0);return <section className="crab-belief-directory"><h4>Belief &amp; tradition index</h4><p>All {entries.length} supplied entries are retained, including repeated labels. Groups distinguish kinds of material; ambiguous labels remain unclassified. Original list headings are provenance labels, not verified geographic assignments.</p><div className="crab-index-controls"><label>Find a tradition or text<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search the complete list…"/></label><label>Group<select value={type} onChange={e=>setType(e.target.value)}><option>All</option>{types.map(t=><option key={t}>{t}</option>)}</select></label><label>Sort<select value={sort} onChange={e=>setSort(e.target.value)}><option>Supplied order</option><option>A–Z</option></select></label><label className="crab-index-toggle"><input type="checkbox" checked={documented} onChange={e=>setDocumented(e.target.checked)}/> Sourced connections only</label></div><p role="status">{filtered.length} matching entries</p>{!filtered.length&&<div className="culture-empty"><p>No entries match all filters.</p><button onClick={()=>{setQuery('');setType('All');setDocumented(false)}}>Reset index filters</button></div>}{types.map(t=>{const list=filtered.filter(e=>e.type===t);return list.length?<details key={t} open={query.length>0||documented||type!=='All'}><summary>{t} <span>{list.length}</span></summary><ul className="crab-index-list">{list.map((e,i)=><li key={`${e.label}-${i}`}><strong>{e.label}</strong><small>Original list heading: {e.sourceGroup}</small>{connections[e.label]?<><span className="crab-evidence-badge">Sourced connection</span><p>{connections[e.label].text}</p><a href={connections[e.label].url}>Read source →</a></>:<span className="crab-pending-label">Crab connection not yet researched</span>}</li>)}</ul></details>:null})}<p className="subnote">“Not yet researched” does not mean crabs are absent from a tradition. Folklore, philosophical schools and fictional mythologies are not treated as interchangeable religions.</p></section>}
