import {useEffect,useState} from 'react';
import type {ReactNode} from 'react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import './crab-overview-structure.css';
import {CrabBeliefIndex} from './crab-belief-index';
const beliefRoles:Record<string,{overview:string;roles:string[];source:string}>={
 Christianity:{overview:'Crabs have a limited, localized role in Christian spirituality: they occur in devotional stories and religious imagery, rather than as a central sacred animal. Their significance depends on the story or image, not on a single Christian meaning assigned to every crab.',roles:['Worship: not an object of Christian worship; Catholic teaching explicitly rejects worship of creatures in place of God.','Symbolism: a crab may act as a visual reminder of providential help in a saint’s story. It is not a universal Christian emblem.','Stories and figures: the best-documented example here is the crab associated with Francis Xavier; the crab serves the sacred story rather than becoming a deity.','Rituals and traditions: crab imagery is preserved in churches and devotional art. The sources reviewed do not establish a widespread crab-specific Christian rite.'],source:'https://www.vatican.va/content/catechism/en/part_three/section_two/chapter_one/article_1/iii_you_shall_have_no_other_gods_before_me.html'},
 'Moche traditions':{overview:'For the Moche, crab forms belonged to a wider sacred visual world combining humans, animals and supernatural beings. Their importance is visible in ceremonial and funerary material culture, not just in realistic pictures of sea life.',roles:['Worship: a crab-bodied supernatural figure is documented; this does not establish worship of all living crabs.','Symbolism: human–crab combinations and fangs identify beings beyond ordinary animal life. Crab figures also participate in supernatural confrontations.','Stories and figures: the Seattle Art Museum identifies a vessel as a fanged deity with a crab body; related Moche imagery shows anthropomorphized crabs in combat.','Rituals and traditions: vessels depicting supernatural beings formed part of a culture that honored its dead through such objects. The precise rite attached to each crab object is not always recoverable.'],source:'https://art.seattleartmuseum.org/objects/23561/'},
 Buddhism:{overview:'Crabs matter principally as characters in Buddhist teaching stories. Their choices make moral lessons memorable: intelligence, discernment and the consequences of deception are communicated through an animal encounter.',roles:['Worship: the Jātaka material cited here presents crabs as story characters, not deities receiving worship.','Symbolism: the crab’s alertness and defensive claws give practical form to discernment and resistance to deceit.','Stories and figures: The Crane and the Crab is a Jātaka teaching narrative in which the crab sees through a predator’s false promise.','Rituals and traditions: retelling and teaching these narratives preserves their religious role. These sources do not establish a general crab-specific Buddhist ritual.'],source:'https://www.buddhanet.net/e-learning/buddhism/tale008/'},
 'Greek astral tradition':{overview:'The crab links divine narrative with the night sky. Its main documented spiritual importance is as a figure placed among the stars by a goddess, giving a celestial sign a story of service and reward.',roles:['Worship: the Karkinos account describes divine intervention, not a crab cult or a rite of worship directed at ordinary crabs.','Symbolism: Cancer makes the crab a lasting heavenly figure associated with Hera’s reward.','Stories and figures: Karkinos aids the Hydra against Heracles, is killed, and receives a place among the stars.','Rituals and traditions: the constellation story was transmitted through classical mythography. The cited account does not document a dedicated crab ritual.'],source:'https://www.theoi.com/Ther/Karkinos.html'}
};
export type BeliefEntry={id:string;title:string;targets:string[];content:ReactNode};
export function CrabBeliefTabs({entries}:{entries:BeliefEntry[]}){
 const getTarget=()=>{try{return decodeURIComponent(window.location.hash.slice(1))}catch{return ''}};
 const find=(target:string)=>entries.find(e=>e.id===target||e.targets.includes(target))?.id;
 const [active,setActive]=useState(()=>find(getTarget())||entries[0].id);
 useEffect(()=>{const onHash=()=>{const id=find(getTarget());if(id)setActive(id)};const custom=(e:Event)=>{const id=find((e as CustomEvent<string>).detail);if(id)setActive(id)};window.addEventListener('hashchange',onHash);window.addEventListener('crab-belief-navigate',custom);return()=>{window.removeEventListener('hashchange',onHash);window.removeEventListener('crab-belief-navigate',custom)}},[entries]);
 return <Tabs value={active} onValueChange={setActive} activationMode="manual" className="crab-belief-tabs"><TabsList aria-label="Significance across Beliefs" className="crab-belief-tablist">{entries.map(e=><TabsTrigger key={e.id} value={e.id}>{e.title}</TabsTrigger>)}<TabsTrigger value="complete-index">All beliefs · 460</TabsTrigger></TabsList><CrabBeliefComparison/>{entries.map(e=>{const role=beliefRoles[e.title];return <TabsContent key={e.id} value={e.id} forceMount className="crab-belief-panel"><h4>{e.title}</h4><p className="crab-belief-summary">{role.overview}</p><ul className="crab-belief-roles">{role.roles.map(line=>{const colon=line.indexOf(':');return <li key={line}><strong>{line.slice(0,colon)}</strong><span>{line.slice(colon+1)}</span></li>})}</ul><a href={role.source} target="_blank" rel="noreferrer">Source for this overview ↗</a><details className="crab-belief-examples"><summary>Documented examples and source notes</summary>{e.content}</details></TabsContent>})}<TabsContent value="complete-index" forceMount className="crab-belief-panel"><CrabBeliefIndex/></TabsContent></Tabs>
}
const phases=[
 ['Origins','Triassic · inferred divergence','The true-crab lineage branches','A fossil-calibrated molecular analysis places the likely origin of Brachyura in the Triassic. This is a model-based estimate of lineage divergence, older than the familiar body fossils—not a named blue-crab ancestor.','https://pmc.ncbi.nlm.nih.gov/articles/PMC11282366/'],
 ['Origins','Early Jurassic · fossil evidence','Early crab-like forms','Eocarcinus praecursor from Yorkshire and Eoprosopon klugi from Bavaria preserve early forms relevant to crab ancestry. Their placement has been debated, so neither can be drawn as a confirmed direct ancestor of Callinectes sapidus.','https://palaeo-electronica.org/content/2021/3427-new-bajocian-crab-from-france'],
 ['Origins','Middle–Late Jurassic','Diversification in marine habitats','Fossil crabs diversify in reef-associated environments. These fossils document experimentation within the crab body plan and establish that early crab history was already branching into multiple lineages.','https://palaeo-electronica.org/content/2020/3084-mesozoic-reef-crabs'],
 ['Evolution','About 150 million years ago','A recognizable larval stage','A fossil megalopa preserves a surprisingly modern-looking stage between planktonic larval life and the juvenile crab. The basic developmental transition predates many later expansions of crab diversity.','https://www.nature.com/articles/ncomms7417'],
 ['Evolution','Cretaceous','Major lineages diversify','Phylogenomic work places substantial family-level diversification in the Cretaceous. The fossil record of Portunoidea—the broader swimming-crab group—also reaches this period, although its individual families have different ages.','https://academic.oup.com/jcb/article/28/1/82/2548308'],
 ['Evolution','Around the end of the Cretaceous','Established higher-crab lineages','A fossil-informed reconstruction places several higher-crab groups, including portunids, before the end-Cretaceous boundary. This is a broad family-history milestone, not evidence that the living blue-crab species already existed.','https://collections.naturalsciences.be/ssh-invertebrates/digital-library/crustacea/malacostraca/decapoda/biblio/broesing_reconstruction_2008'],
 ['Evolution','Eocene–Miocene','Continuing expansion of diversity','The same reconstruction reports increasing brachyuran species diversity through the Eocene to Miocene. Modern families accumulated varied forms and ecological strategies; blue-crab ancestry is one branch within this larger radiation.','https://collections.naturalsciences.be/ssh-invertebrates/digital-library/crustacea/malacostraca/decapoda/biblio/broesing_reconstruction_2008'],
 ['Current developments','1896 · taxonomic milestone','The modern species is named','Mary J. Rathbun’s authorship and the date 1896 accompany the accepted name Callinectes sapidus. This records scientific description, not the date the animal evolved. A precise fossil-to-living-species pedigree remains incomplete.','https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=6763'],
 ['Current developments','2021 · genomic milestone','A chromosome-level genome','A published genome assembly supplies a molecular reference for investigating blue-crab genes, chromosome organization and relationships. It advances our ability to study the lineage rather than marking a new anatomical stage.','https://pubmed.ncbi.nlm.nih.gov/34544121/'],
 ['Current developments','Present day','The living blue-crab strategy','A broad carapace, grasping claws, rear swimming paddles and an estuary-to-coast life cycle characterize the living species. Growth proceeds through molts; populations continue responding to environmental conditions. The present form is not an endpoint of evolution.','https://www.dnr.sc.gov/marine/pub/seascience/bluecrab.html']
];
export function CrabHorizontalTimeline(){const [active,setActive]=useState(0);const [group,date,title,body,url]=phases[active];return <div className="crab-horizontal-history"><p>Select a plotted milestone to explore its evidence. This is an ordered sequence, not a proportional time axis or a proven ancestor-to-descendant pedigree.</p><div className="crab-interactive-plot"><svg viewBox="0 0 1000 210" role="group" aria-label="Interactive crab evolutionary timeline"><rect x="20" y="20" width="290" height="170" rx="8" fill="#244137"/><rect x="320" y="20" width="380" height="170" rx="8" fill="#263c3e"/><rect x="710" y="20" width="270" height="170" rx="8" fill="#3c392a"/><text x="40" y="50" fill="#c5e5d3" fontSize="15">ORIGINS</text><text x="340" y="50" fill="#c5e5d3" fontSize="15">EVOLUTION</text><text x="730" y="50" fill="#e5d7b7" fontSize="15">CURRENT DEVELOPMENTS</text><path d="M60 110H945l-12 -7m12 7l-12 7" stroke="#8ed6c9" strokeWidth="3" fill="none"/>{phases.map((p,i)=><g key={p[2]} role="button" tabIndex={0} aria-pressed={active===i} aria-label={p[1]+': '+p[2]} onClick={()=>setActive(i)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();setActive(i)}}}><circle cx={65+i*96} cy="110" r={active===i?22:17} fill={active===i?'#8ed6c9':'#19372a'} stroke="#8ed6c9" strokeWidth="2"/><text x={65+i*96} y="115" textAnchor="middle" fill={active===i?'#10251d':'#d3e9dd'} fontSize="13" className="crab-phase-number">{i+1}</text><text x={65+i*96} y="156" textAnchor="middle" fill="#d3e9dd" fontSize="11">{['Triassic','Early Jurassic','Jurassic','150 Ma','Cretaceous','End Cretaceous','Eocene–Miocene','1896','2021','Present'][i]}</text></g>)}</svg></div><div className="crab-plot-controls"><label htmlFor="crab-timeline-step">Milestone {active+1} of {phases.length}</label><input id="crab-timeline-step" type="range" min="0" max={phases.length-1} value={active} onChange={e=>setActive(Number(e.target.value))} aria-valuetext={date+': '+title}/></div><article className="crab-phase-detail" aria-live="polite"><span>{group} · {date}</span><h4>{title}</h4><p>{body}</p><a href={url} target="_blank" rel="noreferrer">Evidence &amp; further detail ↗</a></article></div>}
export const cultureIntros:Record<string,string>={History:'Crabs appear in material culture, dress, food traditions and coastal livelihoods. The examples below show how people made the animal recognizable in objects and community life, beyond strictly religious meanings.',Mythology:'Mythic crabs take an active role in explaining the world: they intervene in heroic struggles or account for the movement of the sea. These traditions give familiar animal features a role in much larger events.',Fiction:'Literary and screen crabs become plot-driving characters, narrators and companions. Their claws, shells and sideways movement give creators recognizable traits to transform into humor, conflict or imaginative explanations.'};
function CrabBeliefComparison(){return <details className="belief-comparison"><summary>Compare the documented roles across these four traditions</summary><div className="belief-matrix-scroll"><table className="belief-matrix"><thead><tr><th scope="col">Role</th>{Object.keys(beliefRoles).map(name=><th scope="col" key={name}>{name}</th>)}</tr></thead><tbody>{['Worship','Symbolism','Stories and figures','Rituals and traditions'].map((label,i)=><tr key={label}><th scope="row">{label}</th>{Object.entries(beliefRoles).map(([name,r])=><td key={name}>{r.roles[i].slice(r.roles[i].indexOf(':')+1)}</td>)}</tr>)}<tr><th scope="row">Source</th>{Object.entries(beliefRoles).map(([name,r])=><td key={name}><a href={r.source} target="_blank" rel="noreferrer">View source ↗</a></td>)}</tr></tbody></table></div><p className="poc-disclaimer">A comparison of the documented accounts on this page, not a ranking or an exhaustive account of each belief. Detailed examples and references remain in the individual cards.</p></details>}
