import {expandCrabCollections} from './crab-collection-expansion';
export type CrabMedia = {type:'image'|'youtube'|'vimeo'|'audio'|'pdf'|'model';url:string;thumbnail?:string;license?:string;licenseUrl?:string};
export type CrabRecord = {title:string; kind:string; focus:string; description:string; inspect:string[]; source:string; credit:string; scope?:string;media?:CrabMedia};
export type CrabCollection = {intro:string; records:CrabRecord[]};
const dnr='https://www.dnr.sc.gov/marine/pub/seascience/bluecrab.html';
const survey='https://dnr.maryland.gov/fisheries/pages/blue-crab/dredge.aspx';
const anatomy='https://lanwebs.lander.edu/faculty/rsfox/invertebrates/callinectes.html';
const shell='https://journals.biologists.com/jeb/article/210/24/4272/17258/Mechanical-properties-of-the-rigid-and-hydrostatic';
const film='https://ecosystemsontheedge.org/top-predator/';
const sound='https://upcommons.upc.edu/server/api/core/bitstreams/5cf8ba25-eb5b-4ffd-8263-4d2d52512b3c/content';
const record=(title:string,kind:string,focus:string,description:string,inspect:string[],source:string,credit:string,scope='Callinectes sapidus'):CrabRecord=>({title,kind,focus,description,inspect,source,credit,scope});
const baseCollections:Record<string,CrabCollection>={
 overview:{intro:'Start with the organism, the physical specimen and the evidence behind this archive. Select a record to inspect its distinguishing features and provenance.',records:[
 record('Blue crab identification','Field guide','Identity','A species-level reference for distinguishing the blue crab from other swimming crabs.',['Compare lateral carapace spines.','Locate the paddle-shaped rear legs.','Compare adult and immature abdominal shapes.'],dnr,'South Carolina Department of Natural Resources'),
 record('Female specimen in three dimensions','Specimen','Form','A digitized female blue crab held in the Smithsonian 3D collection.',['Inspect dorsal and ventral surfaces.','Distinguish a recorded specimen from an artist’s reconstruction.','Follow the Models section for the separate sculpt viewer.'],'https://3d.si.edu/object/3d/blue-crab%3Ab0bf6d44-af22-40dc-bd85-7d66255be4a7','Smithsonian Environmental Research Center · record dpo_3d_200038 · public-domain media'),
 record('An estuary-wide life history','Research film','Life cycle','Research context for migration, habitat and fisheries. The film is a historical account, not a current population assessment.',['Follow the connection between migration and reproduction.','Separate observations from management decisions.','Compare the film with the dated survey record.'],film,'Smithsonian · Ecosystems on the Edge')
 ]},
 infrastructure:{intro:'Structures and refuge used by the crab, followed by the physical instruments people use to study it. Human equipment is not presented as something the crab builds.',records:[
 record('Sediment refuge','Habitat structure','Crab-used structure','Sediment provides concealment; this is not evidence of an engineered permanent dwelling.',['Inspect the relationship between body profile and concealment.','Compare exposed ground with protective cover.','Read the original refuge account below.'],dnr,'South Carolina DNR'),
 record('Winter survey dredge','Research equipment','Sampling','The survey uses a lined dredge, timed tow and GPS positions to relate catches to sampled area.',['Trace tow distance × dredge width → sampled area.','Compare catch counts with density estimates.','Inspect the published survey method rather than treating raw catches as population totals.'],survey,'Maryland DNR · Chesapeake Bay Winter Dredge Survey'),
 record('Tags, trawls and tracking','Research equipment','Observation','Field research combines tagged animals and sampling equipment to investigate movement.',['Compare an animal tag with a sampling net.','Ask which method identifies an individual.','Track the distinction between recapture location and a continuous route.'],film,'Smithsonian Environmental Research Center')
 ]},
 transport:{intro:'Locomotion at body scale and migration at estuary scale. Compare appendages and follow the life-stage sequence without treating an illustrative route as an observed track.',records:[
 record('Walking legs and swimming paddles','Anatomy','Locomotion','Different appendages support movement along the bottom and through water.',['Select the three walking-leg pairs.','Compare them with the flattened rear pair.','Inspect limb articulation in Models.'],anatomy,'Richard Fox · Lander University'),
 record('Spawning migration','Life history','Migration','Movement links mating habitat with egg-release habitat.',['Distinguish adult movement from larval transport.','Compare the seasonal calendar below.','Check geographic context before applying a timing claim.'],dnr,'South Carolina DNR · regional life-history account'),
 record('Paddling without travelling','Behavioral study','Display','Courtship research investigates paddling that generates directed water flow rather than ordinary swimming.',['Compare stationary display and locomotion.','Inspect the experiment’s flow-visualization method.','Read the behavioral context in Society.'],'https://pubmed.ncbi.nlm.nih.gov/18375848/','2008 · To paddle or not: context dependent courtship display')
 ]},
 graphics:{intro:'Illustrations, observation graphics, field photographs and presentation material about the crab. Each visual keeps its source and distinguishes illustration from specimen photography.',records:[
 record('External anatomy illustration','Illustration','Anatomy','The archive’s existing illustrated blue crab supports labeled, magnified inspection. It is not a calibrated photograph.',['Inspect claws, carapace, eyes and paddles.','Compare structures in the anatomy viewer.','Do not infer measurements from this illustration.'],anatomy,'Labyrinth illustration · anatomical reference: Lander University'),
 record('Blue crab field photography','Photograph collection','Identification','The agency field guide supplies crab photographs alongside identification and life-cycle material.',['Compare dorsal coloration and abdominal views.','Keep the source caption with the image.','Distinguish sex and maturity from image color alone.'],dnr,'South Carolina DNR · source-hosted images'),
 record('Stock assessment model assumptions','Presentation','Population graphics','A published slide presentation on blue-crab stock-assessment assumptions. Distributed as a PDF of slides, not an editable PowerPoint file.',['Inspect chart axes and model assumptions.','Keep the July 2022 date visible when quoting results.','Compare modeled estimates with survey observations.'],'https://www.chesapeakebay.net/files/documents/h_blue_crab_assessment_7-20-2022.pptx.pdf','Mike Wilberg · UMCES · 20 July 2022'),
 record('Winter survey maps and figures','Data graphics','Survey coverage','Published maps and time-series figures accompany the winter survey.',['Inspect survey-site coverage.','Read units and year labels.','Use the original report for uncertainty and methods.'],survey,'Maryland DNR · source-hosted survey graphics')
 ]},
 business:{intro:'Crab social behavior and the crab’s significance to human communities: courtship, communication, fishing traditions and the regional seafood economy.',records:[
 record('Chemical and visual courtship signals','Behavioral study','Animal interaction','Experiments examine how sensory information affects pair formation and maintenance.',['Identify which signal was manipulated.','Separate pair formation from pair maintenance.','Compare the experimental setting with field behavior.'],'https://pubmed.ncbi.nlm.nih.gov/28296500/','Bushmann · 1999 · Concurrent Signals and Behavioral Plasticity'),
 record('Context-dependent courtship display','Behavioral study','Animal interaction','Male paddling was studied in relation to courtship context and the water flow it creates.',['Inspect the display rather than assuming every paddle stroke is swimming.','Compare access to a potential mate.','Read the particle-imaging method and limitations.'],'https://pubmed.ncbi.nlm.nih.gov/18375848/','2008 · To paddle or not'),
 record('Watermen and seafood communities','Cultural record','Human significance','The Smithsonian’s Water Ways program documents the relationship between fishing, markets and community life.',['Read the account as a 2004 cultural record.','Compare occupation, place and tradition.','Do not reuse historical prices as current prices.'],'https://festival.si.edu/2004/water-ways/fish-markets/smithsonian','Smithsonian Folklife Festival · 2004')
 ]},
 fitness:{intro:'Body systems, growth and health: examine anatomy, the molt cycle and the research used to understand the changing skeleton.',records:[
 record('Internal anatomy reference','Anatomical account','Body systems','A blue-crab dissection reference covering external structures and internal organization.',['Locate gill chambers beneath the carapace.','Compare feeding, circulation and sensory systems.','Keep external illustration separate from internal dissection evidence.'],anatomy,'Richard Fox · Lander University'),
 record('Rigid and hydrostatic skeletons','Experimental study','Molting','Mechanical research compares support during the transition between soft and hardened stages.',['Compare material stiffness with whole-body support.','Read how molt stage was defined.','Avoid treating one specimen measurement as a species-wide constant.'],shell,'Journal of Experimental Biology · 2007'),
 record('Growth and molt stages','Life history','Development','A regional account of shell shedding, expansion and hardening.',['Follow pre-molt → ecdysis → post-molt.','Compare growth with temporary vulnerability.','Distinguish shell hardening from repair of an old shell.'],dnr,'South Carolina DNR')
 ]},
 agriculture:{intro:'The crab’s encounters, defenses and physical vulnerabilities—not human combat equipment. Inspect how claws, protective armor and escape relate to one another.',records:[
 record('Claws in an encounter','Anatomy','Active defense','Claw-bearing appendages provide a physical means of handling food and responding to threats.',['Compare grasping surfaces and limb joints.','Inspect claws in the anatomy viewer.','Do not handle live crabs to reproduce an encounter.'],anatomy,'Richard Fox · Lander University'),
 record('The powerful pinch','Field photograph','Defensive structure','A Chesapeake Bay Program photographic account focused on the blue crab’s claw.',['Compare the photograph with the archive illustration.','Examine the contact surfaces.','Separate an image from a measured force experiment.'],'https://www.chesapeakebay.net/news/blog/photo-of-the-week-the-powerful-pinch-of-a-blue-crab','Chesapeake Bay Program'),
 record('Protection changes after molting','Experimental study','Vulnerability','The mechanical state of the skeleton changes across the molt cycle.',['Compare rigid armor with soft-stage support.','Connect condition to the refuge account.','Read the original mechanical tests.'],shell,'Journal of Experimental Biology · 2007')
 ]},
 modeling:{intro:'Inspect the crab as a three-dimensional object, then compare individual anatomical structures. A specimen scan, an artist’s sculpt and an annotated illustration are explicitly separate records.',records:[
 record('Smithsonian female blue crab','3D specimen','Specimen scan','A digitized female specimen with museum provenance. The source service can be unavailable; the independently hosted sculpt below is a different object.',['Rotate to the underside in the source viewer.','Inspect the abdominal apron and appendages.','Retain Smithsonian provenance when reusing public-domain media.'],'https://3d.si.edu/object/3d/blue-crab%3Ab0bf6d44-af22-40dc-bd85-7d66255be4a7','Smithsonian · dpo_3d_200038 · public domain'),
 record('Female blue-crab sculpt','3D artwork','Artist reconstruction','C.J. Goldman’s detailed, polypainted crab sculpt. An artist-created mesh, not a measured anatomical scan.',['Orbit and zoom the embedded mesh.','Inspect the underside, claws and rear paddles.','Compare shape against the specimen and anatomy reference.'],'https://sketchfab.com/3d-models/blue-crab-6cf206cdd27c4b42a0fc439ffb2e7505','C.J. Goldman · Sketchfab · CC Attribution'),
 record('Component anatomy atlas','Annotated illustration','Component comparison','Selectable carapace, eyes, claws, walking legs and paddles with sourced descriptions.',['Magnify a selected component.','Compare two structures side by side.','Use the real 3D object above for surface inspection; this atlas remains two-dimensional.'],anatomy,'Labyrinth anatomy interface · Lander University reference')
 ]},
 animation:{intro:'Crab imagery, sculptural interpretations and design references. Historical depictions of unspecified crab species are comparative art—not evidence about blue-crab anatomy.',records:[
 record('Blue-crab digital sculpture','Digital sculpture','Blue crab','An artist’s interpretation suitable for close inspection of silhouette, surface and color.',['Compare artistic choices with specimen geometry.','Inspect polypainted surface treatment.','Keep creator attribution with the object.'],'https://sketchfab.com/3d-models/blue-crab-6cf206cdd27c4b42a0fc439ffb2e7505','C.J. Goldman · CC Attribution'),
 record('Hellenistic bronze crab','Museum object','Comparative art','A bronze crab in the Metropolitan Museum collection, dated to the third–first century BCE.',['Compare material and silhouette.','Inspect the museum’s object photographs.','Do not identify this historical object as Callinectes sapidus.'],'https://www.metmuseum.org/art/collection/search/256125','The Metropolitan Museum of Art · 1992.11.69','Crab depiction · species unspecified'),
 record('Crab support from Cleopatra’s Needle','Museum object','Comparative art','A Roman bronze crab support associated with the obelisk, dated 13 BCE.',['Compare an architectural support with a free-standing sculpture.','Read the object’s provenance.','Examine how the crab form was adapted to a load-bearing object.'],'https://www.metmuseum.org/art/collection/search/551894','The Metropolitan Museum of Art · 81.2.2','Crab depiction · species unspecified')
 ]},
 nature:{intro:'The estuary as the crab’s environment: habitat, geographic context and the measurements that make environmental comparisons meaningful.',records:[
 record('Estuary habitat profile','Field guide','Habitat','A species-focused account of habitat and ecology in the Chesapeake region.',['Compare nursery habitat and adult habitat.','Follow connections to movement and feeding.','Keep the regional scope visible.'],'https://www.chesapeakebay.net/discover/field-guide/entry/blue-crab','Chesapeake Bay Program'),
 record('Depth, temperature and salinity','Survey observations','Environmental data','Environmental measurements accompany winter crab sampling.',['Compare like seasons before interpreting a difference.','Keep units beside measurements.','Distinguish sampling conditions from experimental tolerances.'],survey,'Maryland DNR · Winter Dredge Survey'),
 record('Food-web relationships','Ecological account','Ecology','The crab connects prey, predators and people within estuarine food webs.',['Compare feeding with predation risk.','Inspect the life stage attached to each relationship.','Do not interpret the diagram as a measured energy budget.'],'https://www.chesapeakebay.net/discover/field-guide/entry/blue-crab','Chesapeake Bay Program')
 ]},
 survival:{intro:'How the crab persists through seasonal change, predation and human pressures, and how those pressures are studied.',records:[
 record('Seasonal refuge and migration','Research account','Seasonal survival','Research follows crab movement and winter refuge in the Chesapeake.',['Compare seasonal retreat with long-distance movement.','Identify where observational evidence comes from.','Read the historical context of the documentary.'],film,'Smithsonian · Ecosystems on the Edge'),
 record('Winter population survey','Survey series','Conservation evidence','Repeated sampling supports population assessment; the published method explains corrections and uncertainty.',['Compare years in the published series.','Separate catch from estimated abundance.','Read method changes before interpreting trends.'],survey,'Maryland DNR'),
 record('Habitat and fishery pressures','Conservation account','Threats','A blue-crab reference connecting ecological pressures with conservation context.',['Separate habitat pressures from harvest pressures.','Compare a biological finding with a management response.','Check the responsible agency for current rules.'],'https://www.chesapeakebay.net/discover/faq/category/blue-crabs','Chesapeake Bay Program')
 ]},
 film:{intro:'A viewing collection organized around the crab, field research and digitization. The embedded film is a historical source; companion records provide context rather than invented footage.',records:[
 record('Blue Crabs: Top Predator in Peril','Documentary','Field research','Smithsonian documentary on blue-crab ecology, research and Chesapeake livelihoods.',['Watch for the distinction between migration and population change.','Identify field instruments when they appear.','Use the discussion themes below; they are not timestamped chapters.'],film,'Smithsonian · Ecosystems on the Edge · historical documentary'),
 record('Blue crabs come to life in 3D','Digitization account','Specimen recording','A behind-the-scenes account of producing the Smithsonian specimen model.',['Follow specimen → scan → digital surface.','Compare digitization with artist sculpting.','Open Models to inspect the separate objects.'],'https://sercblog.si.edu/blue-crabs-come-to-life-in-3d/','Smithsonian Environmental Research Center · 2014'),
 record('Fisheries research media','Research collection','Research context','The research laboratory’s collection contextualizes crab observation and conservation work.',['Select blue-crab material within the broader laboratory collection.','Record the producer and date when citing footage.','Distinguish a research explanation from raw observation video.'],'https://serc.si.edu/labs/fisheries-conservation','Smithsonian Environmental Research Center')
 ]},
 sounds:{intro:'Sound in relation to the crab: acoustic exposure research, listening demonstrations and cultural sound. Experimental playback is not a recording of a crab vocalizing.',records:[
 record('Noise and cross-sensory interference','Acoustic study','Crab research','A 2023 study examines blue-crab sensory responses after noise exposure.',['Compare acoustic exposure with olfactory testing.','Inspect the paper’s hydrophone and recording setup.','Distinguish playback stimuli from sounds emitted by the animal.'],sound,'Solé et al. · Science of the Total Environment 873 · 162260 · 2023'),
 record('100–500 Hz listening reference','Synthetic demonstration','Study context','An adjustable pure tone illustrates frequency only. It does not reproduce the paper’s acoustic exposure, underwater pressure or a crab call.',['Use low speaker volume.','Compare pitch across the displayed range.','Treat the waveform as generated mathematics, not measured animal audio.'],sound,'Labyrinth educational synthesis · range contextualized by Solé et al.'),
 record('Under the Sea: a fictional crab voice','Cultural recording','Fiction','Disney’s official musical performance associated with Sebastian offers a cultural contrast to biological acoustics.',['Listen at the official source.','Separate an anthropomorphic character from the real species.','Keep rights and performer credits with the recording.'],'https://video.disney.com/watch/crab-e-oke-under-the-sea-4e635b0a77c4df9c6a8979a4','Disney · official source-hosted recording','Fictional crab character · not a blue-crab field recording')
 ]}
};
export const crabCollections=expandCrabCollections(baseCollections);
