import {useEffect,useRef} from 'react';
import * as T from 'three';
import {RoundedBoxGeometry} from 'three/addons/geometries/RoundedBoxGeometry.js';
import {EffectComposer} from 'three/addons/postprocessing/EffectComposer.js';
import {RenderPass} from 'three/addons/postprocessing/RenderPass.js';
import {UnrealBloomPass} from 'three/addons/postprocessing/UnrealBloomPass.js';
export default function Landscape({paused,replay,onReady}:{paused:boolean;replay:number;onReady:()=>void}){
 const host=useRef<HTMLDivElement>(null),state=useRef({paused,replay,onReady});state.current={paused,replay,onReady};
 useEffect(()=>{const el=host.current!;let renderer:T.WebGLRenderer;try{renderer=new T.WebGLRenderer({antialias:true,powerPreference:'high-performance'})}catch{el.textContent='The living atlas is ready below.';return}
 renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setClearColor('#0b151c');renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFShadowMap;el.appendChild(renderer.domElement);
 const scene=new T.Scene();scene.fog=new T.FogExp2('#14232b',.023);const camera=new T.PerspectiveCamera(43,1,.1,150);const composer=new EffectComposer(renderer);composer.addPass(new RenderPass(scene,camera));const bloom=new UnrealBloomPass(new T.Vector2(1,1),.45,.5,.82);composer.addPass(bloom);
 scene.add(new T.HemisphereLight('#bedbe4','#1c2c30',1.5));const sun=new T.DirectionalLight('#c4e1e9',3);sun.position.set(-9,16,7);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-14,right:14,top:14,bottom:-14,near:.5,far:65});sun.shadow.bias=-.0005;scene.add(sun);const inner=new T.PointLight('#9ce8df',50,15,2);inner.position.set(0,2,0);scene.add(inner);
 // Deterministic stone relief: original procedural texture, not downloaded artwork.
 const texCanvas=document.createElement('canvas');texCanvas.width=texCanvas.height=256;const ctx=texCanvas.getContext('2d')!,pixels=ctx.createImageData(256,256);for(let y=0;y<256;y++)for(let x=0;x<256;x++){const i=(y*256+x)*4,n=Math.sin(x*12.9898+y*78.233)*43758.5453,v=125+(n-Math.floor(n)) *65+Math.sin(x*.18+Math.cos(y*.12))*15;pixels.data[i]=v;pixels.data[i+1]=v;pixels.data[i+2]=v;pixels.data[i+3]=255}ctx.putImageData(pixels,0,0);const texture=new T.CanvasTexture(texCanvas);texture.wrapS=texture.wrapT=T.RepeatWrapping;texture.repeat.set(2,2);texture.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());
 const stone=new T.MeshStandardMaterial({color:'#728a91',roughness:.83,metalness:.12,bumpMap:texture,bumpScale:.075,roughnessMap:texture});const monument=new T.Group();scene.add(monument);const blocks:{mesh:T.Mesh;base:T.Vector3;angle:number;order:number}[]=[];const blockGeo=new RoundedBoxGeometry(.65,.7,.9,3,.085);
 for(let ring=0;ring<5;ring++){const radius=1.15+ring*.76,count=14+ring*8;for(let i=0;i<count;i++){const angle=i/count*Math.PI*2;if((i+ring*3)%count<3)continue;const height=1+(ring%3)*.28;for(let row=0;row<2+(ring===2?1:0);row++){const mesh=new T.Mesh(blockGeo,stone);mesh.scale.set(.9,height,1);mesh.rotation.y=-angle;mesh.position.set(Math.sin(angle)*radius,row*.72*height+.37,Math.cos(angle)*radius);mesh.castShadow=mesh.receiveShadow=true;monument.add(mesh);blocks.push({mesh,base:mesh.position.clone(),angle,order:(ring*2+row)/12})}}}
 const pedestal=new T.Mesh(new T.CylinderGeometry(5,5.3,.35,96),stone);pedestal.position.y=-.2;pedestal.receiveShadow=true;scene.add(pedestal);
 const heart=new T.Mesh(new T.IcosahedronGeometry(.6,2),new T.MeshStandardMaterial({color:'#ddfff3',emissive:'#8dd5c6',emissiveIntensity:2,roughness:.2,metalness:.4}));heart.position.y=1.7;monument.add(heart);
 const network=new T.LineSegments(new T.WireframeGeometry(new T.IcosahedronGeometry(5.1,2)),new T.LineBasicMaterial({color:'#bde8e7',transparent:true,opacity:.45}));network.position.y=1;scene.add(network);
 const terrainGeo=new T.PlaneGeometry(150,150,180,180);terrainGeo.rotateX(-Math.PI/2);const p=terrainGeo.attributes.position;for(let i=0;i<p.count;i++){const x=p.getX(i),z=p.getZ(i),r=Math.hypot(x,z),fade=T.MathUtils.smoothstep(r,5,15);const elevation=(Math.sin(x*.19+z*.08)*2.8+Math.cos(z*.22)*2+Math.sin(x*.56)*Math.cos(z*.42)*.7+Math.sin(x*1.7+z*.9)*.12)*fade;p.setY(i,-.48+elevation)}terrainGeo.computeVertexNormals();const terrainMat=stone.clone();terrainMat.color.set('#3c535e');const terrain=new T.Mesh(terrainGeo,terrainMat);terrain.receiveShadow=true;scene.add(terrain);
 const particleCount=1500,particleData=new Float32Array(particleCount*3),seeds=new Float32Array(particleCount*3);for(let i=0;i<particleCount;i++){seeds[i*3]=Math.sin(i*17.13)*24;seeds[i*3+1]=(Math.cos(i*13.37)*.5+.5)*18;seeds[i*3+2]=Math.sin(i*37.17)*24}particleData.set(seeds);const particleGeo=new T.BufferGeometry();particleGeo.setAttribute('position',new T.BufferAttribute(particleData,3));const sprite=document.createElement('canvas');sprite.width=sprite.height=32;const sc=sprite.getContext('2d')!,g=sc.createRadialGradient(16,16,0,16,16,16);g.addColorStop(0,'#fff');g.addColorStop(.15,'#fff');g.addColorStop(1,'#ffffff00');sc.fillStyle=g;sc.fillRect(0,0,32,32);const spriteTex=new T.CanvasTexture(sprite);const particles=new T.Points(particleGeo,new T.PointsMaterial({map:spriteTex,color:'#d1e8e8',size:.065,transparent:true,opacity:.65,depthWrite:false,blending:T.AdditiveBlending}));scene.add(particles);
 const roomIds=['world','connections','manifesto','discover','perspectives','fieldnotes','expeditions','fieldkit','connect'];
 const rooms=roomIds.map((id,i)=>({id,center:new T.Vector3(Math.sin(i*.9)*7,-15,-i*23)}));
 // The original panel journey has no exhibit architecture.
 const look=new T.Vector3(),destination=new T.Vector3();
 monument.updateMatrixWorld(true);
 const targets=new Float32Array(18000*3),drift=new Float32Array(18000);
 for(let i=0;i<18000;i++){const block=blocks[i%blocks.length].mesh;const a=block.geometry.attributes.position;const p=new T.Vector3().fromBufferAttribute(a,(i*37)%a.count).applyMatrix4(block.matrixWorld);targets.set(p.toArray(),i*3);drift[i]=(i%997)/997;}
 const formGeo=new T.BufferGeometry();formGeo.setAttribute('position',new T.BufferAttribute(targets,3));formGeo.setAttribute('seed',new T.BufferAttribute(drift,1));
 const formation=new T.ShaderMaterial({transparent:true,depthWrite:false,blending:T.AdditiveBlending,uniforms:{amount:{value:0},clock:{value:0}},vertexShader:`attribute float seed;uniform float amount,clock;varying float alpha;void main(){float spread=1.-amount;vec3 p=position+vec3(sin(seed*173.),cos(seed*61.)*.8+1.,cos(seed*113.))*spread*12.;p+=vec3(sin(clock+seed*43.),cos(clock*.7+seed*29.),sin(clock*.6+seed*71.))*spread*.4;vec4 mv=modelViewMatrix*vec4(p,1.);gl_Position=projectionMatrix*mv;gl_PointSize=clamp(45./max(1.,-mv.z),1.,5.);alpha=(1.-smoothstep(.85,1.,amount))*.85;}`,fragmentShader:`varying float alpha;void main(){float d=length(gl_PointCoord-.5);if(d>.5)discard;gl_FragColor=vec4(.7,.88,.88,alpha*(1.-d*2.));}`});
 const fragments=new T.Points(formGeo,formation);scene.add(fragments);stone.transparent=true;

 let frame=0,started=performance.now(),last=started,time=0,scroll=scrollY,target=scrollY,mx=0,my=0,px=0,py=0,version=state.current.replay;const reduced=matchMedia('(prefers-reduced-motion: reduce)');
 const resize=()=>{const w=innerWidth,h=innerHeight;renderer.setSize(w,h);composer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix()};const onScroll=()=>{target=scrollY};const pointer=(e:PointerEvent)=>{mx=e.clientX/innerWidth-.5;my=e.clientY/innerHeight-.5};resize();addEventListener('resize',resize);addEventListener('scroll',onScroll,{passive:true});addEventListener('pointermove',pointer,{passive:true});state.current.onReady();
 const draw=(now:number)=>{frame=requestAnimationFrame(draw);if(document.hidden){last=now;return}const dt=Math.min(.04,(now-last)/1000);last=now;const still=state.current.paused||reduced.matches;if(version!==state.current.replay){version=state.current.replay;started=now}if(!still)time+=dt;scroll+=(target-scroll)*(still?1:.055);px+=(mx-px)*.035;py+=(my-py)*.035;const intro=still?1:T.MathUtils.clamp((now-started)/6500,0,1),ease=1-Math.pow(1-intro,3),journey=scroll/innerHeight;
 for(const b of blocks){const assemble=T.MathUtils.smoothstep(intro,b.order*.3,.65+b.order*.3),spread=(1-assemble)*2+Math.sin(Math.min(journey,1.7)/1.7*Math.PI)*.4;b.mesh.position.copy(b.base);b.mesh.position.x*=1+spread;b.mesh.position.z*=1+spread;b.mesh.position.y+=(1-assemble)*(3+b.order*4);b.mesh.rotation.y=-b.angle+(1-assemble)*.4}
 (network.material as T.LineBasicMaterial).opacity=(1-ease)*.7+.025;network.rotation.y=time*.025;heart.rotation.y=time*.22;heart.position.y=1.7+(still?0:Math.sin(time)*.1);
 const angle=.55+(still?0:px*.13),distance=17+(1-ease)*9;destination.set(Math.sin(angle)*distance,8+(1-ease)*10,Math.cos(angle)*distance);look.set(0,.8,0);
 const positions=rooms.map(r=>({room:r,top:(document.getElementById(r.id)?.getBoundingClientRect().top??0)+scrollY}));
 const first=positions[0].top;const entry=T.MathUtils.smoothstep(scroll,Math.max(100,first-innerHeight),first);
 if(entry>0){let current=0;positions.forEach((p,i)=>{if(scroll+innerHeight*.15>=p.top)current=i});const a=positions[current],b=positions[Math.min(current+1,positions.length-1)];const next=T.MathUtils.smoothstep(scroll,b.top-innerHeight*.85,b.top-innerHeight*.15);const position=a.room.center.clone().lerp(b.room.center,next);const roomCamera=position.clone().add(new T.Vector3(still?0:px*.28,.3+(still?0:py*.15),9));destination.lerp(roomCamera,entry);look.lerp(position.clone().add(new T.Vector3(0,.5,-4)),entry)}
 destination.set(Math.sin(angle)*distance,8,Math.cos(angle)*distance);look.set(0,.8,0);camera.position.copy(destination);camera.lookAt(look);scene.fog=new T.FogExp2('#101f29',.018+entry*.012);
 const form=still?1:Math.min(T.MathUtils.smoothstep(intro,0,.85),1-T.MathUtils.smoothstep(journey,.5,1.6));formation.uniforms.amount.value=form;formation.uniforms.clock.value=time;stone.opacity=T.MathUtils.smoothstep(form,.72,1);monument.visible=form>.72;particles.visible=false;if(!still){for(let i=0;i<particleCount;i++){particleData[i*3]=seeds[i*3]+Math.sin(time*.2+i)*.3;particleData[i*3+1]=(seeds[i*3+1]-time*.13+180)%18;particleData[i*3+2]=seeds[i*3+2]+Math.cos(time*.12+i)*.2}particleGeo.attributes.position.needsUpdate=true}composer.render();};frame=requestAnimationFrame(draw);
 return()=>{cancelAnimationFrame(frame);removeEventListener('resize',resize);removeEventListener('scroll',onScroll);removeEventListener('pointermove',pointer);scene.traverse(o=>{const m=o as T.Mesh;m.geometry?.dispose();if(m.material)(Array.isArray(m.material)?m.material:[m.material]).forEach(mat=>mat.dispose())});texture.dispose();spriteTex.dispose();composer.dispose();renderer.dispose();renderer.domElement.remove()};
 },[]);return <div ref={host} className="lc-renderer"/>;
}
