import {useEffect,useRef,useState} from 'react';
import './home-atmosphere.css';
const chapters=[['entrance','The entrance'],['world','The living world'],['connections','Connections'],['manifesto','A closer look'],['discover','The collection'],['perspectives','In focus'],['fieldnotes','Sources & evidence'],['expeditions','Reading calendar'],['fieldkit','Field kit'],['connect','Keep in touch']];
export default function HomeAtmosphere({paused}:{paused:boolean}){
 const canvas=useRef<HTMLCanvasElement>(null),[chapter,setChapter]=useState(0),[progress,setProgress]=useState(0),[open,setOpen]=useState(false);
 useEffect(()=>{const c=canvas.current!,ctx=c.getContext('2d');if(!ctx)return;const reduced=matchMedia('(prefers-reduced-motion: reduce)');let w=0,h=0,frame=0,t=0,target=scrollY,scroll=target,mx=0,my=0,px=0,py=0,last=0;
 const resize=()=>{w=innerWidth;h=innerHeight;const d=Math.min(devicePixelRatio,1.5);c.width=w*d;c.height=h*d;ctx.setTransform(d,0,0,d,0,0)};
 const onScroll=()=>{target=scrollY;setProgress(Math.round(target/Math.max(1,document.documentElement.scrollHeight-h)*100));let active=0;chapters.forEach(([id],i)=>{if((document.getElementById(id)?.getBoundingClientRect().top??Infinity)<h*.48)active=i});setChapter(active)};
 let hovered:HTMLElement|null=null;
 const pointer=(e:PointerEvent)=>{mx=e.clientX/w-.5;my=e.clientY/h-.5;const card=(e.target as HTMLElement).closest<HTMLElement>('.lh-record,.lh-note,.lh-two-paths>a');if(hovered&&hovered!==card){hovered.style.removeProperty('--rx');hovered.style.removeProperty('--ry');hovered.style.removeProperty('--shine')}hovered=card;if(card&&!paused&&!reduced.matches){const r=card.getBoundingClientRect(),x=(e.clientX-r.left)/r.width,y=(e.clientY-r.top)/r.height;card.style.setProperty('--rx',`${(y-.5)*-4}deg`);card.style.setProperty('--ry',`${(x-.5)*5}deg`);card.style.setProperty('--shine',`${x*100}% ${y*100}%`)}};resize();onScroll();addEventListener('resize',resize);addEventListener('scroll',onScroll,{passive:true});addEventListener('pointermove',pointer,{passive:true});
 const draw=(now:number)=>{frame=requestAnimationFrame(draw);if(document.hidden||now-last<32)return;last=now;const still=paused||reduced.matches;if(!still)t+=.008;scroll+=(target-scroll)*.075;px+=(mx-px)*.05;py+=(my-py)*.05;ctx.clearRect(0,0,w,h);const offset=still?0:scroll*.045;const glow=ctx.createRadialGradient(w*(.5+Math.sin(scroll*.00025)*.2),h*.5,0,w*.5,h*.5,w*.7);glow.addColorStop(0,'rgba(76,119,132,.13)');glow.addColorStop(1,'rgba(5,10,15,0)');ctx.fillStyle=glow;ctx.fillRect(0,0,w,h);
 for(let row=0;row<15;row++){ctx.beginPath();for(let col=0;col<=38;col++){const x=col*w/38,y=h*.3+row*38+Math.sin(col*.28+row*.22+t+offset*.01)*25+Math.cos(col*.13+t*.3)*35+(still?0:py*12);col?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.strokeStyle=`rgba(121,164,173,${.016+row*.0015})`;ctx.lineWidth=.6;ctx.stroke()}
 for(let i=0;i<70;i++){const x=((Math.sin(i*49.7)*.5+.5)*w+(still?0:px*20*(i%3+1))+w)%w,y=((Math.cos(i*27.3)*.5+.5)*h-offset*(i%3+1)+h*100)%h;ctx.fillStyle=`rgba(190,219,219,${.12+(i%4)*.07})`;ctx.fillRect(x,y,i%7===0?2:1,i%7===0?2:1)}
 };frame=requestAnimationFrame(draw);
 const elements=Array.from(document.querySelectorAll<HTMLElement>('.lh-section-label,.lh-title-row,.lh-essay-photo,.lh-record,.lh-note,.lh-market-feature>div,.lh-connect>div,.lh-footer-directory>div'));
 const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('la-arrived');io.unobserve(e.target)}}),{threshold:.08});elements.forEach((el,i)=>{el.classList.add('la-reveal');el.style.setProperty('--la-delay',`${i%3*70}ms`);io.observe(el)});
 return()=>{cancelAnimationFrame(frame);io.disconnect();elements.forEach(el=>el.classList.remove('la-reveal','la-arrived'));removeEventListener('resize',resize);removeEventListener('scroll',onScroll);removeEventListener('pointermove',pointer)};
 },[paused]);
 return <><canvas ref={canvas} className="la-atmosphere" aria-hidden="true"/><div className="la-progress" style={{transform:`scaleX(${progress/100})`}}/><aside className="la-navigator" aria-label="Journey navigation"><button onClick={()=>setOpen(!open)} aria-expanded={open} aria-controls="la-index"><span>{String(chapter+1).padStart(2,'0')} / {String(chapters.length).padStart(2,'0')}</span><strong>{chapters[chapter][1]}</strong><span>{open?'−':'+'}</span></button>{open&&<nav id="la-index" aria-label="All homepage chapters">{chapters.map(([id,label],i)=><button key={id} aria-current={i===chapter?'location':undefined} onClick={()=>{document.getElementById(id)?.scrollIntoView({behavior:paused||matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});setOpen(false)}}><small>{String(i+1).padStart(2,'0')}</small>{label}<span>↗</span></button>)}</nav>}</aside></>;
}
