import {useEffect,useRef,useState,type CSSProperties} from 'react';
import {ArrowUpRight,ArrowDown,ArrowLeft,ArrowRight,Search,X,Menu,Volume2,VolumeX,Settings2,Bookmark,Plus,Minus,RotateCcw,Globe2,Grid2X2,List,Compass,Play,Pause,Check} from 'lucide-react';
import {records} from './chesapeake-data';
import land from './crab-world-land.json';
import './homepage.css';
import './homepage-dark.css';
import {FieldSequence,ExpeditionCalendar,MarketplaceFeature,StayConnected} from './home-lando';
import {useHomeScrollMotion} from './home-scroll-motion';
import './home-scroll-polish.css';
import {MessengerWorld} from './home-messenger';
import ConnectionSequence from './home-igloo';
import HomeAtmosphere from './home-atmosphere';
import {useObjectParticles} from './use-object-particles';
import CinematicEntrance from './home-cinematic';


const sections=[['world','The living world'],['discover','Find your next question'],['perspectives','Change your perspective'],['fieldnotes','From the field']] as const;
const photos={water:'https://images.unsplash.com/photo-1518837695005-2083093ee35b?auto=format&fit=crop&w=1600&q=85',forest:'https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=1200&q=85',mountain:'https://images.unsplash.com/photo-1464822759023-ddf4f1a6c224?auto=format&fit=crop&w=1200&q=85'};
const art=[`${import.meta.env.BASE_URL}blue-crab-hero.png`,photos.water,photos.forest,photos.mountain];
const paths=[{title:'The blue crab.',label:'01 / SPECIES',text:'Begin with the blue crab. Follow the connections between a species, its habitat and the people studying it.',href:'?entry=SP-001',image:art[0]}, {title:'Underwater habitats.',label:'02 / HABITATS',text:'Explore underwater grass habitats and the records that describe them.',href:'?entry=HB-001',image:art[1]}, {title:'Measuring the Bay.',label:'03 / FIELD ASSETS',text:'Meet the monitoring stations that turn changing conditions into a record we can read.',href:'?entry=AS-001',image:art[2]}];
function readSaved(){try{return JSON.parse(localStorage.getItem('labyrinth-home-saved')||'[]') as string[]}catch{return []}}
function Mark(){return <svg viewBox="0 0 48 48" fill="none" aria-hidden="true"><path d="M24 3 45 15v18L24 45 3 33V15L24 3Zm0 8 14 8v10l-14 8-14-8V19l14-8Zm0 8 7 4v2l-7 4-7-4v-2l7-4Z" stroke="currentColor" strokeWidth="1.7"/><path d="M24 3v8m21 22-7-4M3 33l7-4" stroke="currentColor" strokeWidth="2"/></svg>}
function World({paused,wire,zoom,onSelect,assembly,replay}:{paused:boolean;wire:boolean;zoom:number;onSelect:()=>void;assembly:number|null;replay:number}){
 const canvas=useRef<HTMLCanvasElement>(null),rotation=useRef({x:-.25,y:1.25}),drag=useRef<{x:number;y:number}|null>(null);
 useEffect(()=>{const el=canvas.current;if(!el)return;const c=el.getContext('2d');if(!c)return;const buffer=document.createElement('canvas');const bc=buffer.getContext('2d');const began=performance.now();let frame=0,visible=true,last=0;const observer=new IntersectionObserver(e=>visible=e[0].isIntersecting);observer.observe(el);
 const draw=(time:number)=>{frame=requestAnimationFrame(draw);if(!visible)return;const dt=Math.min(time-last,40);last=time;const box=el.getBoundingClientRect(),dpr=Math.min(devicePixelRatio,2);if(el.width!==Math.round(box.width*dpr)||el.height!==Math.round(box.height*dpr)){el.width=box.width*dpr;el.height=box.height*dpr}c.setTransform(dpr,0,0,dpr,0,0);const w=box.width,h=box.height,r=Math.min(w,h)*.345*zoom,cx=w*.5,cy=h*.49;c.clearRect(0,0,w,h);if(!paused&&!drag.current)rotation.current.y+=dt*.000055;
 const project=(lon:number,lat:number)=>{const a=lon*Math.PI/180+rotation.current.y,b=lat*Math.PI/180;const x=Math.cos(b)*Math.sin(a),y=Math.sin(b),z=Math.cos(b)*Math.cos(a),pitch=rotation.current.x;return [cx+x*r,cy-(y*Math.cos(pitch)-z*Math.sin(pitch))*r,y*Math.sin(pitch)+z*Math.cos(pitch)]};
 const glow=c.createRadialGradient(cx-r*.28,cy-r*.3,r*.03,cx,cy,r*1.22);glow.addColorStop(0,'#365c50');glow.addColorStop(.7,'#142e29');glow.addColorStop(.82,'#0b1c19');glow.addColorStop(.83,'#a6cbb14d');glow.addColorStop(1,'#70977b00');c.fillStyle=glow;c.beginPath();c.arc(cx,cy,r*1.22,0,Math.PI*2);c.fill();
 c.save();c.beginPath();c.arc(cx,cy,r,0,Math.PI*2);c.clip();c.strokeStyle=wire?'#a9c69c66':'#87a58723';c.lineWidth=.65;for(let lat=-75;lat<=75;lat+=15){c.beginPath();let pen=false;for(let lon=-180;lon<=180;lon+=3){const [x,y,z]=project(lon,lat);if(z>0){if(!pen)c.moveTo(x,y);else c.lineTo(x,y);pen=true}else pen=false}c.stroke()}for(let lon=-180;lon<180;lon+=20){c.beginPath();let pen=false;for(let lat=-90;lat<=90;lat+=3){const[x,y,z]=project(lon,lat);if(z>0){if(!pen)c.moveTo(x,y);else c.lineTo(x,y);pen=true}else pen=false}c.stroke()}
 for(const polygon of land){c.beginPath();let pen=false;for(const p of polygon){const[x,y,z]=project(p[0],p[1]);if(z>-.03){if(!pen)c.moveTo(x,y);else c.lineTo(x,y);pen=true}else pen=false}c.strokeStyle=wire?'#d5e5a2':'#bbc69988';c.lineWidth=wire?1:.65;c.stroke();if(!wire&&polygon.every(p=>project(p[0],p[1])[2]>0)){c.closePath();c.fillStyle='#748c6260';c.fill()}}
 const [px,py,pz]=project(-76,38);if(pz>0){c.fillStyle='#dcf5a0';c.shadowColor='#d1ed99';c.shadowBlur=15;c.beginPath();c.arc(px,py,4,0,Math.PI*2);c.fill();c.shadowBlur=0;c.strokeStyle='#d8ef9b80';c.beginPath();c.arc(px,py,10+Math.sin(time/700)*2,0,Math.PI*2);c.stroke();c.font='10px monospace';c.fillText('CHESAPEAKE BAY',px+18,py+4)}c.restore();
 c.strokeStyle='#b4c2a333';c.lineWidth=.7;for(let k=0;k<3;k++){c.save();c.translate(cx,cy);c.rotate(-.4+k*.65);c.beginPath();c.ellipse(0,0,r*1.28,r*(.37+k*.08),0,0,Math.PI*2);c.stroke();c.restore()}for(let i=0;i<65;i++){const a=i*2.399,x=cx+Math.cos(a)*(r*1.3+i%9*8),y=cy+Math.sin(a)*(r*1.1+i%7*7);c.fillStyle=i%5===0?'#dae7b6':'#a5b39855';c.fillRect(x,y,i%5===0?2:1,i%5===0?2:1,)}
 const progress=paused?1:assembly===null?Math.min(1,(time-began)/4200):assembly/100;
 if(progress<1&&bc){buffer.width=el.width;buffer.height=el.height;bc.drawImage(el,0,0);c.clearRect(0,0,w,h);c.strokeStyle='#bddea64d';c.lineWidth=.7;c.beginPath();c.arc(cx,cy,r,0,Math.PI*2);c.stroke();for(let band=0;band<10;band++){const amount=Math.max(0,Math.min(1,(progress-band*.045)*1.85));const ease=1-Math.pow(1-amount,3);const sy=band*h/10;c.globalAlpha=ease;c.drawImage(buffer,0,sy*dpr,w*dpr,h/10*dpr,(1-ease)*(band%2?100:-100),sy+(1-ease)*18,w,h/10)}c.globalAlpha=1}
 };frame=requestAnimationFrame(draw);return()=>{cancelAnimationFrame(frame);observer.disconnect()}},[paused,wire,zoom,assembly,replay]);
 return <canvas ref={canvas} className="lh-world-canvas" tabIndex={0} role="img" aria-label="Interactive globe. Drag to rotate, arrow keys to turn, Enter to explore Chesapeake Bay." onKeyDown={e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();rotation.current.y+=e.key==='ArrowLeft'?-.12:e.key==='ArrowRight'?.12:0;rotation.current.x+=e.key==='ArrowUp'?.08:e.key==='ArrowDown'?-.08:0}if(e.key==='Enter')onSelect()}} onPointerDown={e=>{drag.current={x:e.clientX,y:e.clientY};e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{if(drag.current){rotation.current.y+=(e.clientX-drag.current.x)*.006;rotation.current.x=Math.max(-1,Math.min(1,rotation.current.x+(e.clientY-drag.current.y)*.004));drag.current={x:e.clientX,y:e.clientY}}}} onPointerUp={()=>drag.current=null} onPointerCancel={()=>drag.current=null} onDoubleClick={onSelect}/>;
}
export default function HomePage(){
 const [assembly,setAssembly]=useState<number|null>(null),[replay,setReplay]=useState(0);
 const [panel,setPanel]=useState<'menu'|'search'|'settings'|null>(null),[query,setQuery]=useState(''),[filter,setFilter]=useState('All'),[layout,setLayout]=useState('Grid'),[saved,setSaved]=useState(readSaved),[slide,setSlide]=useState(0),[paused,setPaused]=useState(()=>matchMedia('(prefers-reduced-motion: reduce)').matches),[wire,setWire]=useState(false),[zoom,setZoom]=useState(1),[sound,setSound]=useState(false),[volume,setVolume]=useState(.15),[large,setLarge]=useState(false),[active,setActive]=useState('world'),[focus,setFocus]=useState<string|null>(null),[toast,setToast]=useState(''),[tour,setTour]=useState(-1),[scan,setScan]=useState(false),[scanned,setScanned]=useState(false);
 const audio=useRef<AudioContext|null>(null),gain=useRef<GainNode|null>(null),dialog=useRef<HTMLDialogElement>(null),backFocus=useRef<HTMLElement|null>(null),hero=useRef<HTMLElement>(null),scanTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const toggleSave=(id:string)=>setSaved(old=>{const next=old.includes(id)?old.filter(v=>v!==id):[...old,id];try{localStorage.setItem('labyrinth-home-saved',JSON.stringify(next))}catch{}setToast(next.includes(id)?'Saved to your collection':'Removed from your collection');return next});
 useEffect(()=>{document.title='Labyrinth — Follow your curiosity';const nodes=document.querySelectorAll('.lh-reveal');const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('lh-seen')}),{threshold:.12});nodes.forEach(n=>observer.observe(n));const chapters=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)setActive(e.target.id)}),{rootMargin:'-25% 0px -45% 0px'});sections.forEach(([id])=>{const n=document.getElementById(id);if(n)chapters.observe(n)});return()=>{observer.disconnect();chapters.disconnect();audio.current?.close();if(scanTimer.current)clearTimeout(scanTimer.current)}},[]);
 useEffect(()=>{if(!toast)return;const id=setTimeout(()=>setToast(''),2400);return()=>clearTimeout(id)},[toast]);
 useEffect(()=>{if(panel||focus){backFocus.current=document.activeElement as HTMLElement;dialog.current?.showModal();document.body.style.overflow='hidden'}else{dialog.current?.close();document.body.style.overflow='';backFocus.current?.focus()}return()=>{document.body.style.overflow=''}},[panel,focus]);
 useEffect(()=>{const fn=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();setPanel('search')}};window.addEventListener('keydown',fn);return()=>window.removeEventListener('keydown',fn)},[]);
 useEffect(()=>{if(gain.current&&audio.current)gain.current.gain.setTargetAtTime(sound?volume:0,audio.current.currentTime,.3)},[volume,sound]);
 const toggleAudio=async()=>{if(!audio.current){const ctx=new AudioContext();audio.current=ctx;const g=ctx.createGain();g.gain.value=0;g.connect(ctx.destination);gain.current=g;[110,164.81,220,277.18].forEach((hz,i)=>{const o=ctx.createOscillator(),v=ctx.createGain();o.type='sine';o.frequency.value=hz;v.gain.value=.11/(i+1);o.connect(v);v.connect(g);o.start()})}await audio.current.resume();setSound(v=>!v)};
 const close=()=>{setPanel(null);setFocus(null)};
 const travel=(id:string)=>{close();document.getElementById(id)?.scrollIntoView({behavior:paused?'instant':'smooth'})};
 const matches=records.filter(r=>(filter==='All'||filter==='Saved'?filter!=='Saved'||saved.includes(r.id):r.type===filter)&&(r.name+' '+r.area+' '+r.id).toLowerCase().includes(query.toLowerCase()));
 const detail=records.find(r=>r.id===focus);
 useHomeScrollMotion(paused,slide);
 useObjectParticles(paused);
 return <div className={`lh ${paused?'lh-still':''} ${large?'lh-large':''}`}><HomeAtmosphere paused={paused}/><CinematicEntrance paused={paused}/>
 <a className="lh-skip" href="#discover">Skip to discoveries</a>
 <header className="lh-header"><a href="./" className="lh-brand" aria-label="Labyrinth home"><Mark/><span>LABYRINTH<small>A WORLD OF CONNECTIONS</small></span></a><nav aria-label="Main"><a href="?view=archive">Exploration <ArrowUpRight size={12}/></a><button onClick={()=>travel('perspectives')}>Our approach</button><button onClick={()=>travel('fieldnotes')}>Field notes</button></nav><div className="lh-header-tools"><button aria-label="Search Labyrinth" onClick={()=>setPanel('search')}><Search size={18}/></button><button className="lh-menu-button" aria-label="Open menu" onClick={()=>setPanel('menu')}>MENU <Menu size={16}/></button></div></header>
 <main className="lh-main">
 <section id="world" ref={hero} className="lh-hero" onPointerMove={e=>{if(!paused&&hero.current){const box=hero.current.getBoundingClientRect();hero.current.style.setProperty('--px',String((e.clientX-box.left)/box.width-.5));hero.current.style.setProperty('--py',String((e.clientY-box.top)/box.height-.5))}}}>
 <div className="lh-contours" aria-hidden="true">{Array.from({length:9},(_,i)=><i key={i} style={{'--i':i} as CSSProperties}/>)}</div>
 <div className="lh-hero-top"><span><i/> THE LIVING ATLAS</span><span>CHESAPEAKE BAY / FIRST COLLECTION</span></div>
 <div className="lh-hero-copy"><p className="lh-micro">NATURE. KNOWLEDGE. CONTEXT.</p><h1>Follow your<br/><em>curiosity.</em></h1><p className="lh-intro">Explore species, habitats and observations.<br/>See how each fits into a larger world.</p><button className="lh-pill lh-lime" onClick={()=>travel('discover')}>Find your starting point <ArrowUpRight size={18}/></button><MessengerWorld paused={paused}/></div>
 <div className="lh-orb"><World paused={paused} wire={wire} zoom={zoom} assembly={assembly} replay={replay} onSelect={()=>setFocus('SP-001')}/><div className="lh-orb-tag"><span>01 / THE LIVING WORLD</span><button onClick={()=>{setZoom(1);setWire(v=>!v)}}>{wire?'Surface':'Wireframe'} <Globe2 size={14}/></button></div><div className="lh-orb-controls"><button aria-label="Zoom out" disabled={zoom<=.7} onClick={()=>setZoom(v=>Math.max(.7,v-.15))}><Minus size={14}/></button><span>DRAG TO ROTATE</span><button aria-label="Zoom in" disabled={zoom>=1.45} onClick={()=>setZoom(v=>Math.min(1.45,v+.15))}><Plus size={14}/></button></div><div className="lh-assembly-controls"><button onClick={()=>{setAssembly(null);setReplay(v=>v+1)}} aria-label="Replay globe assembly"><RotateCcw size={12}/> ASSEMBLE</button><input aria-label="Globe assembly progress" type="range" min="0" max="100" value={assembly??100} onChange={e=>setAssembly(+e.target.value)}/></div></div>
 <div className="lh-hero-bottom"><button className="lh-ticket" onClick={()=>travel('expeditions')}><svg viewBox="0 0 80 45" aria-hidden="true"><path d="M3 22 18 15 24 27 39 8 44 32 55 25 62 36 77 18" fill="none" stroke="currentColor"/><circle cx="39" cy="8" r="3" fill="currentColor"/></svg><span>YOUR FIRST EXPEDITION<strong>Chesapeake Bay</strong><small>PLAN YOUR NEXT DISCOVERY</small></span><ArrowUpRight size={20}/></button><button className="lh-scroll" onClick={()=>travel('manifesto')}>THERE'S MORE BELOW <ArrowDown size={17}/></button></div>
 </section>
 <ConnectionSequence paused={paused}/><FieldSequence/>
 <section id="discover" className="lh-discover"><div className="lh-section-label"><span>02 — OPEN THE COLLECTION</span><span>SPECIES / HABITATS / FIELD ASSETS</span></div><div className="lh-title-row lh-reveal"><h2>The collection<em>.</em></h2><a className="lh-text-link" href="?view=archive">Enter the Archive <ArrowUpRight size={18}/></a></div>
 <div className="lh-filterbar"><div className="lh-filters" aria-label="Filter discoveries">{['All','Species','Habitat','Asset','Saved'].map(v=><button key={v} aria-pressed={filter===v} className={filter===v?'selected':''} onClick={()=>setFilter(v)}>{v==='All'?'Everything':v}{v==='Saved'&&saved.length>0?' '+saved.length:''}</button>)}</div><div className="lh-view-controls"><button aria-label="Grid view" aria-pressed={layout==='Grid'} onClick={()=>setLayout('Grid')}><Grid2X2 size={17}/></button><button aria-label="List view" aria-pressed={layout==='List'} onClick={()=>setLayout('List')}><List size={19}/></button><button aria-label="Search discoveries" onClick={()=>setPanel('search')}><Search size={18}/></button></div></div>
 <div className={`lh-records ${layout==='List'?'lh-records-list':''}`}>{matches.map((r,i)=><article className="lh-record" key={r.id}><button className="lh-record-visual" onClick={()=>setFocus(r.id)} aria-label={`Preview ${r.name}`}><img src={r.id==='SP-001'?art[0]:r.type==='Species'?art[1]:r.type==='Habitat'?art[2]:art[3]} alt={r.id==='SP-001'?'Blue crab with blue claws':'Landscape illustration for this collection'} loading="lazy"/><span className="lh-image-index">{r.id}</span><span className="lh-visual-caption">{r.id==='SP-001'?'Callinectes sapidus':'Collection image · illustrative'}</span><span className="lh-card-open"><ArrowUpRight/></span></button><div className="lh-record-info"><p>{r.type.toUpperCase()} <span>0{i+1}</span></p><h3><button onClick={()=>setFocus(r.id)}>{r.name}</button></h3><div><span>{r.area}</span><button aria-label={`${saved.includes(r.id)?'Unsave':'Save'} ${r.name}`} aria-pressed={saved.includes(r.id)} onClick={()=>toggleSave(r.id)}><Bookmark size={16} fill={saved.includes(r.id)?'currentColor':'none'}/></button></div></div></article>)}</div>{matches.length===0&&<div className="lh-empty"><Bookmark/><h3>A little room for discovery.</h3><p>{filter==='Saved'?'Save a record using its bookmark. Your collection stays in this browser.':'No records match this selection.'}</p><button className="lh-pill" onClick={()=>{setFilter('All');setQuery('')}}>Explore everything</button></div>}
 </section>
 <section id="perspectives" className="lh-perspectives"><div className="lh-perspective-image" key={slide}><img src={paths[slide].image} alt="" loading="lazy"/></div><div className="lh-perspective-overlay"/><div className="lh-section-label"><span>03 — IN FOCUS</span><span>{String(slide+1).padStart(2,'0')} / 03</span></div><div className="lh-perspective-copy" key={'text'+slide}><p className="lh-micro">{paths[slide].label}</p><h2>{paths[slide].title}</h2><p>{paths[slide].text}</p><a className="lh-pill lh-lime" href={paths[slide].href}>Read the profile <ArrowUpRight size={17}/></a></div><div className="lh-perspective-bottom"><div className="lh-segmented" role="tablist" aria-label="Perspectives">{paths.map((p,i)=><button key={p.label} role="tab" aria-selected={slide===i} onClick={()=>setSlide(i)}>{p.label.split(' / ')[1]}</button>)}</div><div className="lh-arrows"><button aria-label="Previous perspective" onClick={()=>setSlide(v=>(v+2)%3)}><ArrowLeft/></button><button aria-label="Next perspective" onClick={()=>setSlide(v=>(v+1)%3)}><ArrowRight/></button></div></div></section>
 <section id="fieldnotes" className="lh-fieldnotes"><div className="lh-section-label"><span>04 — FROM THE FIELD</span><span>KNOWLEDGE, WITH A POINT OF ORIGIN</span></div><div className="lh-title-row lh-reveal"><h2>Sources &amp;<br/><em>evidence.</em></h2><p>Explore the sources behind the collection.<br/>Real records. Traceable observations.</p></div><div className="lh-notes-grid">{[{n:'01',name:'Maryland DNR',topic:'Blue crab assessments',url:'https://dnr.maryland.gov/fisheries/pages/blue-crab/dredge.aspx',text:'Read the published monitoring source behind the species profile.'},{n:'02',name:'VIMS',topic:'Underwater grass surveys',url:'https://www.vims.edu/research/units/programs/sav/access/tables/segment_area/',text:'Follow habitat observations back to their survey segments.'},{n:'03',name:'NOAA',topic:'Conditions in the Bay',url:'https://tidesandcurrents.noaa.gov/stationhome.html?id=8571892',text:'Explore the Cambridge station and its published observations.'}].map(n=><a key={n.n} href={n.url} target="_blank" rel="noreferrer" className="lh-note"><span>{n.n} / FIELD SOURCE <ArrowUpRight size={18}/></span><h3>{n.name}</h3><strong>{n.topic}</strong><p>{n.text}</p></a>)}</div></section>
 <ExpeditionCalendar/><MarketplaceFeature/><StayConnected/>
 </main>
 <footer className="lh-footer"><a className="lh-brand" href="./"><Mark/><span>LABYRINTH<small>FOLLOW YOUR CURIOSITY</small></span></a><div className="lh-footer-directory"><div><strong>EXPLORE</strong><a href="?view=archive">Archive</a><a href="?view=map">3D map</a><a href="?view=marketplace">Marketplace</a><button onClick={()=>travel('expeditions')}>Your calendar</button></div><div><strong>CONNECT</strong><button onClick={()=>travel('connect')}>Follow & share</button><button onClick={()=>travel('fieldnotes')}>Source organizations</button><button onClick={()=>setPanel('search')}>Search</button></div><div><strong>YOUR EXPERIENCE</strong><button onClick={()=>setPanel('settings')}>Settings</button><button onClick={()=>{setFilter('Saved');setQuery('');travel('discover')}}>Saved discoveries</button><button onClick={()=>travel('world')}>Back to top ↑</button></div></div><span>Independent exploration.<br/>Connected knowledge.</span></footer><div className="lh-footer-wordmark"><a href="?view=archive">Enter the <em>Archive.</em><ArrowUpRight/></a></div>
 <aside className="lh-dock" aria-label="Experience controls"><button aria-label={sound?'Mute ambient sound':'Enable ambient sound'} aria-pressed={sound} onClick={toggleAudio}>{sound?<Volume2 size={16}/>:<VolumeX size={16}/>}</button><span/><button aria-label={paused?'Enable motion':'Pause motion'} aria-pressed={paused} onClick={()=>setPaused(v=>!v)}>{paused?<Play size={15}/>:<Pause size={15}/>}</button><button aria-label="Experience settings" onClick={()=>setPanel('settings')}><Settings2 size={16}/></button></aside>
 <nav className="lh-chapters" aria-label="Page chapters">{sections.map(([id,title],i)=><button key={id} aria-label={title} aria-current={active===id?'location':undefined} onClick={()=>travel(id)}><span>{title}</span>{String(i+1).padStart(2,'0')}</button>)}</nav>
 {toast&&<div className="lh-toast" role="status"><Check size={16}/>{toast}</div>}
 <dialog ref={dialog} className={`lh-dialog ${panel==='menu'?'lh-menu-dialog':''}`} onCancel={e=>{e.preventDefault();close()}} onClick={e=>{if(e.target===dialog.current)close()}}><div className="lh-dialog-inner"><button className="lh-close" aria-label="Close dialog" onClick={close}><X/></button>
 {panel==='menu'&&<><div className="lh-menu-art">{art.map((src,i)=><img key={i} src={src} alt={['Blue crab','Open water','Forest','Mountains'][i]}/>)}</div><div className="lh-menu-links"><a href="./" className="lh-brand"><Mark/><span>LABYRINTH</span></a><p className="lh-micro">CHOOSE A DIRECTION</p>{[['world','Home'],['discover','Discover'],['paths','Perspectives'],['expeditions','Calendar']].map(([id,name],i)=><button key={id} onClick={()=>travel(id)} className={active===id?'active':''}><small>0{i+1}</small>{name}<ArrowUpRight/></button>)}<a href="?view=archive">Enter the Archive <ArrowUpRight size={18}/></a></div><div className="lh-menu-utilities"><a href="?view=marketplace">MARKETPLACE <ArrowUpRight size={14}/></a><button onClick={()=>travel('connect')}>FOLLOW & SHARE</button><button onClick={()=>travel('fieldnotes')}>FIELD SOURCES</button><span>A WORLD OF CONNECTIONS.</span></div></>}
 {panel==='search'&&<div className="lh-search-panel"><p className="lh-micro">FOLLOW A QUESTION</p><h2>What draws you in?</h2><label><Search/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Species, habitats, places…" aria-label="Search records"/></label><p aria-live="polite">{records.filter(r=>(r.name+' '+r.area).toLowerCase().includes(query.toLowerCase())).length} discoveries</p><div className="lh-search-results">{records.filter(r=>(r.name+' '+r.area).toLowerCase().includes(query.toLowerCase())).map(r=><button key={r.id} onClick={()=>{setPanel(null);setFocus(r.id)}}><small>{r.type} / {r.id}</small><strong>{r.name}</strong><ArrowUpRight size={20}/></button>)}</div>{!records.some(r=>(r.name+' '+r.area).toLowerCase().includes(query.toLowerCase()))&&<p>No matches. Try “crab”, “grass” or “Cambridge”.</p>}</div>}
 {panel==='settings'&&<div className="lh-settings"><p className="lh-micro">MAKE YOURSELF AT HOME</p><h2>Your experience.</h2><label>Motion <button aria-pressed={!paused} onClick={()=>setPaused(v=>!v)}>{paused?'Paused':'On'}</button></label><label>Ambient sound <button aria-pressed={sound} onClick={toggleAudio}>{sound?'On':'Off'}</button></label><label>Volume <input type="range" min="0" max=".4" step=".01" aria-label="Ambient volume" value={volume} onChange={e=>setVolume(+e.target.value)}/></label><label>Larger reading text <button aria-pressed={large} onClick={()=>setLarge(v=>!v)}>{large?'On':'Off'}</button></label><label>Globe surface <button onClick={()=>setWire(v=>!v)}>{wire?'Wireframe':'Terrain'}</button></label><p>Sound is an original synthesized ambient chord. Nothing plays until you enable it. Saved discoveries stay in this browser.</p><button className="lh-pill" onClick={()=>{close();setTour(0);travel('world')}}>Take a short tour <Compass size={17}/></button></div>}
 {detail&&<div className="lh-detail"><div className="lh-detail-art"><img src={detail.id==='SP-001'?art[0]:detail.type==='Habitat'?art[2]:art[1]} alt={detail.id==='SP-001'?'Blue crab':'Illustrative collection landscape'}/><span>{detail.id==='SP-001'?'SPECIMEN 001':'COLLECTION PREVIEW'}</span></div><div className="lh-detail-copy"><p className="lh-micro">{detail.type} / {detail.id}</p><h2>{detail.name}</h2><em>{detail.latin}</em><p>{detail.desc}</p><dl><div><dt>Region</dt><dd>{detail.area}</dd></div><div><dt>Record category</dt><dd>{detail.tag}</dd></div></dl><a className="lh-pill lh-lime" href={'?entry='+detail.id}>Open full profile <ArrowUpRight size={17}/></a><button className="lh-text-link" onClick={()=>toggleSave(detail.id)}><Bookmark size={16}/>{saved.includes(detail.id)?'Saved to collection':'Save for later'}</button></div></div>}
 </div></dialog>
 {tour>=0&&<div className="lh-tour" role="region" aria-label="Guided introduction"><span className="lh-micro">YOUR FIRST TURN / {tour+1} OF 3</span><button className="lh-tour-close" aria-label="End tour" onClick={()=>setTour(-1)}><X size={17}/></button><h3>{['Start with the world.','Choose a connection.','Keep exploring.'][tour]}</h3><p>{['Drag the globe to turn it. Use the surface switch to reveal its structure.','Preview a record, bookmark it, or enter its complete Archive profile.','Switch perspectives to follow a species into its habitat and the observations around it.'][tour]}</p><button onClick={()=>{if(tour===2)setTour(-1);else{setTour(v=>v+1);travel(tour===0?'discover':'perspectives')}}}>{tour===2?'Explore on your own':'Next'} <ArrowRight size={16}/></button></div>}
 </div>;
}
