import {Suspense,lazy,useEffect,useRef,useState} from 'react';
import {ArrowUpRight,Compass,Volume2,VolumeX,X,RotateCcw,Shirt,Sun,Moon,Map,ClipboardList,Smile,HelpCircle} from 'lucide-react';
import type {ExplorerCommand,ExplorerLook} from './messenger-scene';
import './home-messenger.css';
const Scene=lazy(()=>import('./messenger-scene').then(m=>({default:m.MessengerScene})));
const places=[{name:'Archive House',role:'Archivist',link:'?entry=SP-001',color:'#dbb985'},{name:'Estuary Garden',role:'Field guide',link:'?entry=HB-001',color:'#96bb8c'},{name:'Observatory',role:'Observer',link:'?entry=AS-001',color:'#b5a9cf'},{name:'Field Outpost',role:'Outfitter',link:'?view=marketplace',color:'#d6a081'}];
const colors=['#d5ee9e','#dc997c','#91bad5','#bba4d0'];
const quests=[{item:'Species notes',from:0,to:1},{item:'Habitat observations',from:1,to:2},{item:'Monitoring brief',from:2,to:3},{item:'Field report',from:3,to:0}];
const dialogue=[['Welcome to Archive House. Every discovery starts with a question—and a record you can return to.','Our first collection follows Chesapeake Bay: species, habitats, and observations that connect them.'],['Welcome to the Estuary Garden. Follow a blue crab from its profile into the underwater grass habitat around it.','Habitats are connections, not just backdrops. Open the habitat record to follow those links.'],['The Observatory is where observations become evidence. Our collection links back to published monitoring sources.','Visit the Cambridge station record to see where its measurements come from.'],['This is the Field Outpost. The marketplace currently contains demonstration supplies and conservation tasks.','There is no checkout here. Explore how practical work might connect to the records you read.']];
export function MessengerWorld({paused}:{paused:boolean}){
 const dialog=useRef<HTMLDialogElement>(null),audio=useRef<AudioContext|null>(null),seq=useRef(0),soundRef=useRef(false);
 const [open,setOpen]=useState(false),[begun,setBegun]=useState(false),[near,setNear]=useState(-1),[talk,setTalk]=useState<number|null>(null),[line,setLine]=useState(0),[panel,setPanel]=useState<'look'|'tasks'|'emotes'|'help'|null>(null),[night,setNight]=useState(true),[sound,setSound]=useState(false),[overview,setOverview]=useState(false),[command,setCommand]=useState<ExplorerCommand|null>(null),[emote,setEmote]=useState(''),[quest,setQuest]=useState(0),[carrying,setCarrying]=useState(false),[notice,setNotice]=useState(''),[reduced,setReduced]=useState(false);
 const [presence,setPresence]=useState('Connecting…');
 const [look,setLook]=useState<ExplorerLook>(()=>{try{const s=JSON.parse(localStorage.getItem('labyrinth-explorer-v2')||'null');if(s?.look)return s.look}catch{}return {coat:colors[0],trousers:'#263e3b',boots:'#ccad77',hat:true}});soundRef.current=sound;
 const send=(kind:ExplorerCommand['kind'],index?:number)=>setCommand({id:++seq.current,kind,index});
 useEffect(()=>{const q=matchMedia('(prefers-reduced-motion: reduce)');const update=()=>setReduced(q.matches);update();q.addEventListener('change',update);return()=>{q.removeEventListener('change',update);void audio.current?.close()}},[]);
 useEffect(()=>{try{localStorage.setItem('labyrinth-explorer-v2',JSON.stringify({look}))}catch{}},[look]);
 useEffect(()=>{if(!open)return;dialog.current?.showModal();const old=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=old}},[open]);
 useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),4500);return()=>clearTimeout(t)},[notice]);
 useEffect(()=>{if(!emote)return;const t=setTimeout(()=>setEmote(''),2600);return()=>clearTimeout(t)},[emote]);
 function tone(f:number,duration=.18,volume=.025){if(!soundRef.current)return;try{const ctx=audio.current||(audio.current=new AudioContext());void ctx.resume();const o=ctx.createOscillator(),g=ctx.createGain();o.type='sine';o.frequency.value=f;o.connect(g);g.connect(ctx.destination);g.gain.setValueAtTime(.001,ctx.currentTime);g.gain.linearRampToValueAtTime(volume,ctx.currentTime+.015);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+duration);o.start();o.stop(ctx.currentTime+duration)}catch{}}
 useEffect(()=>{if(!open||!sound)return;let note=0;const t=setInterval(()=>tone([164.8,220,261.6,329.6,293.7,220,196,261.6][note++%8],1.5,.014),850);return()=>clearInterval(t)},[open,sound]);
 const speak=(i:number)=>{setTalk(i);setLine(0);setPanel(null);tone(440)};
 const close=()=>{dialog.current?.close();setOpen(false);setSound(false)};
 const travel=(i:number)=>{setOverview(false);setTalk(null);send('travel',i);setNotice('Walking to '+places[i].name+'. Use WASD to take control.')};
 const active=quests[quest],canTask=active&&talk===(carrying?active.to:active.from);
 const taskAction=()=>{if(!active)return;if(!carrying&&talk===active.from){setCarrying(true);setNotice(active.item+' collected. Find the '+places[active.to].role.toLowerCase()+'.')}else if(carrying&&talk===active.to){setQuest(v=>v+1);setCarrying(false);setNotice(quest===3?'The discovery route is complete.':active.item+' delivered.')}tone(660,.5)};
 return <><button className="lm-launch" onClick={()=>setOpen(true)}><Compass size={17}/> Step inside the world <ArrowUpRight size={16}/></button><dialog ref={dialog} className={'lm-dialog lm-v2 '+(night?'':'lm-day ')+((paused||reduced)?'lm-still':'')} aria-label="Explore the Labyrinth world" onCancel={e=>{if(talk!==null||panel){e.preventDefault();setTalk(null);setPanel(null)}else close()}} onClose={()=>setOpen(false)} onKeyDownCapture={e=>{if(talk!==null&&(e.code==='KeyE'||e.code==='Space')){e.preventDefault();e.stopPropagation();if(line===0)setLine(1);else setTalk(null);return}if(e.code==='KeyL')setPanel(v=>v==='look'?null:'look');if(e.code==='Digit1')setEmote('👋');if(e.code==='Digit2')setEmote('💚');if(e.code==='Digit3')setEmote('✨')}}>
 <div className="lm-top"><span>LABYRINTH <small>{presence}</small></span><div><button aria-label={sound?'Mute explorer sounds':'Enable explorer sounds'} onClick={()=>{soundRef.current=!sound;setSound(v=>!v);if(!sound)tone(330)}}>{sound?<Volume2/>:<VolumeX/>}</button><button aria-label={night?'Switch to daylight':'Switch to night'} onClick={()=>setNight(v=>!v)}>{night?<Sun/>:<Moon/>}</button><button aria-label="World overview" aria-pressed={overview} onClick={()=>setOverview(v=>!v)}><Map/></button><button aria-label="Close explorer" onClick={close}><X/></button></div></div>
 <div className="lm-stage">{open&&<Suspense fallback={<div className="lm-loading">Building your little world…</div>}><Scene night={night} paused={paused||reduced} look={look} overview={overview||!begun} emote={emote} onPresence={setPresence} command={command} onNear={setNear} onTalk={i=>{if(begun)speak(i)}} onStep={()=>tone(90,.055,.008)}/></Suspense>}
 {!begun?<div className="lm-entry"><p>A LITTLE WORLD OF DISCOVERY</p><h2>Find your<br/><em>way.</em></h2><button onClick={()=>{setBegun(true);setTimeout(()=>dialog.current?.querySelector('canvas')?.focus(),0);setNotice('WASD to walk · Space to jump · Drag to look around')}}>Begin exploring <ArrowUpRight size={18}/></button></div>:<>
 <nav className="lm-destinations" aria-label="World destinations">{places.map((p,i)=><button key={p.name} aria-pressed={near===i} onClick={()=>travel(i)}><span style={{background:p.color}}/>{p.name}</button>)}</nav>
 <div className="lm-game-tools"><button aria-label="Delivery tasks" aria-pressed={panel==='tasks'} onClick={()=>setPanel(v=>v==='tasks'?null:'tasks')}><ClipboardList/></button><button aria-label="Customize explorer" aria-pressed={panel==='look'} onClick={()=>setPanel(v=>v==='look'?null:'look')}><Shirt/></button><button aria-label="Emotes" aria-pressed={panel==='emotes'} onClick={()=>setPanel(v=>v==='emotes'?null:'emotes')}><Smile/></button><button aria-label="Controls and help" onClick={()=>setPanel(v=>v==='help'?null:'help')}><HelpCircle/></button></div>
 {talk!==null&&<aside className="lm-conversation" key={talk}><button className="lm-dismiss" aria-label="Close guide conversation" onClick={()=>setTalk(null)}><X size={17}/></button><span className="lm-eyebrow">{places[talk].role} · {line+1}/2</span><h3>{places[talk].name}</h3><p>{dialogue[talk][line]}</p>{line===0?<button className="lm-action" onClick={()=>{setLine(1);tone(370)}}>Continue →</button>:<a href={places[talk].link}>Open the connected record <ArrowUpRight size={16}/></a>}{canTask&&<button className="lm-action" onClick={taskAction}>{carrying?'Deliver':'Collect'} {active.item} →</button>}</aside>}
 <div className="lm-bottom"><span>{quest} / 4 DELIVERIES{carrying&&<small>Carrying {active?.item}</small>}</span><div><button onClick={()=>send('jump')}>Jump <small>Space</small></button><button disabled={near<0} onClick={()=>near>=0&&speak(near)}>{near<0?'Walk toward a guide':'Speak to '+places[near].role.toLowerCase()} <small>E</small></button></div><button aria-label="Return to starting view" onClick={()=>{send('home');setTalk(null)}}><RotateCcw size={15}/></button></div><p className="lm-help">WASD / arrows · Shift run · Space jump · Drag orbit · Scroll zoom · Click ground to walk</p>
 {panel&&<aside className="lm-custom lm-panel"><button className="lm-dismiss" aria-label="Close explorer panel" onClick={()=>setPanel(null)}><X size={17}/></button>{panel==='look'?<><h3>Your explorer</h3><p>Change your field outfit.</p>{(['coat','trousers','boots'] as const).map(part=><fieldset key={part}><legend>{part}</legend><div className="lm-swatches">{colors.map(c=><button key={c} aria-label={part+' '+c} aria-pressed={look[part]===c} style={{background:c}} onClick={()=>setLook(v=>({...v,[part]:c}))}/>)}</div></fieldset>)}<label><input type="checkbox" checked={look.hat} onChange={e=>setLook(v=>({...v,hat:e.target.checked}))}/> Field hat</label><small>Outfit saved on this device.</small></>:panel==='tasks'?<><h3>The discovery route</h3><p>Carry knowledge between four guides.</p><ol>{quests.map((q,i)=><li key={q.item} className={i===quest?'active':''}><strong>{i<quest?'✓ ':''}{q.item}</strong><span>{places[q.from].name} → {places[q.to].name}</span>{i===quest&&<button className="lm-action" onClick={()=>{travel(carrying?q.to:q.from);setPanel(null)}}>Find the {places[carrying?q.to:q.from].role.toLowerCase()} →</button>}</li>)}</ol><small>Fictional learning route; session progress.</small></>:panel==='emotes'?<><h3>Express yourself</h3><div className="lm-emotes">{['👋','💚','✨','🌱','🔎','🎉'].map(v=><button key={v} aria-label={'Show '+v} onClick={()=>{setEmote(v);tone(520);setPanel(null)}}>{v}</button>)}</div><small>Reactions appear above your explorer in the shared preview.</small></>:<><h3>Make your way</h3><p>Walk freely around the little planet, or select a destination for a guided walk.</p><dl><dt>Walk / run</dt><dd>WASD, arrows / Shift</dd><dt>Jump / Talk</dt><dd>Space / E near a guide</dd><dt>Camera</dt><dd>Drag to orbit · scroll to zoom</dd><dt>Outfit / emote</dt><dd>L / 1, 2, 3</dd></dl><small>Illustrated world; not a geographic model. The guides are fictional characters. Shared presence connects preview sessions on this server. Public multiplayer hosting is not configured.</small></>}</aside>}
 {emote&&<div className="lm-emote" role="status">{emote}</div>}</>}{notice&&<div className="lm-notice" role="status">{notice}</div>}</div></dialog></>
}
