import {useEffect,useRef} from 'react';
import * as T from 'three';
type Props={progress:number;paused:boolean;wire:boolean;reset:number;onSelect:(n:number)=>void};
export default function IglooScene(props:Props){
 const host=useRef<HTMLDivElement>(null),live=useRef(props);live.current=props;
 useEffect(()=>{const el=host.current!;let renderer:T.WebGLRenderer;try{renderer=new T.WebGLRenderer({antialias:true,alpha:false})}catch{el.textContent='Use the record links to explore these connections.';return}
 renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setClearColor('#080d10');renderer.outputColorSpace=T.SRGBColorSpace;el.appendChild(renderer.domElement);renderer.domElement.setAttribute('aria-label','Rotatable three-dimensional archive structure');renderer.domElement.tabIndex=0;
 const scene=new T.Scene();scene.fog=new T.FogExp2('#080d10',.032);const camera=new T.PerspectiveCamera(40,1,.1,100);camera.position.set(0,3,13);
 scene.add(new T.HemisphereLight('#b5e0ed','#15231e',2));const light=new T.DirectionalLight('#ddf8ff',4);light.position.set(-4,8,5);scene.add(light);const rim=new T.PointLight('#a9e6c0',30,25);rim.position.set(5,1,-2);scene.add(rim);
 const structure=new T.Group();scene.add(structure);const pieces:{mesh:T.Mesh;line:T.LineSegments;base:T.Vector3}[]=[];
 const baseGeo=new T.IcosahedronGeometry(2.45,1).toNonIndexed();const positions=baseGeo.getAttribute('position');
 for(let n=0;n<positions.count;n+=3){const a=new T.Vector3().fromBufferAttribute(positions,n),b=new T.Vector3().fromBufferAttribute(positions,n+1),c=new T.Vector3().fromBufferAttribute(positions,n+2),center=a.clone().add(b).add(c).divideScalar(3);const geo=new T.BufferGeometry().setFromPoints([a.sub(center).multiplyScalar(.965),b.sub(center).multiplyScalar(.965),c.sub(center).multiplyScalar(.965)]);geo.computeVertexNormals();const mesh=new T.Mesh(geo,new T.MeshPhysicalMaterial({color:n%9===0?'#a1b4b6':'#415761',metalness:.65,roughness:.24,clearcoat:.8,side:T.DoubleSide}));mesh.position.copy(center);structure.add(mesh);const line=new T.LineSegments(new T.EdgesGeometry(geo),new T.LineBasicMaterial({color:'#b8e4d4',transparent:true,opacity:.3}));mesh.add(line);pieces.push({mesh,line,base:center})}baseGeo.dispose();
 const core=new T.Mesh(new T.IcosahedronGeometry(.85,1),new T.MeshBasicMaterial({color:'#c1ebbe',wireframe:true,transparent:true,opacity:.8}));structure.add(core);
 const floorGeo=new T.PlaneGeometry(100,100,90,90);floorGeo.rotateX(-Math.PI/2);const fp=floorGeo.attributes.position;for(let i=0;i<fp.count;i++){const x=fp.getX(i),z=fp.getZ(i);fp.setY(i,-3.6+Math.sin(x*.27)*Math.cos(z*.23)*.65+Math.sin(x*.8+z*.6)*.12)}floorGeo.computeVertexNormals();scene.add(new T.Mesh(floorGeo,new T.MeshStandardMaterial({color:'#18242a',roughness:.95,metalness:.3})));
 const grid=new T.GridHelper(70,70,'#3c5559','#22373d');grid.position.y=-3.25;scene.add(grid);
 const dustGeo=new T.BufferGeometry(),dustData=new Float32Array(420*3);for(let i=0;i<420;i++){dustData[i*3]=Math.sin(i*127.1)*22;dustData[i*3+1]=Math.cos(i*71.7)*10;dustData[i*3+2]=Math.sin(i*39.3)*18}dustGeo.setAttribute('position',new T.BufferAttribute(dustData,3));const dust=new T.Points(dustGeo,new T.PointsMaterial({color:'#badbd8',size:.025,transparent:true,opacity:.6}));scene.add(dust);
 const nodes=[new T.Vector3(-4,.5,0),new T.Vector3(3.6,1.8,-1),new T.Vector3(2,-2,1.5)].map((pos,i)=>{const mesh=new T.Mesh(new T.IcosahedronGeometry(.19,1),new T.MeshBasicMaterial({color:['#c8e6a5','#88ccdf','#e0c5a0'][i]}));mesh.position.copy(pos);mesh.userData.record=i;structure.add(mesh);const line=new T.Line(new T.BufferGeometry().setFromPoints([new T.Vector3(),pos]),new T.LineBasicMaterial({color:'#8db9b9',transparent:true,opacity:.4}));structure.add(line);return {mesh,line,pos}});
 const ray=new T.Raycaster(),pointer=new T.Vector2();let dragging=false,lastX=0,lastY=0,moved=0,yaw=0,pitch=0,targetYaw=0,targetPitch=0,lastReset=live.current.reset;
 const down=(e:PointerEvent)=>{dragging=true;lastX=e.clientX;lastY=e.clientY;moved=0;renderer.domElement.setPointerCapture(e.pointerId)};
 const move=(e:PointerEvent)=>{if(!dragging)return;const dx=e.clientX-lastX,dy=e.clientY-lastY;moved+=Math.abs(dx)+Math.abs(dy);targetYaw+=dx*.006;targetPitch=T.MathUtils.clamp(targetPitch+dy*.004,-.65,.65);lastX=e.clientX;lastY=e.clientY};
 const up=(e:PointerEvent)=>{dragging=false;if(moved>7)return;const rect=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(nodes.map(n=>n.mesh))[0];if(hit)live.current.onSelect(hit.object.userData.record)};
 const key=(e:KeyboardEvent)=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();targetYaw+=e.key==='ArrowLeft'?-.18:e.key==='ArrowRight'?.18:0;targetPitch=T.MathUtils.clamp(targetPitch+(e.key==='ArrowUp'?-.1:e.key==='ArrowDown'?.1:0),-.65,.65)}};
 const canvas=renderer.domElement;canvas.addEventListener('pointerdown',down);canvas.addEventListener('pointermove',move);canvas.addEventListener('pointerup',up);canvas.addEventListener('pointercancel',()=>{dragging=false});canvas.addEventListener('keydown',key);
 const resize=()=>{const w=el.clientWidth,h=el.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix()};const observer=new ResizeObserver(resize);observer.observe(el);resize();let frame=0,time=0,smooth=live.current.progress;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;let visible=true;const io=new IntersectionObserver(([e])=>{visible=e.isIntersecting});io.observe(el);
 const draw=()=>{frame=requestAnimationFrame(draw);if(!visible)return;const p=live.current;if(lastReset!==p.reset){targetYaw=0;targetPitch=0;lastReset=p.reset}if(!p.paused&&!reduced)time+=.004;smooth+=(p.progress-smooth)*(reduced?1:.065);yaw+=(targetYaw-yaw)*.09;pitch+=(targetPitch-pitch)*.09;structure.rotation.set(pitch,yaw+Math.sin(time*.4)*.08,0);const explode=T.MathUtils.smoothstep(smooth,.2,.85);for(const piece of pieces){piece.mesh.position.copy(piece.base).multiplyScalar(1+explode*.9);const mat=piece.mesh.material as T.MeshPhysicalMaterial;mat.wireframe=p.wire;piece.line.visible=!p.wire;(piece.line.material as T.LineBasicMaterial).opacity=.25+explode*.55}nodes.forEach(n=>{n.mesh.scale.setScalar(.8+explode*1.4);n.line.visible=explode>.2});core.rotation.y=time*.4;dust.rotation.y=time*.015;camera.position.set(Math.sin(smooth*.7)*1.5,2.1+smooth*1.5,12+smooth*4);camera.lookAt(0,-.25,0);renderer.render(scene,camera)};draw();
 return()=>{cancelAnimationFrame(frame);observer.disconnect();io.disconnect();canvas.removeEventListener('pointerdown',down);canvas.removeEventListener('pointermove',move);canvas.removeEventListener('pointerup',up);canvas.removeEventListener('keydown',key);scene.traverse(o=>{const m=o as T.Mesh;if(m.geometry)m.geometry.dispose();if(m.material)(Array.isArray(m.material)?m.material:[m.material]).forEach(v=>v.dispose())});renderer.dispose();canvas.remove()};
 },[]);return <div ref={host} className="li-canvas"/>;
}
