import {useEffect,useRef,useState} from 'react';
import * as T from 'three';

export type ExplorerLook={coat:string;trousers:string;boots:string;hat:boolean};
export type ExplorerCommand={id:number;kind:'travel'|'home'|'jump'|'emote';index?:number};
export const places=[{name:'Archive House',role:'Archivist',link:'?entry=SP-001',color:'#dbb985'}, {name:'Estuary Garden',role:'Field guide',link:'?entry=HB-001',color:'#96bb8c'}, {name:'Observatory',role:'Observer',link:'?entry=AS-001',color:'#b5a9cf'}, {name:'Field Outpost',role:'Outfitter',link:'?view=marketplace',color:'#d6a081'}];
const R=22,up=new T.Vector3(0,1,0);
const normals=[new T.Vector3(-.30,.94,-.12),new T.Vector3(.5,.82,-.27),new T.Vector3(.12,.77,-.63),new T.Vector3(-.62,.72,-.31)].map(n=>n.normalize());
export function MessengerScene({night,paused,look,command,overview,emote,onPresence,onNear,onTalk,onStep}:{night:boolean;paused:boolean;look:ExplorerLook;command:ExplorerCommand|null;overview:boolean;emote:string;onPresence:(s:string)=>void;onNear:(n:number)=>void;onTalk:(n:number)=>void;onStep:()=>void}){
 const host=useRef<HTMLDivElement>(null),live=useRef({night,paused,look,command,overview,emote,onPresence,onNear,onTalk,onStep});live.current={night,paused,look,command,overview,emote,onPresence,onNear,onTalk,onStep};const [failure,setFailure]=useState(false);
 useEffect(()=>{const el=host.current;if(!el)return;let renderer:T.WebGLRenderer;try{renderer=new T.WebGLRenderer({antialias:true,alpha:false,powerPreference:'high-performance'})}catch{setFailure(true);return}
 renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFShadowMap;renderer.outputColorSpace=T.SRGBColorSpace;el.appendChild(renderer.domElement);renderer.domElement.tabIndex=0;renderer.domElement.setAttribute('aria-label','3D field explorer. WASD or arrow keys to walk, Shift to run, Space to jump, E to talk. Drag to orbit; scroll to zoom.');
 const scene=new T.Scene(),camera=new T.PerspectiveCamera(48,1,.1,200);scene.background=new T.Color('#122f30');scene.fog=new T.Fog('#122f30',55,110);
 const hemi=new T.HemisphereLight('#c9edd5','#18302c',2.4);scene.add(hemi);const sun=new T.DirectionalLight('#ffddac',3);sun.position.set(-25,45,30);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-35;sun.shadow.camera.right=35;sun.shadow.camera.top=35;sun.shadow.camera.bottom=-35;sun.shadow.bias=-.001;scene.add(sun);
 const geometries:T.BufferGeometry[]=[],materials:T.Material[]=[],textures:T.Texture[]=[];const mat=(c:string)=>{const m=new T.MeshToonMaterial({color:c});materials.push(m);return m};const grass=mat('#607f59'),stone=mat('#c3c4a0'),wood=mat('#665847'),dark=mat('#24443f'),cream=mat('#e7dfbf'),water=mat('#408984');
 function mesh(g:T.BufferGeometry,m:T.Material,parent:T.Object3D,x=0,y=0,z=0){geometries.push(g);const o=new T.Mesh(g,m);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o}
 const ink=new T.LineBasicMaterial({color:'#173c34',transparent:true,opacity:.45});materials.push(ink);
 function box(p:T.Object3D,w:number,h:number,d:number,m:T.Material,x=0,y=0,z=0){const b=mesh(new T.BoxGeometry(w,h,d),m,p,x,y,z);if(w>.6&&h>.6){const edges=new T.EdgesGeometry(b.geometry);geometries.push(edges);b.add(new T.LineSegments(edges,ink))}return b}
 function anchor(n:T.Vector3){const g=new T.Group();g.position.copy(n).multiplyScalar(R);g.quaternion.setFromUnitVectors(up,n);scene.add(g);return g}
 mesh(new T.IcosahedronGeometry(R,5),grass,scene);const ocean=mesh(new T.SphereGeometry(R-.16,64,32),water,scene);ocean.receiveShadow=true;
 function label(text:string,p:T.Object3D,y:number){const c=document.createElement('canvas');c.width=512;c.height=96;const ctx=c.getContext('2d')!;ctx.fillStyle='#122d27dd';ctx.fillRect(0,0,512,96);ctx.font='bold 32px monospace';ctx.textAlign='center';ctx.fillStyle='#eef0d8';ctx.fillText(text,256,60);const tex=new T.CanvasTexture(c);textures.push(tex);const material=new T.SpriteMaterial({map:tex,depthTest:true});materials.push(material);const sprite=new T.Sprite(material);sprite.position.y=y;sprite.scale.set(4.5,.84,1);p.add(sprite);return sprite}
 function character(parent:T.Object3D,c:string){const group=new T.Group();parent.add(group);const coat=mat(c),pants=mat('#263e3b'),boot=mat('#ccad77'),skin=mat('#d9b598');box(group,.68,.86,.42,coat,0,1.18);mesh(new T.SphereGeometry(.27,12,10),skin,group,0,1.98);for(const x of [-.09,.09])mesh(new T.SphereGeometry(.025,6,4),dark,group,x,2,-.247);box(group,.08,.065,.07,skin,0,1.93,-.27);mesh(new T.SphereGeometry(.277,12,8,0,Math.PI*2,0,Math.PI*.43),wood,group,0,1.99);for(const x of [-.22,.22])box(group,.06,.74,.07,wood,x,1.25,-.24);const hat=box(group,.76,.09,.68,coat,0,2.23);box(hat,.47,.2,.43,coat,0,.13);box(group,.43,.6,.25,wood,0,1.3,.32);const limbs:T.Group[]=[];for(const x of [-.21,.21]){const leg=new T.Group();leg.position.set(x,.81,0);group.add(leg);box(leg,.23,.62,.25,pants,0,-.28);box(leg,.29,.18,.43,boot,0,-.6,-.07);limbs.push(leg)}for(const x of [-.48,.48]){const arm=new T.Group();arm.position.set(x,1.5,0);group.add(arm);box(arm,.2,.6,.23,coat,0,-.27);mesh(new T.SphereGeometry(.115,8,6),skin,arm,0,-.61);limbs.push(arm)}return {group,coat,pants,boot,hat,limbs}}
 const blockers:{n:T.Vector3;radius:number}[]=[];const npcs:T.Group[]=[];
 normals.forEach((n,i)=>{const g=anchor(n);mesh(new T.CylinderGeometry(4.6,4.9,.3,12),stone,g,0,.05);const wall=mat(places[i].color);if(i===0){box(g,4,3.6,3.3,wall,0,1.95);const roof=mesh(new T.ConeGeometry(3.4,1.5,4),wood,g,0,4.4);roof.rotation.y=Math.PI/4;box(g,.95,2,.1,dark,0,1.15,1.7);for(const x of [-1.25,1.25]){box(g,.72,.95,.1,cream,x,2.5,1.72);box(g,.07,.95,.15,wood,x,2.5,1.8)}for(let j=0;j<3;j++)box(g,1.5,.17,1.1,stone,0,.12+j*.12,2.4-j*.3)}
 else if(i===1){mesh(new T.CylinderGeometry(2,2,.45,24),wood,g,0,.3);mesh(new T.CylinderGeometry(1.85,1.85,.1,24),water,g,0,.57);for(let j=0;j<14;j++){const a=j*2.4;box(g,.07,.8+(j%3)*.3,.07,grass,Math.cos(a)*1.5,1,Math.sin(a)*1.5)}box(g,3,.3,.65,wood,0,.5,3)}
 else if(i===2){mesh(new T.CylinderGeometry(2.2,2.2,2.8,12),wall,g,0,1.5);mesh(new T.SphereGeometry(2.2,16,12,0,Math.PI*2,0,Math.PI/2),cream,g,0,2.9);const tube=mesh(new T.CylinderGeometry(.4,.55,3,12),dark,g,.6,4.1,1.5);tube.rotation.x=Math.PI/3;box(g,.9,1.9,.1,wood,0,1.05,2.21)}else{box(g,3.7,2.6,3,wall,0,1.45);mesh(new T.ConeGeometry(3,2,4),cream,g,0,3.3).rotation.y=Math.PI/4;for(let j=0;j<3;j++)box(g,.8,.8,.8,wood,-2.5,.5,j-1);box(g,1.2,1.9,.12,dark,0,1.1,1.51)}
 label(places[i].name.toUpperCase(),g,6.4);const npc=new T.Group();npc.userData.guide=i;npc.position.set(2.8,.22,2.5);g.add(npc);character(npc,places[i].color);label('•••',npc,2.9).scale.set(1,.45,1);npcs.push(npc);blockers.push({n,radius:i===1?2.3:2.7});
 for(let j=0;j<5;j++){const a=j*Math.PI*2/5;const post=new T.Group();post.position.set(Math.sin(a)*4,.2,Math.cos(a)*4);g.add(post);box(post,.1,2.1,.1,wood,0,1);box(post,.35,.35,.35,cream,0,2.15)}
 });
 // Hand-built little-world scenery, with deterministic placement for repeatable routes.
 for(let i=0;i<125;i++){const a=i*2.399963,n=new T.Vector3(Math.cos(a)*Math.sqrt(1-((i+.5)/125*2-1)**2),(i+.5)/125*2-1,Math.sin(a)*Math.sqrt(1-((i+.5)/125*2-1)**2));if(normals.some(p=>p.angleTo(n)*R<6)||n.angleTo(up)*R<3.5)continue;const g=anchor(n);if(i%4===0){mesh(new T.DodecahedronGeometry(.5+(i%3)*.2),stone,g,0,.35)}else{const height=1.5+i%4*.35;mesh(new T.CylinderGeometry(.11,.18,height,6),wood,g,0,height/2);mesh(new T.ConeGeometry(.8,height*1.1,7),i%2?grass:mat('#84956a'),g,0,height+.2);mesh(new T.ConeGeometry(.6,height*.9,7),grass,g,0,height*1.5)} }
 // Trails curve over the spherical surface instead of cutting through it.
 normals.forEach(n=>{for(let i=0;i<40;i++){const v=up.clone().lerp(n,i/40).normalize();const g=anchor(v);mesh(new T.CylinderGeometry(.24,.24,.035,6),stone,g,0,.03)}});
 const collisionObjects:T.Object3D[]=[];scene.traverse(o=>{if(o instanceof T.Mesh&&o.geometry.type==='BoxGeometry')collisionObjects.push(o)});
 const playerAnchor=anchor(up),player=character(playerAnchor,look.coat);playerAnchor.position.copy(up).multiplyScalar(R);const dust=new T.Group();scene.add(dust);for(let i=0;i<90;i++){const m=mesh(new T.OctahedronGeometry(.035+(i%3)*.02),cream,dust,Math.sin(i*17)*35,Math.cos(i*11)*35,Math.cos(i*3)*35);m.castShadow=false}
 const ghosts=new Map<string,{anchor:T.Group;avatar:ReturnType<typeof character>;mark:T.Sprite;emote:string;target:T.Vector3;jump:number;walking:boolean}>();
 let socket:WebSocket|null=null,self='',lastBroadcast=0;
 if(import.meta.env.DEV){socket=new WebSocket((location.protocol==='https:'?'wss://':'ws://')+location.host+'/explorer-presence');socket.onopen=()=>live.current.onPresence('Connected · preview world');socket.onerror=()=>live.current.onPresence('Solo · presence unavailable');socket.onclose=()=>live.current.onPresence('Solo · disconnected');socket.onmessage=e=>{try{const packet=JSON.parse(e.data);if(packet.you)self=packet.you;if(!Array.isArray(packet.peers))return;const ids=new Set<string>();for(const p of packet.peers){if(p.id===self)continue;ids.add(p.id);let ghost=ghosts.get(p.id);if(!ghost){const a=anchor(new T.Vector3(...p.n));ghost={anchor:a,avatar:character(a,p.look.coat),mark:label('EXPLORER',a,3.1),emote:'',target:new T.Vector3(...p.n),jump:0,walking:false};ghosts.set(p.id,ghost)}ghost.target.set(...p.n as [number,number,number]);ghost.jump=p.jump||0;ghost.walking=!!p.walking;ghost.avatar.group.rotation.y=p.yaw;ghost.avatar.coat.color.set(p.look.coat);ghost.avatar.pants.color.set(p.look.trousers);ghost.avatar.boot.color.set(p.look.boots);ghost.avatar.hat.visible=p.look.hat;if(ghost.emote!==p.emote){ghost.mark.material.map?.dispose();ghost.mark.material.dispose();ghost.anchor.remove(ghost.mark);ghost.mark=label(p.emote||'EXPLORER',ghost.anchor,3.1);ghost.emote=p.emote}}for(const [id,g] of ghosts)if(!ids.has(id)){scene.remove(g.anchor);ghosts.delete(id)}live.current.onPresence((ids.size+1)+' explorer'+(ids.size?'s':'')+' · preview world')}catch{}}}else live.current.onPresence('Solo · shared server not configured');
 const keys=new Set<string>(),normal=up.clone();let yaw=0,pitch=.55,distance=8,jump=0,velocity=0,walk=0,last=0,frame=0,lastCmd=-1,near=-1,nearSent=-2,autopilot:T.Vector3|null=null,lastStep=0;let pointer:{x:number;y:number;startX:number;startY:number}|null=null;const ray=new T.Raycaster(),mouse=new T.Vector2();
 const keydown=(e:KeyboardEvent)=>{if(['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Space'].includes(e.code)){e.preventDefault();keys.add(e.code);autopilot=null}if(e.code==='Space'&&jump===0)velocity=5;if(e.code==='KeyE'&&near>=0)live.current.onTalk(near)};const keyup=(e:KeyboardEvent)=>keys.delete(e.code);const blur=()=>keys.clear();const down=(e:PointerEvent)=>{renderer.domElement.focus();renderer.domElement.setPointerCapture(e.pointerId);pointer={x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY}};const move=(e:PointerEvent)=>{if(pointer){yaw-=(e.clientX-pointer.x)*.007;pitch=T.MathUtils.clamp(pitch+(e.clientY-pointer.y)*.006,.15,1.3);pointer.x=e.clientX;pointer.y=e.clientY}};const release=(e:PointerEvent)=>{if(pointer&&Math.hypot(e.clientX-pointer.startX,e.clientY-pointer.startY)<5){const b=renderer.domElement.getBoundingClientRect();mouse.set((e.clientX-b.left)/b.width*2-1,-(e.clientY-b.top)/b.height*2+1);ray.setFromCamera(mouse,camera);const personHit=ray.intersectObjects(npcs,true)[0];if(personHit){let node:T.Object3D|null=personHit.object;while(node&&node.userData.guide===undefined)node=node.parent;if(node&&node.userData.guide===near){live.current.onTalk(near);pointer=null;return}}const planet=ray.intersectObjects(scene.children,false).find(h=>h.object instanceof T.Mesh&&h.object.geometry.type==='IcosahedronGeometry');if(planet)autopilot=planet.point.clone().normalize()}pointer=null};const wheel=(e:WheelEvent)=>{e.preventDefault();distance=T.MathUtils.clamp(distance+e.deltaY*.008,4,18)};
 const canvas=renderer.domElement;canvas.addEventListener('keydown',keydown);canvas.addEventListener('keyup',keyup);canvas.addEventListener('blur',blur);canvas.addEventListener('pointerdown',down);canvas.addEventListener('pointermove',move);canvas.addEventListener('pointerup',release);canvas.addEventListener('pointercancel',()=>pointer=null);canvas.addEventListener('wheel',wheel,{passive:false});
 const resize=()=>{const {width,height}=el.getBoundingClientRect();renderer.setSize(width,height,false);camera.aspect=width/Math.max(height,1);camera.updateProjectionMatrix()};const ro=new ResizeObserver(resize);ro.observe(el);resize();camera.position.set(0,31,10);camera.lookAt(0,R+1,0);
 function render(t:number){const dt=Math.min((t-last)/1000||0,.045);last=t;const p=live.current;player.coat.color.set(p.look.coat);player.pants.color.set(p.look.trousers);player.boot.color.set(p.look.boots);player.hat.visible=p.look.hat;hemi.intensity=p.night?1.6:2.8;sun.intensity=p.night?1.6:3.2;const bg=p.night?'#122f30':'#80b4af';scene.background=new T.Color(bg);(scene.fog as T.Fog).color.set(bg);
 if(p.command&&p.command.id!==lastCmd){lastCmd=p.command.id;if(p.command.kind==='travel'){const n=normals[p.command.index||0];autopilot=n.clone().lerp(up,.24).normalize()}if(p.command.kind==='home'){normal.copy(up);autopilot=null;yaw=0}if(p.command.kind==='jump'&&jump===0)velocity=5}
 const forward=new T.Vector3(0,0,-1).projectOnPlane(normal).normalize();if(forward.lengthSq()<.1)forward.set(1,0,0).projectOnPlane(normal).normalize();forward.applyAxisAngle(normal,yaw);const right=new T.Vector3().crossVectors(forward,normal).normalize();const direction=new T.Vector3();if(keys.has('KeyW')||keys.has('ArrowUp'))direction.add(forward);if(keys.has('KeyS')||keys.has('ArrowDown'))direction.sub(forward);if(keys.has('KeyD')||keys.has('ArrowRight'))direction.add(right);if(keys.has('KeyA')||keys.has('ArrowLeft'))direction.sub(right);if(autopilot){if(normal.angleTo(autopilot)*R<.35)autopilot=null;else direction.copy(autopilot).projectOnPlane(normal)}const walking=direction.lengthSq()>.0001;if(walking){direction.normalize();const speed=keys.has('ShiftLeft')?6:3.3;const candidate=normal.clone().addScaledVector(direction,speed*dt/R).normalize();if(!blockers.some(b=>b.n.angleTo(candidate)*R<b.radius)&&!p.overview)normal.copy(candidate);else if(autopilot)autopilot=null;walk+=dt*9;if(t-lastStep>350){p.onStep();lastStep=t}}
 velocity-=12*dt;jump=Math.max(0,jump+velocity*dt);if(jump===0)velocity=0;playerAnchor.position.copy(normal).multiplyScalar(R+jump+.12);playerAnchor.quaternion.setFromUnitVectors(up,normal);if(walking){const local=direction.clone().applyQuaternion(playerAnchor.quaternion.clone().invert());player.group.rotation.y=Math.atan2(-local.x,-local.z)}player.limbs.forEach((limb,i)=>limb.rotation.x=walking?Math.sin(walk+(i%2)*Math.PI)*.55:0);player.group.position.y=walking&&!p.paused?Math.abs(Math.sin(walk))*.045:0;
 near=-1;let best=6.4;normals.forEach((n,i)=>{const d=n.angleTo(normal)*R;if(d<best){best=d;near=i}});if(near!==nearSent){nearSent=near;p.onNear(near)}
 if(socket?.readyState===WebSocket.OPEN&&t-lastBroadcast>100){lastBroadcast=t;socket.send(JSON.stringify({n:normal.toArray(),yaw:player.group.rotation.y,jump,walking,look:p.look,emote:p.emote}))}for(const g of ghosts.values()){const dest=g.target.clone().multiplyScalar(R+.12+g.jump);g.anchor.position.lerp(dest,Math.min(1,dt*12));g.anchor.quaternion.setFromUnitVectors(up,g.anchor.position.clone().normalize());g.avatar.limbs.forEach((limb,i)=>limb.rotation.x=g.walking?Math.sin(t*.009+i%2*Math.PI)*.55:0)}
 const desired=p.overview?normal.clone().multiplyScalar(54).addScaledVector(forward,-18):normal.clone().multiplyScalar(R+2+distance*Math.sin(pitch)).addScaledVector(forward,-distance*Math.cos(pitch));const focal=normal.clone().multiplyScalar(R+1.4);if(!p.overview){const delta=desired.clone().sub(focal);ray.set(focal,delta.clone().normalize());ray.far=delta.length();const obstruction=ray.intersectObjects(collisionObjects,false)[0];ray.far=Infinity;if(obstruction)desired.copy(focal).addScaledVector(delta.normalize(),Math.max(2,obstruction.distance-.7)).addScaledVector(normal,1.8)}camera.position.lerp(desired,p.paused?1:1-Math.exp(-dt*5));camera.up.copy(normal);camera.lookAt(normal.clone().multiplyScalar(R+1.4));if(!p.paused)dust.rotation.y+=dt*.008;renderer.render(scene,camera);frame=requestAnimationFrame(render)}frame=requestAnimationFrame(render);
 return()=>{if(socket){socket.onclose=null;socket.close()}cancelAnimationFrame(frame);ro.disconnect();canvas.removeEventListener('keydown',keydown);canvas.removeEventListener('keyup',keyup);canvas.removeEventListener('blur',blur);canvas.removeEventListener('pointerdown',down);canvas.removeEventListener('pointermove',move);canvas.removeEventListener('pointerup',release);canvas.removeEventListener('wheel',wheel);geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());textures.forEach(t=>t.dispose());renderer.dispose();canvas.remove()};
 },[]);
 return <div className="lm-webgl" ref={host}>{failure&&<p className="lm-render-error">3D rendering is unavailable in this browser. You can still use the destination links to explore the Archive.</p>}</div>
}
