"use client";
import {useEffect,useMemo,useRef,useState} from 'react';
import {Plus,Minus,RotateCcw,Move,Layers,Activity,Undo2,Trash2} from 'lucide-react';
import {Slider} from '@/components/ui/slider';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {type BayRecord} from './chesapeake-data';
import grid from './chesapeake-elevation.json';
import {MapActivityControls,mappedPhases,drawActivities,activityWindow,monthNames,type ActivitySelection,type ActivityHit} from './map-activity';
import {formatMetric} from '../lib/conservation-types';
import {sampleElevation,pathDistance,areaMeters,isCrossed,profileSamples,type GeoPoint} from './terrain-math';

type ScreenPoint={x:number;y:number;depth:number;lon:number;lat:number;z:number};
type Face={p:ScreenPoint[];color:string;depth:number};
function Choice({label,value,set,options}:{label:string;value:string;set:(v:string)=>void;options:string[]}){return <Select value={value} onValueChange={set}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{options.map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select>}

export default function TerrainMap({selected,onSelect,records,activity,onActivityChange,onOpenCalendar}:{selected:string|null;onSelect:(r:BayRecord)=>void;records:BayRecord[];activity:ActivitySelection;onActivityChange:(s:ActivitySelection)=>void;onOpenCalendar:()=>void}){
 const ref=useRef<HTMLCanvasElement>(null),faces=useRef<Face[]>([]),hits=useRef<{x:number;y:number;r:BayRecord}[]>([]);
 const activityHits=useRef<ActivityHit[]>([]);const [showActivity,setShowActivity]=useState(true),[phaseId,setPhaseId]=useState('');const phases=mappedPhases(activity),highlight=phases.find(p=>p.id===phaseId)?.id||phases[0]?.id||'';
 const drag=useRef<{x:number;y:number;startX:number;startY:number;moved:boolean}|null>(null);
 const [angle,setAngle]=useState(-.22),[tilt,setTilt]=useState(.85),[zoom,setZoom]=useState(1),[exaggeration,setExaggeration]=useState(150);
 const [layer,setLayer]=useState('All'),[year,setYear]=useState(new Date().getUTCFullYear()),[mode,setMode]=useState('Explore'),[units,setUnits]=useState('Metric');
 const [surface,setSurface]=useState('Land + seafloor'),[center,setCenter]=useState([-76.5,38.725]),[points,setPoints]=useState<GeoPoint[]>([]);
 const [probe,setProbe]=useState<(GeoPoint&{elevation:number|null})|null>(null),[notice,setNotice]=useState('');
 const [inputLat,setInputLat]=useState('38.50'),[inputLon,setInputLon]=useState('-76.40');
 const active=records.find(r=>r.id===selected),imperial=units==='Imperial';
 const heightText=(z:number)=>`${(z*(imperial?3.28084:1)).toFixed(1)} ${imperial?'ft':'m'}`;
 const distanceText=(d:number)=>`${(d/(imperial?1609.344:1000)).toFixed(2)} ${imperial?'mi':'km'}`;
 const areaText=(a:number)=>`${(a/(imperial?2589988.110336:1000000)).toFixed(2)} ${imperial?'mi²':'km²'}`;
 useEffect(()=>{if(active?.type==='Species'){onActivityChange({...activity,speciesId:active.id});setCenter([-76.5,38.725]);setZoom(1);setLayer('All')}else if(active){setCenter([active.lon,active.lat]);setZoom(2.1);setLayer('All')}else{setCenter([-76.5,38.725]);setZoom(1)}},[selected]);
 const profile=useMemo(()=>profileSamples(grid,points),[points]);
 const crossed=mode==='Area'&&isCrossed(points);
 const elevations=profile.map(p=>p.elevation).filter((v):v is number=>v!==null);
 const min=elevations.length?Math.min(...elevations):0,max=elevations.length?Math.max(...elevations):0;
 const total=pathDistance(points);
 useEffect(()=>{
  const canvas=ref.current;if(!canvas)return;
  const draw=()=>{
   const w=canvas.clientWidth,h=canvas.clientHeight,dpr=window.devicePixelRatio||1;
   canvas.width=w*dpr;canvas.height=h*dpr;const c=canvas.getContext('2d');if(!c)return;c.scale(dpr,dpr);
   c.fillStyle='#0d2024';c.fillRect(0,0,w,h);
   const scale=Math.min(w/1.72,h/1.85)*zoom;
   const project=(lon:number,lat:number,z:number):ScreenPoint=>{const x=(lon-center[0])*.78,y=center[1]-lat;const a=x*Math.cos(angle)-y*Math.sin(angle),b=x*Math.sin(angle)+y*Math.cos(angle),v=z*exaggeration/111195;const depth=b*Math.cos(tilt)+v*Math.sin(tilt);return {x:w/2+a*scale,y:h*.52+(b*Math.sin(tilt)-v*Math.cos(tilt))*scale,depth,lon,lat,z}};
   const pointAt=(i:number,j:number)=>{const z=grid.values[j*grid.width+i];if(z===null)return null;return project(grid.bounds[0]+(i+.5)/grid.width*(grid.bounds[2]-grid.bounds[0]),grid.bounds[3]-(j+.5)/grid.height*(grid.bounds[3]-grid.bounds[1]),z)};
   const color=(z:number,slope:number)=>z<0?`hsl(${185+Math.min(-z,40)*.5} 50% ${Math.max(15,44+z*.65)+slope}%)`:`hsl(${110-Math.min(z,220)*.22} ${Math.max(18,38-z*.07)}% ${Math.min(61,28+z*.14)+slope}%)`;
   const mesh:Face[]=[];const step=zoom>2?1:2;
   for(let j=0;j<grid.height-1;j+=step)for(let i=0;i<grid.width-1;i+=step){const i2=Math.min(i+step,grid.width-1),j2=Math.min(j+step,grid.height-1),corners=[pointAt(i,j),pointAt(i2,j),pointAt(i2,j2),pointAt(i,j2)];if(corners.some(p=>!p))continue;const pp=corners as ScreenPoint[];for(const indexes of [[0,1,2],[0,2,3]]){const p=indexes.map(k=>pp[k]);if(p.every(v=>v.x<0)||p.every(v=>v.x>w)||p.every(v=>v.y<0)||p.every(v=>v.y>h))continue;const z=p.reduce((s,v)=>s+v.z,0)/3;if(surface==='Seafloor only'&&z>=0)continue;const shade=Math.max(-7,Math.min(7,(p[0].z-p[2].z)*.25));mesh.push({p,color:color(z,shade),depth:p.reduce((s,v)=>s+v.depth,0)/3})}}
   mesh.sort((a,b)=>a.depth-b.depth);faces.current=mesh;
   for(const f of mesh){c.beginPath();f.p.forEach((p,i)=>i?c.lineTo(p.x,p.y):c.moveTo(p.x,p.y));c.closePath();c.fillStyle=f.color;c.fill();c.strokeStyle=f.color;c.lineWidth=.45;c.stroke()}
   // Zero contour marks the model reference; not a surveyed shoreline or tide.
   c.strokeStyle='#cfebc0';c.lineWidth=.7;c.beginPath();for(const f of mesh){const intersections:ScreenPoint[]=[];for(let k=0;k<3;k++){const a=f.p[k],b=f.p[(k+1)%3];if((a.z<0)===(b.z<0))continue;const t=-a.z/(b.z-a.z);intersections.push(project(a.lon+(b.lon-a.lon)*t,a.lat+(b.lat-a.lat)*t,0))}if(intersections.length===2){c.moveTo(intersections[0].x,intersections[0].y);c.lineTo(intersections[1].x,intersections[1].y)}}c.stroke();
   const drawPath=(positions:GeoPoint[],closed:boolean)=>{c.beginPath();positions.forEach((p,i)=>{const z=sampleElevation(grid,p.lon,p.lat);if(z===null)return;const q=project(p.lon,p.lat,z);if(i)c.lineTo(q.x,q.y);else c.moveTo(q.x,q.y)});if(closed)c.closePath();c.strokeStyle='#ffe299';c.lineWidth=2.5;c.stroke();if(closed){c.fillStyle='#ffe29920';c.fill()}};
   drawPath(points,mode==='Area'&&points.length>=3);points.forEach((p,i)=>{const z=sampleElevation(grid,p.lon,p.lat);if(z===null)return;const q=project(p.lon,p.lat,z);c.beginPath();c.arc(q.x,q.y,5,0,Math.PI*2);c.fillStyle='#ffe299';c.fill();c.font='bold 12px Arial';c.fillText(String(i+1),q.x+8,q.y-7)});
   if(probe&&probe.elevation!==null){const p=project(probe.lon,probe.lat,probe.elevation);c.strokeStyle='#ffffff';c.lineWidth=2;c.beginPath();c.arc(p.x,p.y,7,0,Math.PI*2);c.stroke()}
   activityHits.current=showActivity&&mode==='Explore'?drawActivities(c,project,activity,phases,highlight):[];
   hits.current=[];
   records.forEach((r,index)=>{if(layer!=='All'&&r.type!==layer)return;const loc=r,z=sampleElevation(grid,loc.lon,loc.lat);if(z===null)return;const p=project(loc.lon,loc.lat,z),slot=index%3,dx=(slot-1)*28,dy=slot%2?22:-10,q={x:p.x+dx,y:p.y+dy};c.strokeStyle=r.type==='Species'?'#c5e99a':r.type==='Habitat'?'#88ccd7':'#e9c48a';c.beginPath();c.moveTo(p.x,p.y);c.lineTo(q.x,q.y);c.stroke();c.beginPath();c.arc(q.x,q.y,selected===r.id?13:10,0,Math.PI*2);c.fillStyle=c.strokeStyle;c.fill();c.strokeStyle=selected===r.id?'#fff':'#132420';c.lineWidth=2;c.stroke();c.fillStyle='#14221b';c.font='bold 12px Arial';c.textAlign='center';c.fillText(String(index+1),q.x,q.y+4);hits.current.push({...q,r})});
   if(zoom<1.5){c.font='12px Arial';c.textAlign='center';for(const [name,lon,lat]of [['Annapolis',-76.492,38.978],['Baltimore',-76.612,39.29],['Cambridge',-76.076,38.563],['Crisfield',-75.858,37.983]] as [string,number,number][]){const z=sampleElevation(grid,lon,lat);if(z===null)continue;const p=project(lon,lat,z);c.fillStyle='#0c211ddd';const len=c.measureText(name).width;c.fillRect(p.x-len/2-4,p.y-11,len+8,18);c.fillStyle='#eef2d3';c.fillText(name,p.x,p.y+2)}}
  };
  draw();const ro=new ResizeObserver(draw);ro.observe(canvas);return()=>ro.disconnect();
 },[angle,tilt,zoom,exaggeration,layer,records,center,selected,points,mode,probe,surface,activity,showActivity,highlight]);
 const choosePoint=(p:GeoPoint)=>{const elevation=sampleElevation(grid,p.lon,p.lat);if(elevation===null){setNotice('That coordinate is outside the elevation grid.');return}setNotice('');setProbe({...p,elevation});if(mode==='Distance / profile'||mode==='Area')setPoints(v=>v.length>=20?v:[...v,p]);};
 const click=(x:number,y:number)=>{if(mode==='Explore'){const activityHit=activityHits.current.find(p=>Math.hypot(p.x-x,p.y-y)<24);if(activityHit){setPhaseId(activityHit.id);return}const hit=hits.current.find(p=>Math.hypot(p.x-x,p.y-y)<17);if(hit){onSelect(hit.r);return}}for(let i=faces.current.length-1;i>=0;i--){const [a,b,c]=faces.current[i].p;const den=(b.y-c.y)*(a.x-c.x)+(c.x-b.x)*(a.y-c.y);if(Math.abs(den)<1e-8)continue;const u=((b.y-c.y)*(x-c.x)+(c.x-b.x)*(y-c.y))/den,v=((c.y-a.y)*(x-c.x)+(a.x-c.x)*(y-c.y))/den,t=1-u-v;if(u>=0&&v>=0&&t>=0){choosePoint({lon:u*a.lon+v*b.lon+t*c.lon,lat:u*a.lat+v*b.lat+t*c.lat});return}}setNotice('Choose a point on the modeled surface.');};
 const reset=()=>{setAngle(-.22);setTilt(.85);setZoom(1);setCenter([-76.5,38.725])};
 const changeMode=(m:string)=>{setMode(m);setPoints([]);setNotice('')};
 const label=mode==='Area'?'Click three or more points to outline an area.':mode==='Distance / profile'?'Click two or more points for distance and a terrain profile.':'Click terrain to inspect its modeled elevation, or a numbered record.';
 return <div className="terrain-workspace"><div className="terrain-controls"><Choice label="Measurement tool" value={mode} set={changeMode} options={['Explore','Inspect','Distance / profile','Area']}/><Choice label="Terrain surface" value={surface} set={setSurface} options={['Land + seafloor','Seafloor only']}/><Choice label="Measurement units" value={units} set={setUnits} options={['Metric','Imperial']}/><div className="exaggeration"><span>Vertical scale <strong>{exaggeration}×</strong></span><Slider aria-label="Vertical exaggeration" value={[exaggeration]} min={1} max={300} step={1} onValueChange={v=>setExaggeration(v[0])}/></div></div>
 <div className="map-wrap terrain-map"><div className="map-top"><span><Layers size={15}/> Chesapeake · terrain & bathymetry</span><Choice label="Record layer" value={layer} set={setLayer} options={['All','Species','Habitat','Asset']}/></div>
 {showActivity&&mode==='Explore'&&<div className="activity-overlay-label">{activity.speciesId==='SP-001'?'Blue crab':'Eastern oyster'} · {activityWindow(activity).map(m=>monthNames[m].slice(0,3)).join(' / ')}<small>Cyan A markers · seasonal context, not tracking</small></div>}
 <canvas ref={ref} aria-label="Three-dimensional NOAA elevation and bathymetry model. Drag to orbit. Select Inspect or a measurement tool, then click the surface. Coordinate fields below provide a keyboard alternative." onPointerDown={e=>{drag.current={x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY,moved:false};e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{const d=drag.current;if(!d)return;const dx=e.clientX-d.x,dy=e.clientY-d.y;if(Math.hypot(e.clientX-d.startX,e.clientY-d.startY)>4)d.moved=true;if(d.moved){if(e.shiftKey){setCenter(([lon,lat])=>[lon-dx*.002/zoom,lat+dy*.002/zoom])}else{setAngle(v=>v+dx*.006);setTilt(v=>Math.max(.2,Math.min(1.57,v+dy*.005)))}}d.x=e.clientX;d.y=e.clientY}} onPointerUp={e=>{if(drag.current&&!drag.current.moved){const b=e.currentTarget.getBoundingClientRect();click(e.clientX-b.left,e.clientY-b.top)}drag.current=null}} onPointerCancel={()=>drag.current=null}/>
 <div className="map-tools"><button aria-label="Zoom in" onClick={()=>setZoom(v=>Math.min(5,v+.3))}><Plus/></button><button aria-label="Zoom out" onClick={()=>setZoom(v=>Math.max(.7,v-.3))}><Minus/></button><button aria-label="Rotate map" onClick={()=>setAngle(v=>v+.3)}><Move/></button><button aria-label="Top-down view" onClick={()=>{setTilt(Math.PI/2);setAngle(0)}}>2D</button><button aria-label="Reset three-dimensional view" onClick={reset}><RotateCcw/></button></div>
 <div className="terrain-legend"><span>Depth below NAVD 88</span><i/><span>Land elevation</span></div><div className="map-caption"><span>Drag: orbit / tilt · Shift-drag: pan</span><span>Vertical display {exaggeration}× · measurements use true values</span></div></div>
 <MapActivityControls selection={activity} onChange={value=>{onActivityChange(value);setShowActivity(true);const record=records.find(r=>r.id===value.speciesId);if(record&&selected!==record.id)onSelect(record)}} enabled={showActivity} onToggle={setShowActivity} phases={phases} highlight={highlight} onHighlight={setPhaseId} onFit={()=>{reset();setMode('Explore');setShowActivity(true)}} onProfile={onOpenCalendar} exploring={mode==='Explore'}/>
 <section className="measurement-panel" aria-label="Measurements"><div className="section-title"><h3>{mode==='Explore'?'Elevation inspector':mode}</h3><div className="measurement-actions"><button aria-label="Undo last measurement point" disabled={!points.length} onClick={()=>setPoints(v=>v.slice(0,-1))}><Undo2 size={16}/></button><button aria-label="Clear measurements" onClick={()=>{setPoints([]);setProbe(null);setNotice('')}}><Trash2 size={16}/></button></div></div><p className="subnote">{label} Up to 20 points.</p>
 <div className="measurement-readings" aria-live="polite"><div><small>Coordinates</small><strong>{probe?`${probe.lat.toFixed(4)}°, ${probe.lon.toFixed(4)}°`:'Select a point'}</strong></div><div><small>Elevation · NAVD 88</small><strong>{probe?.elevation!=null?heightText(probe.elevation):'—'}</strong></div><div><small>Depth below datum</small><strong>{probe?.elevation!=null?(probe.elevation<0?heightText(-probe.elevation):'Above datum'):'—'}</strong></div>{mode==='Distance / profile'&&<div><small>Horizontal path length</small><strong>{distanceText(total)}</strong></div>}{mode==='Area'&&<div><small>Approximate plan area</small><strong>{crossed?'Crossed outline':points.length>=3?areaText(areaMeters(points)):'Add 3+ points'}</strong></div>}</div>
 {crossed&&<p className="measurement-warning">The outline crosses itself. Undo a point to measure a simple polygon.</p>}{notice&&<p role="status" className="measurement-warning">{notice}</p>}
 <form className="coordinate-entry" onSubmit={e=>{e.preventDefault();const lat=Number(inputLat),lon=Number(inputLon);if(!inputLat.trim()||!inputLon.trim()||!Number.isFinite(lat)||!Number.isFinite(lon)){setNotice('Enter valid latitude and longitude.');return}choosePoint({lat,lon})}}><label>Latitude<input type="number" step="any" required value={inputLat} onChange={e=>setInputLat(e.target.value)}/></label><label>Longitude<input type="number" step="any" required value={inputLon} onChange={e=>setInputLon(e.target.value)}/></label><button className="secondary" type="submit">{mode==='Area'||mode==='Distance / profile'?'Add point':'Inspect coordinate'}</button></form>
 {mode==='Distance / profile'&&profile.length>1&&<div className="elevation-profile"><div className="section-title"><h3>Land / seafloor profile</h3><span>{distanceText(total)}</span></div><svg viewBox="0 0 600 150" role="img" aria-label={`Elevation profile. Lowest ${min.toFixed(1)} meters, highest ${max.toFixed(1)} meters relative to NAVD 88.`}><line x1="0" x2="600" y1={130-(0-Math.min(min,0))/Math.max(Math.max(max,0)-Math.min(min,0),1)*110} y2={130-(0-Math.min(min,0))/Math.max(Math.max(max,0)-Math.min(min,0),1)*110} stroke="#a5c7b4" strokeDasharray="4 4"/><polyline points={profile.filter(p=>p.elevation!==null).map(p=>`${p.distance/Math.max(total,1)*600},${130-((p.elevation??0)-Math.min(min,0))/Math.max(Math.max(max,0)-Math.min(min,0),1)*110}`).join(' ')} fill="none" stroke="#c5e99a" strokeWidth="2"/></svg><div className="profile-labels"><span>Start · 0</span><span>Low {heightText(min)} / high {heightText(max)}</span><span>End · {distanceText(total)}</span></div></div>}
 <p className="subnote">NOAA NCEI elevation model · NAVD 88 · reduced to about 610 × 790 m cells. Values are approximate model samples, not current water depth or navigation soundings. Negative heights mean below the datum; low-lying land can also be below it. Profile and distance measurements are independent of vertical exaggeration. <a href={grid.sourceUrl} target="_blank" rel="noreferrer">Data source</a></p></section>
 <div className="timeline"><div><Activity size={16}/> Conservation history <strong>{year}</strong></div><Slider aria-label="Conservation history year" min={2000} max={new Date().getUTCFullYear()} step={1} value={[year]} onValueChange={v=>setYear(v[0])}/><div className="time-label"><span>2000</span><span>{new Date().getUTCFullYear()} · PUBLISHED DATA</span></div>{active?(()=>{const metric=active.metrics.find(m=>m.id==="monthly_mean")||active.metrics[0];const observation=metric?.series.filter(o=>o.date.startsWith(String(year))).at(-1);return <p className="subnote">{active.name} · {metric?.label}: {observation?`${formatMetric(observation.value,metric.precision)} ${metric.unit} · ${observation.date} · ${observation.quality}`:"No published/imported value for this year."}<br/>{metric?.scope}</p>})():<p className="subnote">Select a record to inspect its published history.</p>}<p className="subnote">For monthly series, the latest published month in the selected year is shown. Markers stay fixed: no animal movement data is available. The NOAA terrain model does not change with the timeline; station water levels use a different datum.</p></div></div>
}
