import {useEffect,useRef,useState} from 'react';
import type {PointerEvent as ReactPointerEvent, RefObject} from 'react';
export type Camera={lon:number;lat:number;zoom:number};
const clamp=(v:number,a:number,b:number)=>Math.max(a,Math.min(b,v));
export function clampCamera(c:Camera):Camera{const zoom=clamp(c.zoom,1,16);return {zoom,lon:clamp(c.lon,-180+180/zoom,180-180/zoom),lat:clamp(c.lat,-90+90/zoom,90-90/zoom)}}
export function anchoredZoom(c:Camera,z:number,u=.5,v=.5):Camera{z=clamp(z,1,16);return clampCamera({zoom:z,lon:c.lon+(u-.5)*(360/c.zoom-360/z),lat:c.lat-(v-.5)*(180/c.zoom-180/z)})}
export function useAtlasCamera(surface:RefObject<SVGSVGElement|null>,expanded:boolean,onTap:(el:Element)=>void,onInteract:()=>void){
 const [camera,setCamera]=useState<Camera>({lon:0,lat:0,zoom:1});
 const current=useRef(camera),target=useRef(camera),animation=useRef(0),paint=useRef(0),points=useRef(new Map<number,{x:number;y:number}>()),tap=useRef(onTap);tap.current=onTap;const interact=useRef(onInteract);interact.current=onInteract;
 const gesture=useRef<{camera:Camera;x:number;y:number;distance:number;width:number;height:number;moved:boolean;el:Element;time:number;vx:number;vy:number;lastX:number;lastY:number}|null>(null);
 const reduced=()=>window.matchMedia('(prefers-reduced-motion: reduce)').matches;
 function stop(){cancelAnimationFrame(animation.current);animation.current=0;target.current=current.current}
 function commit(c:Camera){current.current=clampCamera(c);if(!paint.current)paint.current=requestAnimationFrame(()=>{paint.current=0;setCamera(current.current)})}
 function update(c:Camera,anchor?:[number,number]){stop();const from=current.current,to=clampCamera(c);target.current=to;if(reduced()){commit(to);return}const start=performance.now();function frame(now:number){const t=Math.min(1,(now-start)/360),k=t*t*(3-2*t),z=Math.exp(Math.log(from.zoom)+(Math.log(to.zoom)-Math.log(from.zoom))*k);commit(anchor?anchoredZoom(from,z,...anchor):{zoom:z,lon:from.lon+(to.lon-from.lon)*k,lat:from.lat+(to.lat-from.lat)*k});if(t<1)animation.current=requestAnimationFrame(frame);else animation.current=0}animation.current=requestAnimationFrame(frame)}
 function zoom(factor:number,u=.5,v=.5){interact.current();const z=target.current.zoom*factor;update(anchoredZoom(current.current,z,u,v),[u,v])}
 function center(){const p=[...points.current.values()];return {x:p.reduce((s,v)=>s+v.x,0)/p.length,y:p.reduce((s,v)=>s+v.y,0)/p.length,distance:p.length>1?Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y):0}}
 function rebase(el:Element,moved=false){const p=center(),rect=surface.current!.getBoundingClientRect();gesture.current={camera:current.current,x:p.x,y:p.y,distance:p.distance,width:rect.width,height:rect.height,moved,el,time:performance.now(),vx:0,vy:0,lastX:p.x,lastY:p.y}}
 function onPointerDown(e:ReactPointerEvent<SVGSVGElement>){if(e.button!==0)return;stop();e.currentTarget.focus({preventScroll:true});e.currentTarget.setPointerCapture(e.pointerId);points.current.set(e.pointerId,{x:e.clientX,y:e.clientY});rebase(e.target as Element,points.current.size>1)}
 function onPointerMove(e:ReactPointerEvent<SVGSVGElement>){if(!points.current.has(e.pointerId)||!gesture.current)return;points.current.set(e.pointerId,{x:e.clientX,y:e.clientY});const g=gesture.current,p=center(),dx=p.x-g.x,dy=p.y-g.y;g.moved ||= Math.hypot(dx,dy)>4||points.current.size>1;if(!g.moved)return;interact.current();let c=g.camera;if(g.distance&&p.distance){const rect=e.currentTarget.getBoundingClientRect();c=anchoredZoom(c,c.zoom*p.distance/g.distance,(g.x-rect.left)/g.width,(g.y-rect.top)/g.height)}commit({...c,lon:c.lon-dx/g.width*360/c.zoom,lat:c.lat+dy/g.height*180/c.zoom});target.current=current.current;const now=performance.now(),dt=Math.max(8,now-g.time);g.vx=.65*g.vx+.35*(p.x-g.lastX)/dt;g.vy=.65*g.vy+.35*(p.y-g.lastY)/dt;g.lastX=p.x;g.lastY=p.y;g.time=now}
 function cancel(){points.current.clear();gesture.current=null;stop()}
 function onPointerUp(e:ReactPointerEvent<SVGSVGElement>){const g=gesture.current;if(!g)return;points.current.delete(e.pointerId);if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);if(points.current.size){rebase(g.el,true);return}gesture.current=null;if(!g.moved){tap.current(g.el);return}if(reduced()||performance.now()-g.time>80||g.distance)return;let vx=clamp(g.vx,-1.2,1.2),vy=clamp(g.vy,-1.2,1.2),last=performance.now();function coast(now:number){const dt=Math.min(32,now-last);last=now;vx*=Math.exp(-dt/110);vy*=Math.exp(-dt/110);const c=current.current;commit({...c,lon:c.lon-vx*dt/g!.width*360/c.zoom,lat:c.lat+vy*dt/g!.height*180/c.zoom});target.current=current.current;if(Math.hypot(vx,vy)>.015)animation.current=requestAnimationFrame(coast)}animation.current=requestAnimationFrame(coast)}
 useEffect(()=>{const el=surface.current;if(!el)return;function wheel(e:WheelEvent){if(document.activeElement!==el&&!e.ctrlKey&&!e.metaKey)return;e.preventDefault();const rect=el!.getBoundingClientRect(),delta=e.deltaY*(e.deltaMode===1?16:e.deltaMode===2?rect.height:1);zoom(Math.exp(-clamp(delta,-120,120)*.0025),(e.clientX-rect.left)/rect.width,(e.clientY-rect.top)/rect.height)}el.addEventListener('wheel',wheel,{passive:false});return()=>{el.removeEventListener('wheel',wheel);cancel();cancelAnimationFrame(paint.current);paint.current=0}},[expanded]);
 return {camera,update,zoom,handlers:{onPointerDown,onPointerMove,onPointerUp,onPointerCancel:cancel,onLostPointerCapture:(e:ReactPointerEvent<SVGSVGElement>)=>{if(points.current.has(e.pointerId))cancel()},onDoubleClick:(e:React.MouseEvent<SVGSVGElement>)=>{const r=e.currentTarget.getBoundingClientRect();zoom(e.shiftKey?.5:2,(e.clientX-r.left)/r.width,(e.clientY-r.top)/r.height)}}};
}
