import {useEffect} from 'react';

// Sample the displayed artwork itself: fragments retain its colors and silhouette.
export function useObjectParticles(paused:boolean){useEffect(()=>{
 if(paused||matchMedia('(prefers-reduced-motion: reduce)').matches)return;
 const layer=document.createElement('canvas');layer.setAttribute('aria-hidden','true');Object.assign(layer.style,{position:'fixed',inset:'0',pointerEvents:'none',zIndex:'8'});document.body.appendChild(layer);const ctx=layer.getContext('2d')!;
 const cache=new WeakMap<Element,{pixels:Uint8ClampedArray;w:number;h:number}>();const originals=new Map<HTMLElement,string>();let frame=0,last=0;
 const sample=(el:HTMLImageElement|HTMLCanvasElement)=>{if(cache.has(el))return cache.get(el);try{if(el instanceof HTMLImageElement&&!el.complete)return;const c=document.createElement('canvas');c.width=96;c.height=96;const x=c.getContext('2d',{willReadFrequently:true})!;x.drawImage(el,0,0,96,96);const result={pixels:x.getImageData(0,0,96,96).data,w:96,h:96};cache.set(el,result);return result}catch{return undefined}};
 function draw(time:number){frame=requestAnimationFrame(draw);if(time-last<32||document.hidden)return;last=time;const dpr=Math.min(devicePixelRatio,1.5);if(layer.width!==innerWidth*dpr||layer.height!==innerHeight*dpr){layer.width=innerWidth*dpr;layer.height=innerHeight*dpr;}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,innerWidth,innerHeight);
 document.querySelectorAll<HTMLImageElement|HTMLCanvasElement>('.lh-main img,.lh-main canvas').forEach(el=>{const r=el.getBoundingClientRect();if(r.width<50||r.height<50||r.bottom<0||r.top>innerHeight)return;const amount=Math.min(1,Math.max(0,(innerHeight-r.top)/(innerHeight*.32)),Math.max(0,r.bottom/(innerHeight*.28)));if(amount>=1){if(originals.has(el))el.style.opacity=originals.get(el)!;return;}const data=sample(el);if(!data)return;if(!originals.has(el))originals.set(el,el.style.opacity);el.style.opacity=String(Math.max(0,(amount-.88)/.12));const spread=(1-amount)**2;ctx.globalAlpha=Math.min(1,amount*4)*(1-Math.max(0,(amount-.88)/.12));for(let y=0;y<96;y+=2)for(let x=0;x<96;x+=2){const k=(y*96+x)*4;if(data.pixels[k+3]<30)continue;const seed=x*17.3+y*41.7;ctx.fillStyle=`rgb(${data.pixels[k]},${data.pixels[k+1]},${data.pixels[k+2]})`;const px=r.left+x/96*r.width+Math.sin(seed)*spread*200,py=r.top+y/96*r.height+Math.cos(seed)*spread*130;ctx.fillRect(px,py,Math.max(1,r.width/48*amount),Math.max(1,r.height/48*amount));}ctx.globalAlpha=1;});}
 frame=requestAnimationFrame(draw);return()=>{cancelAnimationFrame(frame);layer.remove();originals.forEach((opacity,el)=>el.style.opacity=opacity)};
 },[paused]);}
